### ISSUE TITLE
snapToRoads always throws error

### ISSUE THREAD

**Issue by bolav** [googlemaps/google-maps-services-js#100]
Seems like the response from snapToRoads is missing `response.json.status` which means that this test fails: https://github.com/googlemaps/google-maps-services-js/blob/1715534101af1de3668bcfacd425806478b30641/lib/internal/make-api-call.js#L102

**Comment by stephenmcd** [comment]
Thanks a lot for the report. I just pushed 0.4.1 to npm which should fix this.
