### ISSUE TITLE
getting CORS error with distanceMatrix

### ISSUE THREAD

**Issue by paulous** [googlemaps/google-maps-services-js#102]
The error:
Fetch API cannot load https://maps.googleapis.com/maps/api/distancematrix/json?destinations=-33.9…9%2C%20151.230326&units=metric&key=...the_key.... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

The url works...
Not really sure what to do about this kind of error. Any ideas?

I should mention that I can use the reverseGeocode() without a problem.

**Comment by stephenmcd** [comment]
See https://github.com/googlemaps/google-maps-services-js/issues/59#issuecomment-282595007

**Comment by paulous** [comment]
Thanks. I will assume that this is just my lack of understanding and not a flaw with the library or vuejs. I am using vue-cli, webpack-dev-server and have no real clue how I would implement it there, or even if it would be appropriate.
