### ISSUE TITLE
placesPhoto callback not error first

### ISSUE THREAD

**Issue by sumpton** [googlemaps/google-maps-services-js#104]
I must be missing something. I recently updated from 3.1 and find that my scripts calling placesPhoto appear to not return a callback with err first. It is as if the response is the only thing returned.

I looked through all the code, issues, and docs, and callback (err, response) works as it did for other methods, like

> https://googlemaps.github.io/google-maps-services-js/docs/ResponseCallback.html

It would look like a bug, but don't see what has changed, and it has been since 4.0.

Is there a change log?

I appreciate this library, and help understanding my error.

**Comment by sumpton** [comment]
I would sure appreciate some help or direction with this.

Is there a plunker for this library?

**Comment by stephenmcd** [comment]
It was a regression that occurred with some large changes since 0.3.1

Just pushed 0.4.3 with the fix.
