### ISSUE TITLE
placesAutoComplete wrong query componens convert

### ISSUE THREAD

**Issue by aduycuong** [googlemaps/google-maps-services-js#105]
Wrong query componens convert:
https://github.com/googlemaps/google-maps-services-js/blob/master/lib/internal/convert.js		
googleMapsClient.placesAutoComplete({
			input: '...',
			components: 'country:vn' // convert to '0:c|1:o|2:u|3:n|4:t|5:r|6:y|7::|8:v|9:n'
		}, (err, response) => {})

**Comment by stephenmcd** [comment]
Try `components: {country: 'vn'}`
