### ISSUE TITLE
TypeScript 2 definitions for Google Maps API

### ISSUE THREAD

**Issue by luciano-aguirre** [googlemaps/google-maps-services-js#106]
I'm working with TypeScript 2 and Node JS. I'm trying to install Google Maps, but I'm not having success. I install the Google Maps library with "npm install @google/maps" and the typescript definitions with "npm install @types/googlemaps". The problem is they have different names! So the compiler tell me "Cannot find module "@google/maps" when I write require("@google/maps").
I would be very gratefully if you could help me.
Thanks!

**Comment by stephenmcd** [comment]
Not sure what the solution is, but this is probably a subset of #42
