### ISSUE TITLE
exceptions swallowed in nodejs

### ISSUE THREAD

**Issue by jsuiker** [googlemaps/google-maps-services-js#109]
I expect that an exception thrown within the geocode callback would bubble up and kill my process...
```
'use strict'

var google_maps = require('@google/maps'),
    config = require('./config'),
    gm = google_maps.createClient({key: config.googleMaps.api_key}),
    address = '1 Infinite Loop Cupertino, CA'


gm.geocode(
    { address: address },
    (err, response) => {
        if (err) return console.log(err)
        console.log('received results for ' + address)
        throw(new Error('SomeKindOfError'))
    })


setTimeout(
    () => {
        throw new Error('SomethingSpecial');
    }, 2000)
```

**Comment by brahmos** [comment]
I'm seeing the same and it makes it difficult to debug, I would rather have node crash to see what's wrong then having to run it in a debugger and trace it.

Looks like it's getting caught in tasks.js 

https://github.com/googlemaps/google-maps-services-js/blob/master/lib/internal/task.js#L240

**Comment by artofspeed** [comment]
Errors should always be logged and handled gracefully. It's not always optimal to just let server crash in order to debug the errors out, especially in production environment. Your application should be coded in such way to log & trace errors reasonably easily.

**Comment by brahmos** [comment]
Agree, not disputing that. But when you are developing, you are better off seeing what happens as it happens, in this case, an expected crash. But here,  I get a request that never comes back because unexpectedly a bug is causing an exception to be caught.

**Comment by talawahtech** [comment]
I just got bitten by this as well. There was a programming error in my error handling code ("Cannot read property 'statusCode' of undefined") and it just got silently swallowed. I am not sure how this *should* be handled, but the current approach is pretty confusing and time consuming for the developer.

After looking at the code in question I switched to using the Promise API instead. At least when I do that I get notified about the unhandled rejection, and I have the option to add another catch statement. 

Perhaps you should promote the use of the Promise API over the Callback API or at least add a note indicating the risk of exceptions being swallowed.

**Comment by DaddyWarbucks** [comment]
I have worked with this library quite a bit and always used this little wrapper. I decided to throw it in a gist to share. Its configured for promises, rather than the callbacks, but it should handle all of the cases where this library throws weird errors.
https://gist.github.com/DaddyWarbucks/2b1edc1aa6ad716f54f5dd1906d92b7f

**Comment by jpoehnelt** [comment]
I recommend using the Axios and TypeScript based rewrite of this library now: https://www.npmjs.com/package/@googlemaps/google-maps-services-js/v/2.0.1
