### ISSUE TITLE
Speed Limits with "path" instead of "placeId" doesn't work

### ISSUE THREAD

**Issue by odubuc** [googlemaps/google-maps-services-js#111]
using v0.4.3

according to the [documentation](https://developers.google.com/maps/documentation/roads/speed-limits):
> Required parameters: Either a path or one or more placeIds.

I am unable to call `speedLimits()` with the parameter `path`  I'm always getting the following error message: `missing property "placeId"`. or `unexpected property "path"` if I specify both.

code used:
```
import * as GoogleMaps from '@google/maps';

var googleMapsClient = GoogleMaps.createClient({
    key: '<key>'
});

googleMapsClient.speedLimits({
    path: '60.170880,24.942795|60.170879,24.942796|60.170877,24.942796'
}, function(err, response){
    console.log(err, response)
});
```

**Comment by stephenmcd** [comment]
In this library, using `path` is broken out into its own method, `snappedSpeedLimits`. 

I just pushed 2561db7300be831b1b8bd0db3e0e749f0192c9bc which clarifies that a bit.

**Comment by odubuc** [comment]
Thank you, I missed the other function. 
would be great to have a list of available function inside the readme
