### ISSUE TITLE
PlacesNearby API bug

### ISSUE THREAD

**Issue by rotero** [googlemaps/google-maps-services-js#112]
Hi, the placesNearby call allows for the parameter "rankby" with values ["prominence","distance"].

That results in the URL for the request to add the query param "&rankby=VALUE". 

Now the funny thing is that with prominence it works all fine, but with  distance it doesn't. 
The request result in a invalid request error. 
The reason seems to be that a request with the URL "&rankby=prominence" works but "&rankby=distance" doesn't!

BUT "&rank**B**y=distance" works so does "&rank**B**y=prominence" !!

easy fix would therefore be to rename the query param output from "rankby" to "rankBy"

**Comment by stephenmcd** [comment]
Guessing you're also using the `radius` param, which is invalid when using `rankby=distance`, as per: https://developers.google.com/places/web-service/search

> Note that radius must not be included if rankby=distance (described under Optional parameters below) is specified.
