### ISSUE TITLE
Using LatLngBounds for nearby search for Places

### ISSUE THREAD

**Issue by deeMaj** [googlemaps/google-maps-services-js#116]
I read in the google documentation that there is a possibility to include LatLngBounds object instead of location+radius when searching for places, however I have not found any examples for it. I would appreciate a little help in figuring out how to use that particular search parameter. 
Thanks a lot,
Deepanjana

**Comment by stephenmcd** [comment]
You're confusing the client-side JavaScript API with the server-side web service that this library is a client for.
