### ISSUE TITLE
Why cant I use Google Maps Places Web Services from frontend

### ISSUE THREAD

**Issue by vamsiampolu** [googlemaps/google-maps-services-js#117]
https://issuetracker.google.com/issues/66923535

I have added this codepen as well, https://codepen.io/vamsiampolu/pen/ZXLvoB

I have been trying it with various referrers and various permissions. Why do I have to load 26KB library instead of using a single API call.

There are many unanswered questions that either suggest using JSONP or CORS Anywhere or a server side proxy, why cant I use the API directly.

https://stackoverflow.com/search?q=%5Bgoogle-places-api%5D+CORS

Can you provide an example / reference me to a post of appropriate config for using the Places API on the frontend with the API config referred correctly.

**Comment by stephenmcd** [comment]
The issuetracker you opened the first issue in is the correct place to report this.
