### ISSUE TITLE
How to use distance matrix api with LatLng origin and destination

### ISSUE THREAD

**Issue by monajafi** [googlemaps/google-maps-services-js#118]
In my app I have to use latitude and longitude in origin and destination not the address.
I've tried 'latitiude,longitude' literal for  example '30.3453463,80,34534534' in origin or destination field in this way:
origins: ['30.3453463,80,34534534']
destinations:['30.34545463,80,34536534']

but this leads to { InvalidValueError: in property "origins": at index 0: undefined
    at Function.InvalidValueError.prepend  error
what is the correct way of using lat.  long. in origins and destinations fileds

**Comment by stychu** [comment]
try with
origins: [{lat:30.3453463, lng:80.34534534}]
destinations:[{lat:30.34545463, lng:80.34536534}]

also look at the commas in the geo locs. Idk if you did it by mistake writing this example or you do have commas in the locations number itself

**Comment by monajafi** [comment]
Thanks, It is working now, but the results for same origin and destinations are not consistent at same time request from android call to node.js. the android api response is consistent but node.js is not like android one
