### ISSUE TITLE
DistanceMatrix bug

### ISSUE THREAD

**Issue by stychu** [googlemaps/google-maps-services-js#119]
Hello,
When trying to use distancematrix for 1 origin and 210 destinations i get some error and i think its bugged.
Because when i did try do direct call for http not by your api i can make this kind of request and will recieve 210 to 1 origin calculations but with your api maximum number I could get was 180 to 1.

Also on quotas google its saying to max 25x25 originsXdestinations could be send for one request this gives 625 elements but why I can't make 1x624. Do you know maybe ?

**Comment by stephenmcd** [comment]
Can you provide the values you're using to make the requests for both the client library and directly to the web service?

**Comment by stephenmcd** [comment]
Please re-open if you can provide detail on reproducing the issue.
