### ISSUE TITLE
Unable to resolve module util from @google/maps/lib/index.js

### ISSUE THREAD

**Issue by dflourusso** [googlemaps/google-maps-services-js#121]
Unable to resolve module **util** from `@google/maps/lib/index.js`
Why i got this error?

**Comment by stephenmcd** [comment]
I'm not sure how you got there, but you've somehow managed to not install teh library properly. Please report back if work out what when wrong.

**Comment by goulkreek** [comment]
Same issue on my part too.
Just followed the google instructions at [https://github.com/googlemaps/google-maps-services-js](https://github.com/googlemaps/google-maps-services-js)

> npm install @google/maps

Please keep issue open

**Comment by tejesh014** [comment]
I'm getting the same error when trying to access through ES6 way (through import). Trying to use this with React Native.

**Comment by unicornRainbows** [comment]
Yeah.. seems like we going to have to do the request ourselves using any of the http request guys.. not ideal..

**Comment by huybuidac** [comment]
same here with tsx and yarn add -D @types/google__maps
