### ISSUE TITLE
Crashing the whole app: "SyntaxError: Unexpected end of JSON input"

### ISSUE THREAD

**Issue by elrichs** [googlemaps/google-maps-services-js#122]
I use the googleMapsClient to reverse geocode. Most of the time it works without a problem, however seemingly for no apparent reason from my side, sometimes googleMapsClient throws an exception that is not caught by any error handlers and it crashes the whole app. It would seem that the problem is coming from within the library. I use `node v6.11.2` and `@google/maps v0.4.3`. Here's my code:

```
const googleMapsClient = require('@google/maps').createClient({
  key: 'APIKEY',
  rate: {limit: 120},
  timeout: 2000,
  Promise: Promise
})
```
```
//called from within async library's "each" method

try {

     //extract coordinates from the object, check cache, if empty give coordinates to googleMapsClient

googleMapsClient.reverseGeocode({latlng: [lat, lon]}).asPromise()
          .then(response => {
            let googleResponse = null;
            if (response.json.results[2]) {
              googleResponse = response.json.results[2].formatted_address
            } else if (response.json.results[1]) {
              googleResponse = response.json.results[1].formatted_address
            } else if (response.json.results[0]) {
              googleResponse = response.json.results[0].formatted_address
            }
                   //do something with the response (nullcheck, assign to object, put in cache)
                   callback()
        }).catch((err) => {
          object.locationString = null;
          callback()
        })
  } catch (e) {
    //log error
    callback()
  }
```
This is the exception stacktrace: 
```
{"date":"Tue Oct 03 2017 07:20:02 GMT+0000 (UTC)","process":{"pid":27006,"uid":1000,"gid":1000,"cwd":"/home/folder/project","execPath":"/usr/bin/nodejs","version":"v6.11.2","argv":["/usr/bin/nodejs","/home/folder/project/server.js"],"memoryUsage":{"rss":100712448,"heapTotal":58740736,"heapUsed":49848408,"external":878295}},"os":{"loadavg":[3.359375,3.21337890625,2.24609375],"uptime":3418282},"trace":[{"column":null,"file":null,"function":"Object.parse","line":null,"method":"parse","native":true},{"column":22,"file":"/home/folder/project/node_modules/@google/maps/lib/internal/make-url-request.js","function":null,"line":87,"method":null,"native":false},{"column":20,"file":"events.js","function":"emitNone","line":91,"method":null,"native":false},{"column":7,"file":"events.js","function":"IncomingMessage.emit","line":185,"method":"emit","native":false},{"column":12,"file":"_stream_readable.js","function":"endReadableNT","line":974,"method":null,"native":false},{"column":11,"file":"internal/process/next_tick.js","function":"_combinedTickCallback","line":80,"method":null,"native":false},{"column":9,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":104,"method":"_tickCallback","native":false}],"stack":["SyntaxError: Unexpected end of JSON input","    at Object.parse (native)","    at IncomingMessage.<anonymous> (/home/folder/project/node_modules/@google/maps/lib/internal/make-url-request.js:87:22)","    at emitNone (events.js:91:20)","    at IncomingMessage.emit (events.js:185:7)","    at endReadableNT (_stream_readable.js:974:12)","    at _combinedTickCallback (internal/process/next_tick.js:80:11)","    at process._tickCallback (internal/process/next_tick.js:104:9)"],"level":"error","message":"uncaughtException: Unexpected end of JSON input","timestamp":"2017-10-03T07:20:02.331Z"}
```

**Comment by Liamdelee** [comment]
hi there,
just a quick question is there any reason why you use rate: {limit: 120}, because it is in milliseconds and if you look at the doc they use a standard of Timeout in milliseconds. (Default: 60 * 1000 ms). maybe it is to slow to parse that it will crash it or something? not sure at all that is the prob, but i never had a prob with it and i did not have that one set so maybe try it out and see.

**Comment by thirstyfish** [comment]
Hi,
I've started to experience the same issue a few days ago, and now it happened 3 times.
I'm using the _snapToRoads_ and _speedLimits_ methods on the client.
I've been running the app in prod for about 7 month now, making about 1 request every 10 seconds and never had this issue before. Seems like the Google API cuts the response in half which results in an invalid JSON response that crashes the client on JSON.parse() in _make-url-request.js_ ...
Any thoughts on this?

Thanks

**Node version: 4.6.1 (running inside Docker)
@google/maps version: 0.3.1**

Stacktrace:
```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/app/node_modules/@google/maps/lib/internal/make-url-request.js:67:22)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
```

**Comment by llaakso** [comment]
Following code in @google/maps/lib/internal/make-url-request.js needs try-catch when parsing JSON:

`     var data = [];
      response.on('data', function(chunk) {
        data.push(chunk);
      });
      response.on('end', function() {
        onSuccess({
          status: response.statusCode,
          headers: response.headers,
          json: JSON.parse(Buffer.concat(data).toString())
        })
      });
`

**Comment by pisaacs** [comment]
Confirming @llaakso recommendation. 

After loading hundreds of records, my app suddenly crashed. Hopefully this can be fixed ASAP, since there are charges when calling the API, and in my case, I have to rerun the entire process. 

https://github.com/googlemaps/google-maps-services-js/blob/22e98d4946321b6ff968848edbd9dda4c4e70166/lib/internal/make-url-request.js#L87

```
undefined:69
            "grocery



SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (C:\...\node_modules\@google\maps\lib\internal\make-url-request.js:87:22)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by FredH76** [comment]
I just had the same issue using cordova.
It came from a corrupted file in my platform.
I solved it this way:
1- remove platform (cordova platform remove _your-platform_)
2- add it again (cordova platform add _your-platform_)
Then my code worked fine again when I ran it (cordova run _your-platform_)

**Comment by dee-g** [comment]
When I limited the number of calls being made to places API ,this JSON error is not coming up .Otherwise if we make parallel calls without any limit to the API ,then jumbled JSON issue is crashing the application.
