### ISSUE TITLE
Time Zone Parameter Confusion

### ISSUE THREAD

**Issue by micahalcorn** [googlemaps/google-maps-services-js#123]
If I make a request to the Time Zone api without a timestamp, I'm getting an `INVALID_REQUEST` in the response. As far as the api is concerned, `timestamp` is required. The documentation for this package says that it is optional. This is probably because the `timeStamp` [convert function is supposed to fall back to the current time if it is undefined](https://github.com/googlemaps/google-maps-services-js/blob/4282e1345daca8239ed1ee936022946be60f47e0/lib/internal/convert.js#L68-L80). For some reason it is not working for me.

**Without** `timestamp`
```
GoogleMaps.timezone({ location }).asPromise().then(res => { console.log(res); }).catch(err => { console.log(err); });
```
```
...
json: { status: 'INVALID_REQUEST' },
requestUrl: 'https://maps.googleapis.com/maps/api/timezone/json?location=35.2176522%2C-97.4949963&key=obfuscated',
query: 
  { location: '35.2176522,-97.4949963',
    key: 'obfuscated' } }
...
```

**With** `timestamp`
```
GoogleMaps.timezone({ location, timestamp: new Date() }).asPromise().then(res => { console.log(res); }).catch(err => { console.log(err); });
```
```
...
json: 
  { dstOffset: 3600,
    rawOffset: -21600,
    status: 'OK',
    timeZoneId: 'America/Chicago',
    timeZoneName: 'Central Daylight Time' },
requestUrl: 'https://maps.googleapis.com/maps/api/timezone/json?location=35.2176522%2C-97.4949963&timestamp=1507751660&key=obfuscated',
query: 
  { location: '35.2176522,-97.4949963',
    timestamp: 1507751660,
    key: 'obfuscated' } }
...
```

*Package version 0.4.3*

**Comment by stephenmcd** [comment]
Thanks for the detail - I just pushed 0.4.5 which should fix this.
