### ISSUE TITLE
Places: Allow multiple country:XX in component param

### ISSUE THREAD

**Issue by denkan** [googlemaps/google-maps-services-js#128]
According to [the docs](https://developers.google.com/places/web-service/autocomplete), we're suppose to be able to filter search results to up to 5 countries by adding multiple piped `country:xx`, as `components=country:us|country:pr|country:vi|country:gu|country:mp`.

However, this is not possible when current param type is an object, as `component:{country:'us'}`.

I've tried different ways with string, arrays etc with no luck. 

**Suggestion**: 
Accept object OR string as `component` param.

**Comment by v1adko** [comment]
I agree, this would be very useful. Also would like to know if there's a way to sort suggestions or assign priority? In my use case it would be useful to have suggestions first grouped/filtered by a certain country and only then list suggestions for all countries (without the country limitation) as there is [this open issue](https://issuetracker.google.com/issues/68932240).

**Comment by zuperm4n** [comment]
I am able to filter by one country only in `v0.4.6` like so:

```
{
    input: <input>,
    components: {
        country: ["gb"]
    }
}
```

Filtering by multiple countries as mentioned in the [docs](https://developers.google.com/places/web-service/autocomplete) would be great but not essential for me right now. I may pull-request a fix if I get some time...

**Comment by dunika** [comment]
Okay after digging into the code there seems to be a bug with how it is building the query. According to the docs the string produced needs to be in the form `country:code|country:code` but when you pass multiple country codes as an array it produces `country: code, code`.

I was able to get multiple countries working with the following

```
components: { country: ['gb|country:ie'] },

```

Which produces the query

```
 components: 'country:gb|country:ie'
```

**Comment by george-dotdev** [comment]
I switched the pipedKeyValues for this:

```
exports.pipedKeyValues = function(arg) {
  if (!arg || typeof arg !== 'object') {
    throw new v.InvalidValueError('not an Object');
  }
  const pipedKeys = [];
  for (const key of Object.keys(arg)) {
    for (let k = 0; k < arg[key].length; k += 1) {
      pipedKeys.push(`${key}:${arg[key][k]}`)
    }
  }
  return pipedKeys.join('|')
};
```
And it worked. It's not very efficient but it's okay.

**Comment by stephenmcd** [comment]
This is resolved in #192

**Comment by eveevans** [comment]
> Okay after digging into the code there seems to be a bug with how it is building the query. According to the docs the string produced needs to be in the form `country:code|country:code` but when you pass multiple country codes as an array it produces `country: code, code`.
> 
> I was able to get multiple countries working with the following
> 
> ```
> components: { country: ['gb|country:ie'] },
> ```
> 
> Which produces the query
> 
> ```
>  components: 'country:gb|country:ie'
> ```

This is wrong. 
Component Filtering documentations says that this filter should works as an "AND" not as an "OR", so in your case, this filter by `gb and  ie` , not `gb or ie`


https://developers.google.com/maps/documentation/geocoding/intro#ComponentFiltering

**Comment by dunika** [comment]
@eveevans Ye, I know it's an AND query. My comment was more a means of getting it to work
