### ISSUE TITLE
ENOTFOUND when I can access to place photos

### ISSUE THREAD

**Issue by leonraf** [googlemaps/google-maps-services-js#130]
Hello,
I have a problem when use placesPhoto. The method return an error:

`{"results":{"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"lh3.googleusercontent.com","host":"lh3.googleusercontent.com","port":443}}`

I run the method on firebase cloud functions.

**Comment by stephenmcd** [comment]
Sounds like a network error, not an issue with this library itself.
