### ISSUE TITLE
How to use the "geometry" library?

### ISSUE THREAD

**Issue by cx-tim** [googlemaps/google-maps-services-js#132]
I would like to use the [isLocationOnEdge](https://developers.google.com/maps/documentation/javascript/geometry#isLocationOnEdge) function of the geometry library. An utils library is implemented for [Android](https://github.com/googlemaps/android-maps-utils). Is there an utils library for NodeJS?

Thanks!

**Comment by stephenmcd** [comment]
This library is unrelated to the client-side feature you're referring to.
