### ISSUE TITLE
Broken link to the API Methods [docs]

### ISSUE THREAD

**Issue by v1adko** [googlemaps/google-maps-services-js#134]
Here in [HOME.md](https://github.com/googlemaps/google-maps-services-js/blob/master/docs/HOME.md) API Methods link is broken. I would gladly open a PR if I knew what is the new link.

Was looking to get information on `componentRestrictions` parameter in the places autocomplete API, but could not find the docs (and sadly this repo seem not to showcase autocomplete abilities at all).

**Comment by stephenmcd** [comment]
It's a relative link intended to be viewed from https://googlemaps.github.io/google-maps-services-js/docs/

**Comment by v1adko** [comment]
Oh, yeah, I missed the "reference documentation" link in readme, sorry.
All of the prominent links led to "developers.google.com".
Thank you.
