### ISSUE TITLE
Using Geo Intents for multiple poinst

### ISSUE THREAD

**Issue by blgsyrmhnds** [googlemaps/google-maps-services-js#136]
Hi 
'geo:' property only for one point but I need multiple points

geo:latitude,longitude
https://developer.android.com/guide/components/intents-common.html#Maps

//geoURL='geo:'+originLat+','+originLot+'q='+DestinationLat+','+DestinationLong;
            var geoURL='maps://?q='+DestinationLat+','+DestinationLong;
             window.open(geoURL,'_blank');

in my app(JS) user click "open with google maps navigation" button and I navigate my user current location to selected point(latitude,longitude) but now I need to navigate my user to point A,then point B and finally Point C

how can I handle that?Can I use geo: with multiple points such as 
geo:[latitude,longitude;latitude1,longitude1;latitude2,longitude2] how can I fix that problem?are there any alternatives with google maps navigation? There is waypoints but it does not work with google maps navigation

**Comment by amuramoto** [comment]
You can use the directions API support in this lib, and provide multiple waypoints in the request:

https://github.com/googlemaps/google-maps-services-js/blob/master/lib/apis/directions.js
