### ISSUE TITLE
reverseGeocode does not work properly

### ISSUE THREAD

**Issue by psychedelics** [googlemaps/google-maps-services-js#138]
hi, 

Using **reverseGeocode**() function does not work properly.

maybe the problem  is in my code or maybe not so here is : 

`var googleMapsClient = google.createClient({
key: 'my_valid_key'
});`
`var latlng = {lat:parseFloat(latv), lng:parseFloat(longv)};`
  `googleMapsClient.reverseGeocode({'latlng': latlng}, function(results, status) {`
      `if (status == 'OK') {`
       ` adresse_geocoded = results[0].geometry.location;`
        `ville_geocoded = results[1].geometry.location;  `
    `  } `
      `else if (status.status == '200'){`
          `console.log("results ", results);`
    `  }`
      `else {`
       ` //console.error('Geocode was not successful for the following reason: ' + JSON.stringify(status));`
        `Object.keys(status).forEach(function(key) {`
          `console.log('Key : ' + key + ', Value : ' + status[key])`
       ` })`
     ` }`
   ` });`

**results** is null but if i check **status** it contains my request and my coord geocoded.

Furthermore **status** contain URL called too (https://maps.googleapis.com/maps/api/geocode/[...]) and if i try this url in my broswer it works fine(tell me **status** 'OK' etc... )

so what's wrong plz ?

**Comment by stephenmcd** [comment]
Looks like you have the callback args defined incorrectly, please see the examples in the readme.

**Comment by cutiko** [comment]
Greetings

I'm sorry if reviving this thread is uncalled but I'm confused. What do you mean by ` please see the examples in the readme`?

There is no example in this [README](https://github.com/googlemaps/google-maps-services-js/blob/master/README.md) and neither on [this](https://github.com/googlemaps/google-maps-services-js/blob/master/docs/HOME.md). I was excited to see there is a [Wiki](https://github.com/googlemaps/google-maps-services-js/wiki) but is empty.

For further details documentation here points to the Google official doc, in this case, the example would be the [following](https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse):

```
 geocoder.geocode({'location': latlng}..
```

But if I do that I get `InvalidValueError: unexpected property "location"`.

So I have changed my `reverseGeocode` argument to `{'latlng': latlng}` as the initial post did and it does work. 

Couldn't find any examples of `reverseGeocoding`, am I missing something?

**Comment by stephenmcd** [comment]
All the param names are here: https://googlemaps.github.io/google-maps-services-js/docs/GoogleMapsClient.html

**Comment by NickSutton** [comment]
> All the param names are here: https://googlemaps.github.io/google-maps-services-js/docs/GoogleMapsClient.html

Error404 - Am I also missing something or is the documentation notably lacking for this package?
