### ISSUE TITLE
[Feature Suggestion]: Default rate limits that confirm to the free tier usage quotas

### ISSUE THREAD

**Issue by brickcap** [googlemaps/google-maps-services-js#142]
Hi,

Thank you for creating this library. I've a small suggestion. The default [rate limit](https://googlemaps.github.io/google-maps-services-js/docs/index.html) of the library is 10 rps. That is way above the web api [default limit](https://developers.google.com/maps/faq#usagelimits) of 2500 reqs/day. It would be great if the defaults could be aligned with the free tier usage quota. And let the users explicitly override the defaults to their desired usage only if there is a paid plan in place. 

Right now I'm initializing the client to [override](https://github.com/googlemaps/google-maps-services-js/blob/master/lib/internal/make-api-call.js#L29) the default 10 req/sec api limit like this
```
var googleMapsClient = require('@google/maps').createClient({
    key: 'your api key',
    rate:{
	limit:2500,
	period:86400000
    }
});

```
What do you think? 

Thanks,
Akshat

**Comment by stephenmcd** [comment]
You're looking at the daily limits for all of the services, however most of them implement a per-second limit as well as noted in each of their individual documentation sections. 

The QPS limit was previously 10 but has recently been raised to 50, so we'll need to update that, but  we'll still keep a per-second default in place.

**Comment by brickcap** [comment]
Thank you @stephenmcd ! Can you please clear up something for me? Am I billed according to the daily limits or according to the QPS? 

Thanks a lot for your quick response. 

Best Regards,
Akshat
