### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by michael-letcher** [googlemaps/google-maps-services-js#143]
Could we have some working examples on how to use this API and or some real documentation on the API itself.

I've found the only reliable way is to  go through the code to lean how it all works?

Which is very poor.

**Comment by realyashnag** [comment]
THANK YOU! I've been looking for hours and couldn't find one proper reference or example. Looking through the code is probably, STILL, the only way to understand and use this lib.

**Comment by andersondsl** [comment]
Don't know about you guys, but i always look into the test scenarios to know more about projects, and this is the way i`m teaching myself about this project. Good test cases are always the best documentation you will find in any project.
