### ISSUE TITLE
Disabling Retries

### ISSUE THREAD

**Issue by Synthoova** [googlemaps/google-maps-services-js#144]
Is it possible to turn the retry behaviour off completely or limit the number of retry attempts?

I'm executing on Firebase Cloud Functions, and if a server error occurs (in my case, I hit a DNS Resolution quota) my call to `googleMapsClient.placesNearby(parameters).asPromise()` causes Errors to come back again and again until the quota has refreshed or I force the Cloud Function to stop.

**Comment by andersondsl** [comment]
Hi @Synthoova, maybe what you are looking for is the rate Limit, this controls rate-limiting of requests. is 50 per default. You can look to all possible configurations here.

https://github.com/googlemaps/google-maps-services-js/blob/master/lib/index.js#L37

Give me a shout if this works for you.

**Comment by Synthoova** [comment]
Yes, that would help.

Thanks for the input!
