### ISSUE TITLE
What happen with .place() function

### ISSUE THREAD

**Issue by thanhinterpol** [googlemaps/google-maps-services-js#145]
My code: 

> var googleMapsClient = require('@google/maps').createClient({
> key: 'my-key',
> Promise: Promise
> });

> async function placeDetail(place_id){
>     let detail = await googleMapsClient.place({
>         placeid: place_id
>       }).asPromise().then(function(response) {
>         console.log("HAHA: " + response.json.results);
>        return response.json.predictions;
>       });
>     return detail;
> }

I have an issue, when I use place function to get place info detail, I got "response.json" is an object, however I can't select anything else in this object.
p/s: While, I can get information normally with Http client.

**Comment by pawarvijay** [comment]
[From LOVELY testcases 
](https://github.com/googlemaps/google-maps-services-js/blob/f9f2d55fa58722a02bd4d8a5cb0eb8aee9ca7faa/spec/e2e/places-spec.js#L149)

```
googleMapsClient.place({
		placeid: 'ChIJzTXekTbB5zsRxRfqh-f4Rb8',
		language: 'fr',
		fields: ['name', 'rating', 'formatted_phone_number', 'geometry'],
	},
	(err, response) => {
		if (!err) {
			console.log(response.json);
		}
	}
);
```

**Comment by pawarvijay** [comment]
please close this issue its answered
