### ISSUE TITLE
Marker blinks when user moves using Geolocation

### ISSUE THREAD

**Issue by azamalvi** [googlemaps/google-maps-services-js#146]
I have to points one source and other one is destination. Now I want to move on this using Geolocation. Now the problem is that when source changed then both marker the source and distention blink. I want only that my source marker smoothly move on marked path and clear previous one.  Here is my code that I am writing in my Ionic 3 App

      map: any;
      directionsService = new google.maps.DirectionsService;
      directionsDisplay = new google.maps.DirectionsRenderer;
      targetLatLng;
      currentLatLng;

      constructor(private geolocation: Geolocation) 
      {
         this.targetLatLng = [50,50];
         platform.ready().then(() => {
            this.loadMap();
            this.geolocation.watchPosition()
            .filter((p) => p.coords !== undefined) //Filter Out Errors
            .subscribe(position => {
               this.currentLatLng = { lat: position.coords.latitude, lng:  position.coords.longitude };
               this.calculateAndDisplayRoute();
            });
         });
      }

      loadMap() 
      {
          this.map = new google.maps.Map(this.mapElement.nativeElement, {
            zoom: 15,
            center: this.targetLatLng,// this.currentLatLng
          });

          this.directionsDisplay.setMap(this.map);
      }

      calculateAndDisplayRoute() 
      {
          this.directionsService.route({
            origin: this.currentLatLng,
            destination: this.targetLatLng,
            travelMode: google.maps.TravelMode['DRIVING']
           }, (res, status) => {
           if (status == google.maps.DirectionsStatus.OK) {
              this.directionsDisplay.setDirections(res);
           } else {
              console.log(status);
           }
         });
      }

**Comment by stephenmcd** [comment]
Hi, your issue isn't related to this library - you might like to try stackoverflow.
