### ISSUE TITLE
Google map cannot find name google

### ISSUE THREAD

**Issue by NasirSP** [googlemaps/google-maps-services-js#147]
I'm trying to load google map using typescript  but it says 'cannot find name google'
also I'm unable to call the method this.initMap() so i'm using the simple JS method. here is my code please help me how to fix this error 'cannot find name google'

![ddd](https://user-images.githubusercontent.com/35560455/35552507-86da1cd6-05ad-11e8-9400-94bd2204e7c9.PNG)

**Comment by NasirSP** [comment]
fixed by adding `declare var google: any;` at the top of ts file, got help [from](https://stackoverflow.com/questions/42759393/cannot-find-name-google-while-using-google-maps-on-ionic2)

**Comment by stephenmcd** [comment]
Thanks for posting your fix - BTW your issue is client-side and has nothing to do with this (server-side) library, please try stackoverflow if you have any further issues like this.

**Comment by JustFly1984** [comment]
@stephenmcd I'm sorry for offtopic, but is there a clientside public repo? I'm very interested to optimize the heck from client side library, but couldn't find any. I found only bloated bug tracker, and it seems like a dead end. Is there any movement to opensource it too? I'm an author of npm `@react-google-maps/api`, and I'm really interested to make google maps faster. Currently We are rewriting it ti typescript. I would love to rewrite client side library to typescript.
