### ISSUE TITLE
Google Places API request count is not reflecting Developer console

### ISSUE THREAD

**Issue by openlayersUser** [googlemaps/google-maps-services-js#149]
Hi,

Am using Google map API Developer Key in web application. Am using nearbySearch and google.maps.places.searchBox in web application. Am  sending request from client side, in browser console, in network tab I can see Google Places API request is going and response is coming. I sent request 500 times. Still Google Places API Web Service request count is 0 in developer console.

But same web application with Licensed Key Google Places API Web Service request count is changing. Why it is not changing for Developer Key.

**Comment by amuramoto** [comment]
closing this as outdated since it is about the old developer console
