### ISSUE TITLE
Remove dependency on transient data in e2e tests

### ISSUE THREAD

**Issue by hysan** [googlemaps/google-maps-services-js#152]
**Problem Description**

I want to test some changes, but I found that most e2e tests are failing; 25/34 to be exact. I suspect that this is because real data can change over time, so the existing tests are very fragile. For example:

Test `19) places client library gets autocomplete predictions for a query` expects to find the description: `description: 'pizza near New York, NY, United States'` in the result. The data is still there but it seems that at some point, Google decided to use abbreviations for countries so the result instead contains: `description: 'pizza near New York, NY, USA'`.

Is there any way for the tests to be fixed in a way that makes them far less fragile? I'm not confident in using or trying to make edits to the codebase without a passing test suite.

**Reproduction Steps**

    git clone https://github.com/googlemaps/google-maps-services-js.git
    cd google-maps-services-js
    npm install
    # With a valid API key:
    export GOOGLE_MAPS_API_KEY=AIza-your-api-key
    npm test

**Comment by stephenmcd** [comment]
Hi, this is a known issue and not particularly a high priority. You're right that the cause is data changing over time, and for this reason we've not been running the e2e tests during integration, only the unit tests - so treat those as the tests that need to pass if you want to propose any changes.

**Comment by hysan** [comment]
@stephenmcd Ok, that makes sense. Thanks for explaining it.

**Comment by stephenmcd** [comment]
I'll leave this open as a TODO for somehow making those tests less brittle.

**Comment by grant** [comment]
I find it hard to find be able to run tests agains this repo.

I'm trying to follow these steps:
https://github.com/googlemaps/google-maps-services-js#api-keys

What's a Server key if not an API key?

---

After enabling all of those APIs, I'm still not able to pass the tests after server timeouts and `q` rejects.

**Comment by amuramoto** [comment]
@hysan I recently updated the tests with data that is passing, but it's still transient. I don't think there's any real way to protect against data changes in some of these APIs.

**Comment by amuramoto** [comment]
@grant Server key was an API key type when keys used to be issued via the developers.google.com console, rather than the Google Cloud console.
