### ISSUE TITLE
Geocode docs have incorrect bounds type

### ISSUE THREAD

**Issue by jpmoyn** [googlemaps/google-maps-services-js#155]
The provided [docs](https://googlemaps.github.io/google-maps-services-js/docs/GoogleMapsClient.html) have incorrect types for the `bounds` parameter of the `geocode()` function. The provided types in the docs are:
```
bounds: {
  southwest: LatLng,
  northeast: LatLng
}
```

but in the actual `convert.js` file of the library, we see that it is expecting the following type:

```
var validateBounds = v.object({
  south: v.number,
  west: v.number,
  north: v.number,
  east: v.number
});```

**Comment by stephenmcd** [comment]
Thanks for pointing that out - I've updated the docs now.

**Comment by jaladankisuresh** [comment]
It seems like typescript type definitions need an update as well, as they still refer to the incorrect format
bounds: {
  southwest: LatLng,
  northeast: LatLng
}

Trying to use geocoding api with the typescript type format results in the following error, which is sort of obvious considering the fact that the format is invalid
```
{"service":"user-service","message":"error msg: in property \"bounds\": missing property \"south\"in property \"bounds\": missing property \"south\"","name":"InvalidValueError","level":"error","stack":"InvalidValueError: in property \"bounds\": missing property \"south\"\n
```

``` typescript
export interface GeocodingRequest {
    address?: string;
    bounds?: LatLngBounds;
    language?: string;
    region?: string;
    components?: GeocodingComponents;
}
export interface LatLngBounds {
    northeast: LatLngLiteral;
    southwest: LatLngLiteral;
}
export interface LatLngLiteral {
    lat: number;
    lng: number;
}
```
