### ISSUE TITLE
CORS error for placesNearby

### ISSUE THREAD

**Issue by focworkshop** [googlemaps/google-maps-services-js#156]
I'm calling the api from reactjs component, resulting the following:

Failed to load https://maps.googleapis.com/maps/api/place/nearbysearch/json?language=en&location=-33.865%2C151.038&maxprice=4&minprice=1&opennow=true&radius=5000&type=restaurant&key=<my key>: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '<my hostname>' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

remarks:
- I have disabled all restriction of my key
- I have tried the geocode API which returned successfully, with the same key, same script
- From the dev console of chrome, I could see the expected results returned in the "Network" tab. Which means from browser client level it somehow passed through, but my component served through nodejs was not able to get through.  

as geocode API passed but just not the placesNearby, I believe it's probably an issue worth taking a look into

**Comment by castellanprime** [comment]
Hi, same problem. I even posted it on stackoverflow [here](https://stackoverflow.com/questions/49327622/using-google-maps-client-with-cors).

**Comment by castellanprime** [comment]
@focworkshop I think I found an workaround [here](https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe/43881141#43881141)

**Comment by stephenmcd** [comment]
See https://b.corp.google.com/issues/66923535

**Comment by castellanprime** [comment]
@stephenmcd I cant access the link you gave.

**Comment by stephenmcd** [comment]
Apologies - I just fixed the URL now.

**Comment by focworkshop** [comment]
I encountered this bug while using the google nodejs library, as an reactjs component, inside a docker container. The geocode API worked great but just not the places API. Under the same set of code, the same library version and the same environment.

So what's the rationale for not blocking all services regarding CORS in the entire library but only some?
