### ISSUE TITLE
Validation errors are not reported when using .asPromise()

### ISSUE THREAD

**Issue by stephenfarrar** [googlemaps/google-maps-services-js#16]
Instead, "undefined is not a function" at index.js line 27

**Comment by 5amfung** [comment]
I have the same problem.  `asPromise()` doesn't work as expected.

**Comment by 5amfung** [comment]
@stephenfarrar Looks like when creating the client, you have to pass in a Promise constructor.

```
var googleMapsClient = require('@google/maps').createClient({Promise: Promise, ...});
```

**Comment by stephenfarrar** [comment]
Yes, that's what I was going to say. If you don't provide a Promise constructor, the library doesn't know how to make a promise. (We let you choose your promise implementation.)

**Comment by stephenfarrar** [comment]
The problem with validation errors not throwing has been fixed (some time ago, actually).
So I'm closing this issue.
