### ISSUE TITLE
directionRenderer.setDirections failed with route returned by nodejs API 

### ISSUE THREAD

**Issue by hduchesn** [googlemaps/google-maps-services-js#161]
Hello,
My front google maps API works well. I can query a route with `directionsService.route({...})` and display the route with `directionRenderer.setDirections(results)`.

Now I want to proxy the call of `directionsService.route` to store results on my server and call gmaps only if it is necessary.
But when I try to display in front the results returned by the `nodejs directions service` I got the error `Cannot read property 'travelMode' of undefined` and the error is in the front file _direction.js line 689_ : `var f = c.request.travelMode;`

It seems the front file is looking for the front request defined when you do the call with `directionsService.route({...})`

Is it possible to use the route returned by the nodejs API with a renderer define in front/web page with js API ? If yes, how to solve this request.travelMode issue?

**Comment by stephenmcd** [comment]
The front-end and back-end services aren't intended to work together in the way you're trying to do. 

At a guess you might be able to manually patch the back-end route data with the missing attributes that the front-end API expects.

**Comment by dannyjlaurence-exp** [comment]
I added this on the front end after recieving the response and it worked. It uses the geometry package so need to load that when you load the google maps sdk.

```
  addGoogleServiceSDKFields = (serverResponse: any) => {
    serverResponse.routes = serverResponse.routes.map((response) => {
      const bounds = new google.maps.LatLngBounds(
        response.bounds.southwest,
        response.bounds.northeast,
      );
      response.bounds = bounds;
      response.overview_path =
        google.maps.geometry.encoding.decodePath(response.overview_polyline.points);

      response.legs = response.legs.map((leg) => {
        leg.start_location =
          new this.google.maps.LatLng(leg.start_location.lat, leg.start_location.lng);
        leg.end_location =
          new this.google.maps.LatLng(leg.end_location.lat, leg.end_location.lng);
        leg.steps = leg.steps.map((step) => {
          step.path = google.maps.geometry.encoding.decodePath(step.polyline.points);
          step.start_location = new google.maps.LatLng(
            step.start_location.lat,
            step.start_location.lng,
          );
          step.end_location = new google.maps.LatLng(
            step.end_location.lat,
            step.end_location.lng,
          );
          return step;
        });
        return leg;
      });

      return response;
    });

    return serverResponse;
  }
```

**Comment by hduchesn** [comment]
You can also do it in back like this : 
`
response.json.routes.forEach(route => {
    route.bounds = {
        south: route.bounds.southwest.lat,
        west: route.bounds.southwest.lng,
        north: route.bounds.northeast.lat,
        east: route.bounds.northeast.lng
    };
    route.legs.forEach(leg =>{
        leg.steps.forEach(step=>{
            step.path=require('@google/maps').util.decodePath(step.polyline.points);
        });
    });
});`
