### ISSUE TITLE
Geometry encodePath in node.js

### ISSUE THREAD

**Issue by sivabalan02** [googlemaps/google-maps-services-js#162]
I want to use the geometry encodePath() and decodePath() functions of geometry in node.js, but i didn't find any topics related this in the documentation. Also i saw alternative mapbox's polyline for encoding and decoding. But the problem is input and output format of google map and mapbox is different. Is anyway to achieve this node.js package?

Thanks

**Comment by xeroxstar** [comment]
Hello @stephenmcd, is there example how to us it? I just got confuse, do i need to copy 5fc4e42 file to somewhere or how do i install it?

**Comment by dvirben123** [comment]
any updates ?
