### ISSUE TITLE
Module not found: Error: Can't resolve 'crypto' 

### ISSUE THREAD

**Issue by muffrank** [googlemaps/google-maps-services-js#163]
I have used `@google/maps` with angular 5. 
I have got this error:

`
ERROR in ./node_modules/@google/maps/lib/internal/make-api-call.js
Module not found: Error: Can't resolve 'crypto' in '/home/umer/IdeaProjects/LwP/code/lwp/node_modules/@google/maps/lib/internal'
ERROR in ./node_modules/@google/maps/lib/internal/make-url-request.js
Module not found: Error: Can't resolve 'https' in '/home/umer/IdeaProjects/LwP/code/lwp/node_modules/@google/maps/lib/internal'
`

Version: 
`    "@google/maps": "^0.4.6"`

**Comment by stephenmcd** [comment]
Sounds like you're trying to use this outside of Node.js which is where this library is intended.

**Comment by muffrank** [comment]
Using it inside angular.io

**Comment by beaudryj** [comment]
@muffrank how did you resolve this? I am running into this while building in my docker container but not locally

**Comment by mmakhalaf** [comment]
Removing node_modules and package-lock.json fixed this for me

**Comment by beaudryj** [comment]
tried that, still biting me

**Comment by seaBubble** [comment]
Had the same issue, run npm install again and it fixed it.

**Comment by George35mk** [comment]
I have tried all the suggested answers but is not working

**Comment by beaudryj** [comment]
@George35mk I ended up trying yarn, and used `yarn install` and it worked perfectly fine

**Comment by George35mk** [comment]
I just tried yarn to install the packages but again is not working.

can you make me a favor.
try to install this packages with yarn, and if they work let me now.

```json

{
  "name": "computer-vision",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.6",
    "@angular/cdk": "^6.3.1",
    "@angular/common": "^6.0.2",
    "@angular/compiler": "^6.0.2",
    "@angular/core": "^6.0.2",
    "@angular/flex-layout": "^6.0.0-beta.16",
    "@angular/forms": "^6.0.2",
    "@angular/http": "^6.0.2",
    "@angular/material": "^6.3.1",
    "@angular/platform-browser": "^6.0.2",
    "@angular/platform-browser-dynamic": "^6.0.2",
    "@angular/router": "^6.0.2",
    "@tensorflow/tfjs": "^0.12.0",
    "core-js": "^2.5.4",
    "crypto-js": "^3.1.9-1",
    "element-resize-event": "^2.0.9",
    "google-palette": "^1.1.0",
    "hammerjs": "^2.0.8",
    "ng2-truncate": "^1.3.17",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.3",
    "@angular/cli": "~6.0.3",
    "@angular/compiler-cli": "^6.0.2",
    "@angular/language-service": "^6.0.2",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}
```


## I  get this error every time
```console
Date: 2018-07-05T21:03:44.805Z
Hash: e8ede91b9be2f0b631cf
Time: 43285ms
chunk {main} main.js, main.js.map (main) 85.4 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 227 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 74 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.95 MB [initial] [rendered]

WARNING in ./node_modules/@tensorflow/tfjs-core/dist/tf-core.esm.js
Module not found: Error: Can't resolve 'crypto' in 'C:\Users\giorg\Documents\Development\My repositories\computer-vision\node_modules\@tensorflow\tfjs-core\dist'
i ｢wdm｣: Compiled with warnings.
```

**Comment by DGmip** [comment]
same for me, nothing fixes this.

**Comment by nhhockeyplayer** [comment]
stuck too

???

**Comment by stephenmcd** [comment]
Just to re-iterate my earlier comment, this library is not intended for use in client-side browser JavaScript, which is what would cause this error to occur. It's intended for server-side Node.js applications. For client-side JavaScript, please see the [Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/tutorial).

I'll lock this for now to prevent more comments that aren't useful to anyone.
