### ISSUE TITLE
search nearby multiple types

### ISSUE THREAD

**Issue by daniele-zurico** [googlemaps/google-maps-services-js#164]
Hi there,
I just started to experiment with the google api and I was trying to retrieve all the places nearby me by type.
I works perfectly if I specify just one type: ex type: 'museum' but my question is how I can retrieve results by multiple types?
https://developers.google.com/places/supported_types
thanks in advance

**Comment by salomao-rodrigues** [comment]
Would also be really interested on this.
It looks to me that the API only allows for one type to be specified though :/
https://developers.google.com/maps/documentation/javascript/places
>type — Restricts the results to places matching the specified type. Only one type may be specified (if more than one type is provided, all types following the first entry are ignored).`

**Comment by stephenmcd** [comment]
> It looks to me that the API only allows for one type to be specified though

That's right.

**Comment by abdulmannanpk** [comment]
As per my understanding if you pass multiple types using pipe sign, it gives you result for one type only. It pick the first category from left to right and gives you result.

**Comment by sampurnamishra-kiwi** [comment]
Hi, I am integrating google near by search api and I am getting only one category type list. Is there any way to restrict search for multiple type in nearbysearch google api.
thanks in advance

**Comment by davidjtgriffiths** [comment]
did you find a solution?
I need to find the 5 closest places of any type ...

**Comment by nuovecode** [comment]
Same issue here. Why is this report closed?

**Comment by rishab089** [comment]
Same query. Open the report again, please.

**Comment by skrskr** [comment]
Did you find solution ?

**Comment by s1nbad** [comment]
same issue - want results for ANY type

**Comment by leaky** [comment]
The workaround of this limitation that I used was to separate the query logic into its own function, passing "type" as an argument. Execute multiple requests in parallel for each required "type" and then combine the results after all requests have returned successfully.
