### ISSUE TITLE
Middleware in NODE JS application

### ISSUE THREAD

**Issue by jfcmoeller** [googlemaps/google-maps-services-js#165]
Hello everybody.

I would appreciate if someone could please help me. I'm using the @google/maps package to geocode a location. It's working in the app.js file but not in other **js** files in my project. How do I set up the middleware for the package? Thanks a lot in advance.

**Comment by reks-scripts** [comment]
You could use app.locals to store your services client:

```
const app = require('express')();
const googleMapsClient = require('@google/maps').createClient({
  key: [API_KEY]
});

app.locals.googleMapsClient = googleMapsClient;
```

Then in your route handler:

```
Router.get('/', (req, res) => {
  const googleMapsClient = req.app.locals.googleMapsClient;
  // make google maps API calls and return response
});
```

Or if you want to create a services client for each request, you could write a middleware function to initialize the client and attach it to the response locals like so:

```
const googleMapsClient = require('@google/maps');

Router.use('/', (req, res, next) => {
  res.locals.googleMapsClient = .createClient({
    key: [API_KEY]
  });
  next();
});
```

Then in your route handler:

```
Router.get('/', (req, res) => {
  const googleMapsClient = res.locals.googleMapsClient;
  // make google maps API calls and return response
});
```

Just a couple ideas off the top of my head... I'm sure there's a bunch of ways to do it.

**Comment by jfcmoeller** [comment]
Thank you so much! Amazing community!! I'm new to the coding stuff. The coding-society is unbelievable. Hope I can give something back in the future. Thanks a lot.
