### ISSUE TITLE
Throw an actual object for timeout

### ISSUE THREAD

**Issue by sitegui** [googlemaps/google-maps-services-js#166]
In the event of a timeout, the [`'timeout'` string](https://github.com/googlemaps/google-maps-services-js/blob/master/lib/internal/make-api-call.js#L120) is returned:

```js
let client = require('@google/maps').createClient({key: 'my-key'})

client.placesAutoComplete({timeout: 1, input: ''}, err => {
    console.log(typeof err, err) // string timeout
})
```

That's really bad because it makes debugging and treating it much harder.

For start, there is no stack trace, so detecting where it came from is hard. On top of that, the [Node.js ecosystem](https://nodejs.org/api/errors.html#errors_error_first_callbacks) expects errors to be instances of Error and many libs misbehave when this assumption fails to be met.

I appreciate this may be a breaking change for some users and its impact should be discussed further, but I would argue this is probably something worth doing.

In any case, this behavior could be documented clearly, so that devs know what to expect in the case of timeouts and defending against it is feasible.

**Comment by DaddyWarbucks** [comment]
I have worked with this library quite a bit and always used this little wrapper. I decided to throw it in a gist to share. Its configured for promises, rather than the callbacks, but it should handle all of the cases where this library throws weird errors.
https://gist.github.com/DaddyWarbucks/2b1edc1aa6ad716f54f5dd1906d92b7f

**Comment by jpoehnelt** [comment]
Thanks for the workaround. I recommend using the Axios and TypeScript based rewrite of this library now: https://www.npmjs.com/package/@googlemaps/google-maps-services-js/v/2.0.1
