### ISSUE TITLE
Exceptions thrown in the callback are swallowed

### ISSUE THREAD

**Issue by sitegui** [googlemaps/google-maps-services-js#167]
If the callback throw any exception, it will be ignored. For example:

```js
let client = require('@google/maps').createClient({key: 'my-key'})

client.placesAutoComplete({input:  ''}, () => {
    throw new Error('Please crash') // this won't be detected anywhere
})
```

That's bad because any code following the thrown exception spot won't be executed and absolute no feedback is given. For reference, that's what Node.js core functions do:
```js
require('fs').readFile('a', () => {throw new Error('Please crash')})
```

```
        throw new Error('Please crash')
        ^

Error: Please crash
    at ReadFileContext.require.readFile [as callback] (D:\...\gui.js:2:8)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

**Comment by sitegui** [comment]
Just for reference for anybody that faces this and #166, that's how I've worked around it:
```js
client.placesAutoComplete({input:  ''}, wrapCallback((err, result) => {
    // Works like other Node.js callbacks
}))

function wrapCallback(fn) {
	return (err, ...args) => {
		process.nextTick(() => {
			if (typeof err === 'string') {
				err = new Error(err)
			}
			fn(err, ...args)
		})
	}
}
```

**Comment by DaddyWarbucks** [comment]
I have also create a gist of how this can be accomplished when using Promises.
https://gist.github.com/DaddyWarbucks/2b1edc1aa6ad716f54f5dd1906d92b7f

**Comment by jpoehnelt** [comment]
Thanks for the workaround. I recommend using the Axios and TypeScript based rewrite of this library now: https://www.npmjs.com/package/@googlemaps/google-maps-services-js/v/2.0.1
