### ISSUE TITLE
Basic example to open a map?

### ISSUE THREAD

**Issue by wizardnet972** [googlemaps/google-maps-services-js#171]
I created a new map in google map website. 

How can i open this map and mark some place by some point and save it?

I search for examples but i not find any.

**Comment by bsoyka** [comment]
This service is not for actually making or showing the maps, it contains other tools to help you do that, such as geocoding.  Take a look at [the Google Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/tutorial), and see if that’s what you’re looking for. 😄
