### ISSUE TITLE
Usage of sessionTokens with API calls.

### ISSUE THREAD

**Issue by DefJunx** [googlemaps/google-maps-services-js#173]
Good day everybody. As per [this URL](https://cloud.google.com/maps-platform/user-guide/pricing-changes/) it is suggested to add to API calls a sessionToken for auto complete service requests, but I coldn't find a way to do so using this library. 

Am I missing something out?

**Comment by stephenmcd** [comment]
It's pending in this PR which you can start developing against: https://github.com/googlemaps/google-maps-services-js/pull/170
