### ISSUE TITLE
timeout error on `place` request

### ISSUE THREAD

**Issue by LiorRabin** [googlemaps/google-maps-services-js#176]
Hello,

I'm getting `{"error":"timeout"}` on `googleMapsClient.place` requests sometimes.

What is the reason for this? How to avoid this?

Thanks

**Comment by phpedinei** [comment]
I have a some problem

**Comment by joonhocho** [comment]
me too

**Comment by amuramoto** [comment]
Can't really debug this on face, but likely cause is temporary server issue at the time of the request.
