### ISSUE TITLE
The validator for the session token parameter for the "placesAutoComplete" method is lowercase.

### ISSUE THREAD

**Issue by DefJunx** [googlemaps/google-maps-services-js#179]
I've implemented the sessionToken on my flow and noticed that if I passed it as "sessionToken" it would throw an error as it wouldn't find the value (the error is generated from apiConfig.validator method). Upon debugging I noticed that it looks for "sessiontoken" instead of "sessionToken".

Seeing as the session token is reported everywhere in camelCase, I thought I'd report this.

Forgive me for repeating sessionToken over one hundred times.

**Comment by amuramoto** [comment]
This is because the API expects `sessiontoken` without camel case for this arg:

https://developers.google.com/places/web-service/autocomplete#session_tokens
