### ISSUE TITLE
Timezone API sends wrong response.

### ISSUE THREAD

**Issue by rahulpanteon** [googlemaps/google-maps-services-js#181]
`{
"dstOffset":0,
"rawOffset":19800,
"status":"OK",
"timeZoneId":"Asia\/Calcutta",
"timeZoneName":"India Standard Time"
}`

the timeZoneId should be 'Asia/Kolkata'.

**Comment by stephenmcd** [comment]
Thanks - I'll close this here since it's unrelated to the client library.
