### ISSUE TITLE
Error trying to create client

### ISSUE THREAD

**Issue by d1820** [googlemaps/google-maps-services-js#183]
Getting this error anyone seen this before

ReferenceError: Development is not defined
    at Object.exports.inject (make-api-call.js?5631:25)
    at Object.exports.createClient (index.js?3e80:50)
    at MapService.lookupLatLong (map-service.ts?796b:13)
    at a.eval (rx-location-search-component.ts?3920:94)
    at step (519:64)
    at Object.eval [as next] (519:45)
    at eval (519:39)
    at new Promise (<anonymous>)

Failing on

var makeApiCall = require('./internal/make-api-call').inject(options);
which traces to this line failing
var clientId = options.clientId || process.env.GOOGLE_MAPS_API_CLIENT_ID;

from my typescript code

With or without Promise stuff errors on same line from npm package. Confirmed the googleMaps objct does have the createClient function and it is fired correctly.
```
const googleMaps = require('@google/maps');

 lookupLatLong(address: string): Promise<any> {
        const client = googleMaps.createClient({
            key: 'blabla', 
           Promise: Promise
        });
        return client.geocode({ address })
            .asPromise()
            .then((response: any) => {
                console.log(response.json.results);
            })
            .catch((err: any) => {
                console.log(err);
            });
    }
```

**Comment by amuramoto** [comment]
can't reproduce, but doesn't seem to be caused by the lib. Only references to this error I could find were related to webpack. Not sure if that helps at all tho.
