### ISSUE TITLE
placesNearby request requires a radius to succeed, but radius is marked optional in the documentation

### ISSUE THREAD

**Issue by alexfringes** [googlemaps/google-maps-services-js#184]
The radius parameter for placesNearby is marked as optional in the documentation ( https://googlemaps.github.io/google-maps-services-js/docs/GoogleMapsClient.html ) but requests to placesNearby will fail if no radius is supplied.

**Comment by stephenmcd** [comment]
It's optional since it shouldn't be specified when `rankby` is set to `distance`, otherwise it's required, as per the docs here: https://developers.google.com/places/web-service/search#PlaceSearchRequests
