### ISSUE TITLE
sessiontoken key in "placesAutoComplete" option doesn't accept object

### ISSUE THREAD

**Issue by DefJunx** [googlemaps/google-maps-services-js#188]
I'm generating my session token using the following method on frontend:

`google.maps.places.AutocompleteSessionToken();`

And then send it to my node backend to perform the "placesAutoComplete" call. The problem with this is that the "sessiontoken" key accepts only strings, and the session token seems to be store in a different object key every time! Am I doing something wrong here? Should it accept objects other than strings?

**Comment by stephenmcd** [comment]
The client and server-side APIs aren't intended to work together. If you're not using the client-side autocomplete, don't use a client-side session token. You can create a server-side session token via `require('@google/maps').util.placesAutoCompleteSessionToken()` which will give you a string that the server-side API expects.

With that out of the way, if you were truly determined to do what you're trying to do, you could access the string value of the client-side object with something like: `var x = new google.maps.places.AutocompleteSessionToken(); x[Object.keys(x)[0]]` which would give you something you could pass to the server - but I would definitely not rely on that behaviour, nor can I recommend that it will achieve the desired affect for billing purposes. 

I would strongly suggest keeping the client-side and server-side logic separate.

**Comment by DefJunx** [comment]
Thank you @stephenmcd :)
