### ISSUE TITLE
Large Controls on Google Maps

### ISSUE THREAD

**Issue by phao5814** [googlemaps/google-maps-services-js#193]
I'm seeing exceptionally large map controls on my own website as well as on the Google Maps [documentation](https://developers.google.com/maps/documentation/javascript/examples/control-positioning). I have tried various browsers and devices (mobile and desktop) and I'm seeing the same issue.

<img width="738" alt="screen shot 2018-08-14 at 12 17 55 pm" src="https://user-images.githubusercontent.com/23574714/44068169-189b8f44-9fbc-11e8-80ef-3f620721b8df.png">

![img_2705](https://user-images.githubusercontent.com/23574714/44068305-a8170cca-9fbc-11e8-862a-7b34804dab48.jpg)

Is this a known bug or is this an isolated incident?

**Comment by stephenmcd** [comment]
Hi, this project is for the Node.js library which has nothing to do with your issue. You probably want the issue tracker for the Maps JavaScript API which is here: https://issuetracker.google.com/components/188853#basic

**Comment by stephenfarrar** [comment]
This issue is explained here
https://issuetracker.google.com/112520084
