### ISSUE TITLE
Make OVER_QUERY_LIMIT and RESOURCE_EXHAUSTED optionally retryable

### ISSUE THREAD

**Issue by jaredkwright** [googlemaps/google-maps-services-js#196]
Currently when the service returns OVER_QUERY_LIMIT or RESOURCE_EXHAUSTED, the library assumes the request is retryable. This can result in hard-to-debug problems, especially when dealing with the Places SDK (see issue #176, #55 and #69 for example). If the maintainers agree, I can submit a pull request setting those options when you instantiate the client, so that you can easily tell when you are getting one of those errors.

Additionally it might be helpful to have a "debug mode" toggle which logs retries and the corresponding reason, so that developers can see real time what might be causing the timeout.

**Comment by rewieer** [comment]
Submitted a PR. This should work if the PR gets merged :
```
this.client.geocode({ address: city }, (err, data) => {
  if (err) {
    reject(null);
  }

  accept(null);
}, {
  options: {
    canRetry: (response) => {
      return false; // Here's the magic
    }
  }
});
```
