### ISSUE TITLE
How to enable 3D Globe Mode on Google Maps JavaScript API?

### ISSUE THREAD

**Issue by mahnunchik** [googlemaps/google-maps-services-js#203]
Copy from not my question: https://stackoverflow.com/questions/51763299/how-to-enable-3d-globe-mode-on-google-maps-javascript-api

**Comment by stephenmcd** [comment]
Stackoverflow was the right place for your question, it's not related to this library.

**Comment by mahnunchik** [comment]
@stephenmcd Could you please answer this question on stackoverflow?
