### ISSUE TITLE
Use of the node standard library "util" causes this to not work with Expo/React Native

### ISSUE THREAD

**Issue by MaffooBristol** [googlemaps/google-maps-services-js#204]
I get this error:

> The package at "node_modules/@google/maps/lib/index.js" attempted to import the Node standard library module "util". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq.html#can-i-use-nodejs-packages-with-expo

This is due to the use of util's deprecate function. It appears to be the only place where this happens, but it seems rather redundant when all it's doing is informing the developer that a certain function is deprecated, and to completely remove the ability to use `@google/maps` in a React Native or an Expo environment, just purely for this one function, seems a bit odd.

I feel it could be replaced with a custom function. Thoughts on this?

Thanks, Matt

**Comment by MaffooBristol** [comment]
In fact, perhaps using https://www.npmjs.com/package/util would do the job?

**Comment by MaffooBristol** [comment]
Just noticed the "this library is designed for server-side Node.js applications" caveat, however I'm not sure whether RN would be classed as client-side or server-side?

**Comment by stephenmcd** [comment]
> React Native does not include the Node standard library

This would preclude it being supported
