### ISSUE TITLE
Client does not write about requests quota limit

### ISSUE THREAD

**Issue by infowebstrong** [googlemaps/google-maps-services-js#205]
I create new account in Google Cloud Console and create api key, i have quota limit 1 request, in free plan.  
When i use quota limit, next request die with timeout, and first time i don`t understand why query die. 
Code i take from examples in readme.md

**Comment by abhaynpai** [comment]
I had to `curl` the URL in order to understand what went wrong. On the API dashboard, I saw a lot of 403s. Ideally the callback should do display the error message.

**Comment by stephenmcd** [comment]
Thanks - this looks like a duplicate of #196
