### ISSUE TITLE
Fatal error when using with react native framework

### ISSUE THREAD

**Issue by ttkien** [googlemaps/google-maps-services-js#206]
I have 2 cases:
- The first case, I installed @google/maps within normal Nodejs package (no React native), @google/maps work well
- the second case, I installed @google/mapps within react native project. @google/maps occurred the following error:
`  bundling failed: Error: Unable to resolve modu
le `util` from `/Volumes/Data/labs/WeatherAppByReactNativeAndCleanArchitecture/weather/node_modules/@google/maps/lib/index.js`: Module `util` does not exist in the Haste module map`

here is my package.json
```

  {
  "compilerOptions": {
    /* Basic Options */
    "target": "es6",                         
    "module": "commonjs",                    
    "lib": [
      "es6", "dom"
    ],                           
    "jsx": "react",                          
    "outDir": "./dist/",                       
    "noImplicitAny": false,                
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/@google",
      "./node_modules/@babel"
      ],                     
    "types": [
    ],                           
    "esModuleInterop": true,                  

    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "skipLibCheck": true,
    "declaration": true,
    "noUnusedLocals": false
  },
   "exclude": [
    "node_modules"
  ]
}
```

and tsconfig.json
```

{
  "compilerOptions": {
    /* Basic Options */
    "target": "es6",                         
    "module": "commonjs",                    
    "lib": [
      "es6", "dom"
    ],                           
    "jsx": "react",                          
    "outDir": "./dist/",                       
   
    "noImplicitAny": false,                
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/@google",
      "./node_modules/@babel"
      ],                     
    "types": [

    ],                           
    "esModuleInterop": true,                  

    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "skipLibCheck": true,
    "declaration": true,
    "noUnusedLocals": false
  },
   "exclude": [
    "node_modules"
  ]
}

```

**Comment by stephenmcd** [comment]
This library is designed for server-side Node.js applications. Attempting to use it client-side, in either the browser or any other environment like React Native, may in some cases work, but mostly will not. Please refrain from reporting issues with these environments when attempting to use them, since **server-side Node.js applications is the only supported environment for this library**. For other environments, try the [Maps JavaScript API], which contains a comparable feauture set, and is explicitly intended for use with client-side JavaScript.

**Comment by tim-rohrer** [comment]
Judging from the number of times this comes up, it is clear people are getting confused by this. I think this is the first answer I've come across which acknowledges that `React` is considered client side.
