### ISSUE TITLE
How do I get a session token for places autocomplete requests?

### ISSUE THREAD

**Issue by andrwmillr** [googlemaps/google-maps-services-js#207]
I’m not sure how to generate a session token for making a places autocomplete request. I'm trying to run code that looks like this:

```
googleMapsClient.placesAutoComplete(
  { input: ‘pizza' },
  (err, response) => console.log(response)
);
```

I’m getting an error that my query is missing a ‘sessiontoken’ property, which is needed per [these docs](https://googlemaps.github.io/google-maps-services-js/docs/GoogleMapsClient.html). When ```placesAutocomplete``` is tested in the spec, the query doesn't include a ‘sessiontoken’ property. I’d like to know how to generate a session token, or if I’m doing something else wrong. Thanks.

**Comment by jferrettiboke** [comment]
This is happening to me too! I have the same issue. I am getting `InvalidValueError: missing property "sessiontoken"` and I am not able to send requests.

I have been using this (see code below), but now it doesn't work.

```js
const googleMapsClient = require("@google/maps").createClient({
  key: process.env.GOOGLE_MAPS_API_KEY
});
```

Any help is welcome. Thanks.

**Comment by jferrettiboke** [comment]
@andrwmillr I just figured it out!

I had:

```js
googleMapsClient.placesAutoComplete({ input })
```

You just need to add `sessiontoken` as a parameter.

```js
googleMapsClient
    .placesAutoComplete({
      input,
      sessiontoken: process.env.GOOGLE_MAPS_API_KEY
    })
```

This approach doesn't make much sense to me, because we are already passing the key with `createClient` function. Maybe, someone can explain what's the reason of this in more detail in order to have a better understanding about it.

**Comment by jferrettiboke** [comment]
@andrwmillr [Here](https://developers.google.com/places/web-service/autocomplete#session_tokens), you have more info about sessions. So, I think the session token can be any string and I don't think the API key is the best. Now, it makes sense to me.

**Comment by stephenmcd** [comment]
It's just a string that should be unique per user - there's the util `require('@google/maps').util.placesAutoCompleteSessionToken()` you can use for this which I've now documented in 66b8b7b46213d749defdfe653a5931bdfd4dcb41

**Comment by TheAmenRa** [comment]
> It's just a string that should be unique per user - there's the util `require('@google/maps').util.placesAutoCompleteSessionToken()` you can use for this which I've now documented in [66b8b7b](https://github.com/googlemaps/google-maps-services-js/commit/66b8b7b46213d749defdfe653a5931bdfd4dcb41)

Hello, I get an error using what you suggest:

```shell
let sessiontoken = require('@google/maps').util.placesAutoCompleteSessionToken();
                                               ^

TypeError: Cannot read property 'placesAutoCompleteSessionToken' of undefined
```

What am I doing wrong?

**Comment by Mimameid** [comment]
> It's just a string that should be unique per user - there's the util `require('@google/maps').util.placesAutoCompleteSessionToken()` you can use for this which I've now documented in [66b8b7b](https://github.com/googlemaps/google-maps-services-js/commit/66b8b7b46213d749defdfe653a5931bdfd4dcb41)

Shouldn't the session token be unique per request session rather than user?

**Comment by wangela** [comment]
@Mimameid Good reference to the docs! It's unique to both the user and the session. The[ documentation Stephen linked](https://github.com/googlemaps/google-maps-services-js/commit/66b8b7b46213d749defdfe653a5931bdfd4dcb41) to makes it clear that it's "a single user's session".

**Comment by Mimameid** [comment]
@wangela 

To make it clear for myself:

Why is it important to mention "single user" here. How can a session not be associated with a "single user"?

Maybe a little offtopic:

How do we know if the session token has an effect (if it was implemented properly)?
