### ISSUE TITLE
How can i get the DirectionsRoute response

### ISSUE THREAD

**Issue by jackdh** [googlemaps/google-maps-services-js#209]
Hi,

I'm trying to get ahold of the `overview_path ` of the DirectionsRoute seen here:

https://developers.google.com/maps/documentation/javascript/directions#Routes

I can't seem to find this response object within this project. Is it not possible or am I missing something?

Thank you

**Comment by stephenmcd** [comment]
You're looking at the documentation for the client-side JavaScript API, which is different from the server-side API that this library is for. You can find the correct documentation here: https://developers.google.com/maps/documentation/directions/intro

**Comment by Sarav-S** [comment]
@jackdh Google maps doesn't provide the overview_path on the response. Instead of that, you can retrieve the list of coordinates by decoding the overview_polyline.points polyline. You can use this package https://www.npmjs.com/package/decode-google-map-polyline
