### ISSUE TITLE
Placesnearby seach with map bounds instead of location

### ISSUE THREAD

**Issue by frizurd** [googlemaps/google-maps-services-js#210]
Hey guys, 
I'm trying to do placesNearby search with specified map bounds instead of a location.
This should be possible, I've tried it on the client side and it worked.

This gives me the following error:
```
  message: 'one of "location", "pagetoken" is required',
  name: 'InvalidValueError'
```

Here's my request:

```
    const request = {
      language: 'en',
      bounds    : req.body.bounds,
      keyword   : 'cafe for work'
    };
    placesService.placesNearby(request, function(err, response) {
      if (!err) {
        resolve(result);
      } else {
        reject(err);
      }
    });
```

Did anyone have any similar issues?
Thanks in advance.

**Comment by stephenmcd** [comment]
> This should be possible, I've tried it on the client side and it worked.

The client-side and server-side APIs are different, with the latter not having a bounds param, so no this won't work. You probably want to use the `radius` param, see the docs for more info: https://developers.google.com/places/web-service/search#PlaceSearchRequests
