### ISSUE TITLE
Response lat lng from geocoder has change from last time at the same place name

### ISSUE THREAD

**Issue by fluke34261** [googlemaps/google-maps-services-js#211]
Response lat long from geocoder has change from last time at the same place name

My Customer ask me why him type name point place (same name) has change lat long from last time him got

Such as 
Place A [2 month ago] =  10.8989, 98.657567
Place A now = 10.8981, 98.65744

do you have any notice document or notice change log. i need it to send to my customer

sorry about my english
thank you

**Comment by amuramoto** [comment]
The geocodes available from Maps Platform are regularly updated from many sources, so they may vary slightly over time if more accurate data is available.
