### ISSUE TITLE
complex polyline example doesn't render anything?

### ISSUE THREAD

**Issue by kpennell** [googlemaps/google-maps-services-js#215]
https://developers.google.com/maps/documentation/javascript/examples/polyline-complex 
![image](https://user-images.githubusercontent.com/1060385/50566403-044f2400-0cff-11e9-9411-edff532392fd.png)

**Comment by stephenmcd** [comment]
Hi, that's unrelated to this client library. You might like to post your issue to stackoverflow.com.

**Comment by kpennell** [comment]
@stephenmcd it's your docs buddy

**Comment by kpennell** [comment]
This isn't for sO

**Comment by stephenmcd** [comment]
It looks like that demo is interactive - did you click on the map more than once?
