### ISSUE TITLE
Plus Code is not returned

### ISSUE THREAD

**Issue by irceric** [googlemaps/google-maps-services-js#219]
When I try to get place details, I add 'plus_code' in fields option and it complains it's a invalid field.

how can I get plus_code from place details api?

**Comment by amuramoto** [comment]
Looks like this was not added to the list of fields. Fixed in https://github.com/googlemaps/google-maps-services-js/commit/40a93da6690de7de8d0a517fda0dc2c1029c3b5e. Please give it a try now.
