### ISSUE TITLE
Google Places Seach pagination

### ISSUE THREAD

**Issue by marcosgouvea** [googlemaps/google-maps-services-js#220]
Hey guys i'm pretty new on this, i read the documentation but i didnt understand it very well,

 i made a query like this
```
googleMapsClient.places({
    query: 'oficina',
    language: 'pt-BR',
    location: [-23.549862, -46.7913917],
    radius: 50000,
    opennow: false,
    type: 'car_repair'
}).then(response =>{
    console.log(response.json.results);
}).catch(error =>{
    console.log('error =>', error)
})
```
it only returns 20 car_repair places near my location, i see that it return **next_page_token** but idk how it works, i would like to retrieve all the places near the 50.000 radius ( i see in the google documentation that this is the limit)

i would like to make a loop and it return all the places till it ends or no more next_page_token.
is it possible ?

**Comment by amuramoto** [comment]
Hi! Please ask how-to questions on the [google-places-api](https://stackoverflow.com/questions/tagged/google-places-api) StackOverflow tag

**Comment by piyushpandey-kiwi** [comment]
Here is the final solution:

getGoogleId = (reqPayload) => {
        return googleMapsClient
            .places({
                query: reqPayload.category.replace(/,(?=\s*$)/, ''),
                language: 'en',
                location: [reqPayload.location.lat, reqPayload.location.long],
                radius: reqPayload.radius,
                pagetoken: reqPayload.next_page_token
            })
            .asPromise();

    }

getPlaceId = (reqPayload, placeIdsArray) => {
        return new Promise(async (resolve, reject) => {
            this.googlePromiseResolve(reqPayload, placeIdsArray, resolve);
        });
    }

   googlePromiseResolve = (reqPayload, placeIdsArray, resolve) => {
        this.getGoogleId(reqPayload).then(async response => {
            const placeIdsConcatArray = placeIdsArray.concat(response.json.results.map(p => p.place_id));
            console.info('requestUrl', response.requestUrl);
            if (response.json.next_page_token) {
                reqPayload.next_page_token = response.json.next_page_token;
                setTimeout(() => {
                    this.pmResolve(reqPayload, placeIdsConcatArray, resolve);
                }, 5000);
            } else {
                resolve(placeIdsConcatArray);
            }
        });
    }
