### ISSUE TITLE
how can i add markers in google maps using JSP

### ISSUE THREAD

**Issue by eutone** [googlemaps/google-maps-services-js#227]
<html>
<body>

<h1>My First Google Map</h1>

<div id="googleMap" style="width:100%;height:400px;"></div>

<script>
function myMap() {

var mapProp= {
  center:new google.maps.LatLng(51.508742,-0.120850),
  zoom:5,
};
var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
}

</script>

<script src="https://maps.googleapis.com/maps/api/js?key=MY_KEY&callback=myMap"></script>

</body>
</html>

**Comment by amuramoto** [comment]
Please ask how-to questions on StackOverflow using the google-maps tag:

https://stackoverflow.com/questions/tagged/google-maps
