### ISSUE TITLE
getting data from API first time only

### ISSUE THREAD

**Issue by raitalharehman** [googlemaps/google-maps-services-js#228]
getting data from API first time only  after that every time got timeout
Check this out.
https://stackoverflow.com/questions/55016627/the-problem-with-geolocation-once-gave-the-result-all-the-others-timeout

**Comment by egorFiNE** [comment]
Same here.

**Comment by egorFiNE** [comment]
Here's the answer: https://developers.google.com/maps/faq#limit_1

**Comment by raitalharehman** [comment]
@egorFiNE thanks
