### ISSUE TITLE
Could not load "elevation"

### ISSUE THREAD

**Issue by stripathix** [googlemaps/google-maps-services-js#229]
Getting error

```
Error: Could not load "elevation".
  at ? (/maps/api/js:72:406)
```

<img width="694" alt="Screenshot 2019-03-22 at 10 40 40 AM" src="https://user-images.githubusercontent.com/8480351/54801891-f4f0ce80-4c8e-11e9-910c-a87a6ff870a4.png">

I am loading google maps API async using below URL
https://maps.googleapis.com/maps/api/js?key=AIzaSyA6abx********************0smXOw9k9o

**Comment by amuramoto** [comment]
Can you post a link to the code where this is being thrown?

**Comment by amuramoto** [comment]
closing due to lack of repsonse
