### ISSUE TITLE
Multiple countries for placesAutoComplete not working

### ISSUE THREAD

**Issue by ronakvora** [googlemaps/google-maps-services-js#234]
Hi, 

I know there have been many issues raised about this.

I know there was a PR located here: https://github.com/googlemaps/google-maps-services-js/pull/192.

But, my query: 

```
googleMapsClient.placesAutoComplete({input: '1600 Amphitheatre Parkway', types: ['address'], components: {'country': ['us', 'ca']}, sessiontoken: sessionToken}).asPromise();
```

is resulting in a URL that's incorrect: 

{ status: 200,
  headers:
   { 'content-type': 'application/json; charset=UTF-8',
     date: 'Fri, 03 May 2019 14:20:37 GMT',
     expires: 'Fri, 03 May 2019 14:20:37 GMT',
     'cache-control': 'private, max-age=300',
     server: 'scaffolding on HTTPServer2',
     'x-xss-protection': '0',
     'x-frame-options': 'SAMEORIGIN',
     'server-timing': 'gfet4t7; dur=13',
     'alt-svc': 'quic=":443"; ma=2592000; v="46,44,43,39"',
     'accept-ranges': 'none',
     vary: 'Accept-Language,Accept-Encoding',
     connection: 'close' },
  json: { predictions: [], status: 'INVALID_REQUEST' },
  requestUrl:
   'https://maps.googleapis.com/maps/api/place/autocomplete/json?components=country%3Aus%2Cca&input=1600%20Amphitheatre%20Parkway&sessiontoken=6a766354-e639-48e6-a255-d30d274a7477&types=address&key=[REDACTED]',
  query:
   { components: 'country:us,ca',
     input: '1600 Amphitheatre Parkway',
     sessiontoken: '6a766354-e639-48e6-a255-d30d274a7477',
     types: [ 'address' ],
     key: REDACTED} }

The requestUrl parameter putsa a ',' between the us and canada instead of a '|'. I'm not sure if I'm missing something or if there's a bug somewhere.

The workaround for now is: 

```
const result = await googleMapsClient.placesAutoComplete({input: '1600 Amphitheatre Parkway', types: ['address'], components: {'country': 'us|country:ca'}, sessiontoken: sessionToken}).asPromise();
```

**Comment by amuramoto** [comment]
Looks like this is due to a bug in pipedKeyValues:

https://github.com/googlemaps/google-maps-services-js/blob/master/lib/internal/convert.js#L24

Will take some time to come up with a fix for this since we'll have to be careful about causing breakage, but we can definitely do something about it

**Comment by wangela** [comment]
@ronakvora Please make sure to make a new API key and delete the one you pasted in your original comment, since comment history is visible in GitHub.

**Comment by ronakvora** [comment]
I did. Thank you for looking out! :)

**Comment by jpoehnelt** [comment]
For others finding this, please pass the countries in already concatenated or use the refactor of this library https://www.npmjs.com/package/@googlemaps/google-maps-services-js/v/2.0.1.
