### ISSUE TITLE
Request Timeout on Production server

### ISSUE THREAD

**Issue by SatyaFariz** [googlemaps/google-maps-services-js#235]
I'm using placesAutoComplete, place, and nearbyPlaces API. It's working on my development server but always request timeout on production server without any error message or response. It's very hard to debug.

**Comment by amuramoto** [comment]
What are the actual calls that are timing out?

**Comment by sanusi87** [comment]
Same here, even a simple script like this give me timeout:

```javascript
const googleMapsClient = require('@google/maps').createClient({
	key: API_KEY
});

googleMapsClient.geocode({
	address: '56000, Kuala Lumpur'
}, function(err, response) {
	if( !err ){
		console.log(response.json.results);
	}else{
		console.log(err);
	}
});
```

**Comment by amuramoto** [comment]
Can't reproduce
