### ISSUE TITLE
Order Field not Present in Places API or elsewhere?

### ISSUE THREAD

**Issue by avcohen** [googlemaps/google-maps-services-js#239]
This might be less of an issue per-se but I don't seem to find any documentation for some information that one would assume could be made available via the Places API.

Specifically, I'm looking for the info noted on [this listing](https://www.google.com/search?hl=en&source=hp&ei=Y-DdXPeuG66d5wL1-YmQAw&q=inday&oq=inday&gs_l=psy-ab.12..0l10.2369.2795..3043...0.0..0.247.504.5j0j1....2..0....1..gws-wiz.....0..0i131j0i10.U2uL_mxA5TI&npsic=0&rflfq=1&rlha=0&rllag=40750448,-73980941,1028&tbm=lcl&rldimm=9287243097353770239&phdesc=Ga5fhcdKnLg&ved=2ahUKEwi5geKKiaHiAhWF2FkKHVVxBycQvS4wAHoECAgQCQ&rldoc=1&tbs=lrf:!3sIAE,lf:1,lf_ui:9&rlst=f#rldoc=1) under `Order`.

It seems Google often collects which delivery services any given location uses. I'd be super curious to find this data via an API.

Thanks!

**Comment by amuramoto** [comment]
This info isn't currently available via the API. Right now there's no plan to add it afaik.

**Comment by avcohen** [comment]
Thanks, @amuramoto. Will do!
