### ISSUE TITLE
.places(query, callback) -language option only returning english

### ISSUE THREAD

**Issue by randyhoulahan** [googlemaps/google-maps-services-js#240]
`{
        query:'États Unis,
        language:'fr',
        type: 'country'
    }`

Returns english

**Comment by amuramoto** [comment]
Might be because 'country' is not a supporter place type for queries. It's returned in results but can't be queried on. 

Can you try with a supported type and see if you are seeing the same issue?

https://developers.google.com/places/web-service/supported_types

**Comment by andersondsl** [comment]
@randyhoulahan your exemple query is missing a quote, closing the query parameter

**Comment by amuramoto** [comment]
Thanks @andersondsl !
