### ISSUE TITLE
Support `Street View Static API`

### ISSUE THREAD

**Issue by chrux** [googlemaps/google-maps-services-js#244]
Is there any plan to add support to `Street View Static API`

**Comment by amuramoto** [comment]
Not at this time. This lib is meant for node.js calls, so we don't include any front end features with it.

**Comment by chrux** [comment]
What's a front end feature? https://developers.google.com/maps/documentation/streetview/intro, This just allow users to get a image of a location

**Comment by amuramoto** [comment]
The API is intended for showing street view images on the web and in mobile apps.
