### ISSUE TITLE
.asPromise().then() being ignored

### ISSUE THREAD

**Issue by chrissyast** [googlemaps/google-maps-services-js#246]
I am trying to use the asPromise() in https://googlemaps.github.io/google-maps-services-js/docs/RequestHandle.html  function so that my code will wait for the request to complete. Even with asPromise it's still hitting the outer code first. Also is returning 'err' even though 200 status.

```    
    googleMapsClient.placesNearby(request).asPromise()
    .then(function(err,response){
        
        if(!err){
          console.log('inside function')
          placesOfInterest.push(response.json.results)      
        }
        else{
          console.log("it's fucked")
          console.log(err)
        } 
             
    }); 
    console.log('outside function')
    return(placesOfInterest)
```

Expected output:
inside function
outside function

Actual output:
outside function
it's fucked
{ status:200
... results: [some results]
... status: 'OK'
...}

**Comment by chrissyast** [comment]
Well, I've partially answered my own question by changing the `function(err,response)` to just `function(response)` and commenting out the 'err' parts, and then putting the outside function into `finally(function(){my code}`

But how does the code handle errors now??

**Comment by amuramoto** [comment]
Are you including the `Promise` prop in your createClient?

```
const googleMapsClient = require('@google/maps').createClient({
  key: 'your API key here',
  Promise: Promise
});
```

**Comment by chrissyast** [comment]
@amuramoto  Yes, I included the promise prop. In the end, [this](https://stackoverflow.com/a/56434597/8940624) was the best solution - returning the promise from the function instead of carrying on with the code after doing the search, although it still doesn't seem to have any error handling.

**Comment by skalfyfan** [comment]
Based on your first snippet and what you've list as the `Actual Output` is the correct and expected output. You have chosen to use `asPromise()` thereby making your `googleMapsClient` method calls asynchronous. 

To add error handling add a `catch` clause at the end of your promise chain.

The solution you linked to in your reply on Jun 12 appears to have gotten you and the right track! 👍 

This can probably be closed?

**Comment by amuramoto** [comment]
Thanks for responding on this @skalfyfan !
