### ISSUE TITLE
Reverse Geocoding

### ISSUE THREAD

**Issue by samy-blake** [googlemaps/google-maps-services-js#248]
Hey,
i miss the function of reverse geocoding.
In this example (https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse) they use the parameter 'location' but i dont see it in the options for 'geocode' (https://github.com/googlemaps/google-maps-services-js/blob/master/lib/apis/geocode.js#L42).

can you add this funtion to this lib?

Yours sincerely

**Comment by amuramoto** [comment]
This is already included. You call `reverseGeocode` and pass an array in the `latlng` prop.

For an example, see [this test](https://github.com/googlemaps/google-maps-services-js/blob/master/spec/e2e/geocode-spec.js#L120)

**Comment by NickSutton** [comment]
Error404 on the link, was looking for this example exactly :-(

**Comment by amuramoto** [comment]
@NickSutton Here's an updated link: https://github.com/googlemaps/google-maps-services-js/blob/master/e2e/geocode/reversegeocode.test.ts
