### ISSUE TITLE
 maps options on goolge maps geocode

### ISSUE THREAD

**Issue by coy102** [googlemaps/google-maps-services-js#250]
Hello,

can i use maps options on geocode, something like this

```
const mapsOptions = {
    componentRestrictions: { country: 'id' },
    types: ['(cities)']
  };
```

Thanks

**Comment by amuramoto** [comment]
For supported options params, see the code comment here:

https://github.com/googlemaps/google-maps-services-js/blob/master/lib/apis/geocode.js#L24
