### ISSUE TITLE
It only returns 3 pages with pagetoken

### ISSUE THREAD

**Issue by malihassan20** [googlemaps/google-maps-services-js#251]
I can only get 3 pages results even though we have more than 3 pages. Does anybody have the same issue which I am facing?

**Comment by malihassan20** [comment]
I am using googleMapsClient.places for this. I was able to successfully get the three pages result using next_page_token from the result but since after three pages it is null so how I can get the other remaining pages data?

I know that google has written this in their documentation: 

_"next_page_token contains a token that can be used to return up to 20 additional results. A next_page_token will not be returned if there are no additional results to display. The maximum number of results that can be returned is 60. There is a short delay between when a next_page_token is issued, and when it will become valid."_

But does anybody know a way by which I can get the remaining results data?

**Comment by amuramoto** [comment]
20 results are returned per page, and a max of 60 results are returned in total, so only 3 pages are expected.
