### ISSUE TITLE
Remove map UI from tabbing order

### ISSUE THREAD

**Issue by bhaskar-nair2** [googlemaps/google-maps-services-js#253]
Hello, I am using a the map API in a form to display selected location. The issue is that even after disabling the UI controls, the map still has Google's Banner and the Report an Issue button which take focus on pressing tab. I don't mind having the buttons there, but it is very irritating for my users to press tab multiple times to skip over those controls. 

Adding `tabIndex='-1'` did not work. The base UI controls have been disabled.

**Comment by amuramoto** [comment]
If I'm understanding correctly this is a feature request for map loading in the JS API rather than this library. Please open a bug in our issue tracker. Thanks!

https://issuetracker.google.com/savedsearches/558438
