### ISSUE TITLE
Google Places Photos API does not pass maxheight/maxwidth

### ISSUE THREAD

**Issue by sulaysumaria** [googlemaps/google-maps-services-js#254]
When using `placesPhoto` api to get photos, any one of `maxheight` or `maxwidth` is required. But when passed to function, it does not attach it to request url which results in 400 Bad Request.

**Comment by amuramoto** [comment]
Our tests cover this and are passing. 
https://github.com/googlemaps/google-maps-services-js/blob/master/spec/e2e/places-spec.js#L145

Can you post a gist to the request you're trying?

**Comment by sulaysumaria** [comment]
My bad. I was passing a variable that was undefined.

Maybe error can be more descriptive?

**Comment by amuramoto** [comment]
Sounds good - can't guarantee when we can improve error messages, but happy to look at a PR if you want to get involved =)
