### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version "8". Got "10.16.2"

### ISSUE THREAD

**Issue by theochampion** [googlemaps/google-maps-services-js#260]
Hi there,

I'm trying to install this module on  node `10.16.2` using `yarn add @google/maps` and I get this error:

`The engine "node" is incompatible with this module. Expected version "8". Got "10.16.2"`

Is there a way to make it work on node 10 or do I have to downgrade to node 8?

**Comment by amuramoto** [comment]
It looks like this is an issue with installing npm dependencies with yard. Use `yarn --ignore-engines`
