### ISSUE TITLE
Distance Matrix: Origins and destinations as LatLngLiteral don't build the right URL

### ISSUE THREAD

**Issue by OzoTek** [googlemaps/google-maps-services-js#261]
Hi,

When trying your client with the Distance Matrix API, I noticed that using the `origins` and `destinations` query params with the `LatLngLiteral` does not work properly because of the way the query params are built up in the request URL.

Example usage:

```js
client.distanceMatrix({
  origins: [{ lat: origin_lat, lon: origin_lon }],
  destinations: [{ lat: destination_lat, lon: destination_lon }]
});
```

Will create a URL like:

https://maps.googleapis.com/maps/api/distancematrix/json?destinations=%5Bobject%20Object%5D&origins=%5Bobject%20Object%5D

I successfully made it work with another available type though, so I believe this is only the case with `LatLngLiteral` and `LatLngLiteralVerbose`.

The culprit code seems to be there: https://github.com/googlemaps/google-maps-services-js/blob/55e43cf99f4514eff51f37bb5f97cd85d2c7a2c4/lib/index.js#L64-L68

Where `obj[key]` is a `{lat, lon}` object, that gets stringified as `"[object Object]"`.

Let me know if you need more information.
Thanks!

Alexandre

**Comment by amuramoto** [comment]
The lib expects LatLng to be in the format `{lat:someLat, lng:someLng}`. In your example you're using `lon` for the second prop. Can you check to see if that fixes the issue?

https://googlemaps.github.io/google-maps-services-js/docs/LatLng.html

**Comment by OzoTek** [comment]
Indeed, it works thanks! Sorry about the noise!
