### ISSUE TITLE
Documentation Mistake: placesNearby specified 'radius' parameter as optional, which it's supposed to be 'required'

### ISSUE THREAD

**Issue by nusantara-cloud** [googlemaps/google-maps-services-js#262]
https://googlemaps.github.io/google-maps-services-js/docs/GoogleMapsClient.html

Without the 'radius' specified, the call would return an error with INVALID_REQUEST status.

**Comment by amuramoto** [comment]
This is kinda true and kinda not. `radius` is required, unless using rankby=distance. I've updated the description in https://github.com/googlemaps/google-maps-services-js/commit/463b49e1131e35292f037fca11089243b5e60332

Thanks for reporting!
