### ISSUE TITLE
Invalid geocode request sends valid response

### ISSUE THREAD

**Issue by whithang** [googlemaps/google-maps-services-js#267]
From Node:

I'm sending this request to geocode: {address: ,  _adfaaasd_,  US}
I'm expecting a null response but I'm getting a valid address in MD:
`[{"address_components":[{"long_name":"Boyds","short_name":"Boyds","types":["locality","political"]},{"long_name":"Maryland","short_name":"MD","types":["administrative_area_level_1","political"]},{"long_name":"United States","short_name":"US","types":["country","political"]},{"long_name":"20841","short_name":"20841","types":["postal_code"]}],"formatted_address":"22705 Clarksburg Road, Suite 116 Clarksburg Outlet, Boyds, MD 20841, United States","geometry":{"location":{"lat":39.22859649999999,"lng":-77.2864812},"location_type":"GEOMETRIC_CENTER","viewport":{"northeast":{"lat":39.22994548029149,"lng":-77.2851322197085},"southwest":{"lat":39.22724751970849,"lng":-77.28783018029151}}},"partial_match":true,"place_id":"ChIJrystCGIptokRQ4sdF5sFbZM","plus_code":{"compound_code":"6PH7+CC Clarksburg, Germantown, MD, United States","global_code":"87F46PH7+CC"},"types":["establishment","point_of_interest","store"]}]`

**Comment by jpoehnelt** [comment]
Hi @whithang,

The `[{"partial_match":true, ...}]` lets you know that there was some fuzziness in finding this place. You should be able to use this value to determine if there was an exact match or not. You can read more here: https://developers.google.com/maps/documentation/geocoding/intro#Results

> **partial_match** indicates that the geocoder did not return an exact match for the original request, though it was able to match part of the requested address. You may wish to examine the original request for misspellings and/or an incomplete address.
> 
> Partial matches most often occur for street addresses that do not exist within the locality you pass in the request. Partial matches may also be returned when a request matches two or more locations in the same locality. For example, "21 Henr St, Bristol, UK" will return a partial match for both Henry Street and Henrietta Street. Note that if a request includes a misspelled address component, the geocoding service may suggest an alternative address. Suggestions triggered in this way will also be marked as a partial match.
