### ISSUE TITLE
google map for play store version 6.4.12 ionic4

### ISSUE THREAD

**Issue by ajayshah1992** [googlemaps/google-maps-services-js#291]
I have custom phone which play store version is 6.4.12 and there is no way to update this play store version. we have an developed in ionic4. 
I am trying to to load google map in this phone but it always try to update play store which it not possible to update. But in General phone map loads.
So, Is there is way that ionbic 4 can run old plugin version, As In my case the path of observable in google is pointing to wrong path as ionic 4 points it to rxjs/index.

Or Is there is any way that it checks play store version and disables the location plugin

**Comment by amuramoto** [comment]
Please ask how-to questions on our StackOverflow tag:

https://stackoverflow.com/questions/tagged/google-maps
