### ISSUE TITLE
Machine-In-The-Middle vulnerability in package https-proxy-agent

### ISSUE THREAD

**Issue by silverio** [googlemaps/google-maps-services-js#293]
There is a Machine-In-The-Middle vulnerability in package `https-proxy-agent: "^2.2.1" `which is used in `@google/maps`. It has been patched in version >=3.0.0 .

[ https://npmjs.com/advisories/1184 ]( https://npmjs.com/advisories/1184 )

**Comment by jpoehnelt** [comment]
Thanks for reporting. I'll try to get a patch in shortly.

**Comment by jpoehnelt** [comment]
Now published to 1.0.2 https://www.npmjs.com/package/@google/maps.
