### ISSUE TITLE
Adding a way so that the InfoWindow can get a path to an html file.

### ISSUE THREAD

**Issue by ThomasBiede** [googlemaps/google-maps-services-js#297]
Today I wanted to style and make an InfoWindow for my marker, but it was pretty weird/difficult to design. I think that having to input and loooong html string as content is not very elegant. It would be better if I could set as the content string a path to a html file, instead of the html string.

it should look something like this:
`const marker = new google.maps.InfoWindow({
   content: './path/to/html/file'
});`

This would be a much more elegant approach and would imporve the developing experience because i wouldn't have to switch between an editing html file and copying the html document into the content string

**Comment by jpoehnelt** [comment]
Closing https://github.com/googlemaps/v3-utility-library/issues/566
