### ISSUE TITLE
Direction parameter's name is different with the official document

### ISSUE THREAD

**Issue by WildSaoFeng** [googlemaps/google-maps-services-js#298]
#### Environment details

API: 'directions'

'mode' is an optional parameter for the current version and in the official document it's a required parameter and the variable name is "travelMode".

[Google Map Doc](https://developers.google.com/maps/documentation/javascript/directions#TravelModes)

This may be a small thing but it costs me around 1 hour to figure out by reading source code. So hope others with better luck. 

Thanks!

**Comment by jpoehnelt** [comment]
It is optional here: https://developers.google.com/maps/documentation/directions/intro#optional-parameters which is correct. 

https://developers.google.com/maps/documentation/javascript/reference/directions#DirectionsRequest.travelMode is for the JavaScript Web API and not applicable here. It's confusing! I'll followup internally about this inconsistency.
