### ISSUE TITLE
Multiple place type in autocomplete query

### ISSUE THREAD

**Issue by dann95** [googlemaps/google-maps-services-js#299]
#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
Places Autocomplete
2. OS type and version
Linux 5.1.17-300.fc30.x86_64 #1 SMP Wed Jul 10 15:20:27 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
3. Library version and other environment information
"@google/maps": "^1.0.2",
#### Steps to reproduce

  1. Try search in places autocomplete api using more than one type.

#### Code example

```ts
export class PlacesService {

    public static async queryPlaces(q: string, language: string = 'pt-BR'): Promise<TPlaces> {
        const client: GoogleMapsClient = createClient({
            key: 'OMITED-KEY',
            language
        });
        const request: PlaceAutocompleteRequest = {
            input: q,
            types: [
                'address',
                'establishment'
            ]
        };
        const response = await client.placesAutoComplete(request).asPromise();
        const places: TPlaces = response.json.predictions.map(entry => ({
            description: entry.description,
            idPlace: entry.place_id
        }));

        return places;
    }
}
```
in the line https://github.com/googlemaps/google-maps-services-js/blob/master/lib/apis/places.js#L264
the validation of "one Of" seems to not match with google apis rules, using webservice in front-end im able to query with more than one type, and in this NodeJS library it throws error if you want to query with more than one type...
#### Specific library code:
 ```js
exports.placesAutoComplete = {
  url: 'https://maps.googleapis.com/maps/api/place/autocomplete/json',
  validator: v.object({
    types: v.optional(v.oneOf(['geocode', 'address', 'establishment', '(regions)', '(cities)'])),
  })
};
```

#### In a front-end project i have a code like this:
```js

class GoogleAddressService {
    get autoComplete() {
        if (!this.autoCompleteSDK) {
            this.autoCompleteSDK = new window.google.maps.places.AutocompleteService;
        }
        return this.autoCompleteSDK;
    }
    async search(input) {
        return new Promise((resolve, reject) => {
           this.autoComplete.getQueryPredictions({
               radius: 16000,
               types: [
                   'locality',
                   'sublocality',
                   'postal_code',
                   'country',
                   'administrative_area_level_1',
                   'administrative_area_level_2',
                   'administrative_area_level_3',
                   'establishment',
                   'geocode',
                   'address'
               ],
               input,
               location: {lat: () => -34, lng: () => 151},
               sessionToken: new window.google.maps.places.AutocompleteSessionToken()
           }, (response) => {
               resolve(response);
           })
        });
    }
}
```

Why this library blocks to query autocomplete places for more than 1 type?

**Comment by dann95** [comment]
Hmmmmmm #ping

**Comment by wangela** [comment]
Please see the [documentation for Place Autocomplete](https://developers.google.com/places/web-service/autocomplete#place_types). "In general only a single type is allowed". If you are implementing an Address autocomplete, you may want to choose just the `address` type.

**Comment by dann95** [comment]
"In general only a single type is allowed", that's not true, you can query multiple types in front-end SDK, that uses same service.. So why front-end do not validate multiple query?

**Comment by dann95** [comment]
"You may restrict results from a Place Autocomplete request to be of a certain type by passing a types parameter. The parameter specifies a **type** or a **type collection**, "

**Comment by dann95** [comment]
what is a "type collection"?

**Comment by dann95** [comment]
If "types" parameter **must** be only one item, it's really weird to be an Array, also to be plural type**S**,
