### ISSUE TITLE
rankby parameter giving back "INVALID_REQUEST"

### ISSUE THREAD

**Issue by nadabou** [googlemaps/google-maps-services-js#308]
#### Environment details

1. API: Google Places
2. OS: Debian 10
3. Library version
@google/maps: ^0.5.5
Node: v8.16.2

#### Steps to reproduce
Following the Google Places documentation, we are looking for nearby places using the following parameters object:
```
const googleMapsClient = require("@google/maps").createClient({
    key: process.env.GOOGLE_PLACES_API_KEY,
    Promise: Promise
  });

const placesNearbyParams = {
    location: `${address.latitude},${address.longitude}`,
    radius,
    type,
    rankby: 'distance'

  };
const response = await googleMapsClient
      .placesNearby(placesNearbyParams)
      .asPromise();
```
This code gives us this query:
[https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=48.857281,2.278315&radius=1000&rankby=distance&type=museum&key=KEY](url)
Which gives us an "INVALID_REQUEST":
![image](https://user-images.githubusercontent.com/29257680/73457906-b0d15e80-4374-11ea-8c08-3909f9582648.png)

When we change the query parameter `rankby` to `rankBy` in the browser
[https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=48.857281,2.278315&radius=1000&rankBy=distance&type=museum&key=KEY](url)
We get the following response, with all the nearby places displayed correctly:

![image](https://user-images.githubusercontent.com/29257680/73457787-85e70a80-4374-11ea-9940-680941e3b8d6.png)

If we try to change the parameters of the query:
```
  const placesNearbyParams = {
    location: `${address.latitude},${address.longitude}`,
    radius,
    type,
    rankBy: 'distance'
  };
```
We get the following error:

#### Stack trace
```
{ InvalidValueError: unexpected property "rankBy"
    at /home/nada/project/node_modules/@google/maps/lib/internal/validate.js:90:15
    at /home/nada/project/node_modules/@google/maps/lib/internal/validate.js:168:15
    at Array.forEach (<anonymous>)
    at Object.validator (/home/nada/project/node_modules/@google/maps/lib/internal/validate.js:167:16)
    at Object.placesNearby (/home/nada/project/node_modules/@google/maps/lib/index.js:55:25)
    at exports.fromGooglePlaces (/home/nada/project/app/services/google/google-places.js:32:8)
    at Object.module.exports.getNearbyPlaces (/home/nada/project/app/services/nearbyPlaces.js:39:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  message: 'unexpected property "rankBy"',
  name: 'InvalidValueError' }
```
Thanks!

**Comment by jpoehnelt** [comment]
Thanks for reporting. Please try the new package at https://www.npmjs.com/package/@googlemaps/google-maps-services-js/v/2.0.1.
