### ISSUE TITLE
How to pass in withCredential?

### ISSUE THREAD

**Issue by 5amfung** [googlemaps/google-maps-services-js#31]
When using this in angular 2 app, I get this error.  How do I pass in `withCredential: false`?

```
A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:4200' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.
```

**Comment by stephenmcd** [comment]
For client-side access you'll want to use the V3 JavaScript API: https://developers.google.com/maps/documentation/javascript/

The google-maps-services-js library is designed for server-side Node.js apps.
