### ISSUE TITLE
Places: API docs incorrect/misleading

### ISSUE THREAD

**Issue by adamreisnz** [googlemaps/google-maps-services-js#310]
#### Environment details

Node 12.14.1
Library: 1.1.0

#### Issue
Docs (https://googlemaps.github.io/google-maps-services-js/docs/GoogleMapsClient.html) specify:

![image](https://user-images.githubusercontent.com/490562/73604475-51828100-45f6-11ea-8ee3-9735bc5b0129.png)

That implies in my mind using components as follows:

```js
query.components = [
  'country:nz',
];
```

E.g. an array of strings, formatted as per https://developers.google.com/places/web-service/autocomplete#place_autocomplete_requests.

However, that is incorrect and it apparently should be:

```js
query.components = {
  country: 'nz',
};
```

Also, the docs appear to be for an older version: @google/maps 0.5.5

It looks like these docs maybe are outdated and either should be removed or updated.

**Comment by jpoehnelt** [comment]
I deleted the docs as they were over two years old. See the recent rewrite of this library: https://www.npmjs.com/package/@googlemaps/google-maps-services-js/v/2.0.1

**Comment by adamreisnz** [comment]
Then what is going on with the https://www.npmjs.com/package/@google/maps library?
It says it's been updated 19 days ago. Is it still active? Should we use it? Should we not? Should we use https://www.npmjs.com/package/@googlemaps/google-maps-services-js/v/2.0.1 instead?

Why are there two packages to begin with? Why isn't one of them deprecated or pointing to the other package? 

It's a bit confusing as you might imagine.
