### ISSUE TITLE
Unable to use as dependency with `npm ci --production` in Docker container

### ISSUE THREAD

**Issue by dcrck** [googlemaps/google-maps-services-js#315]
I get this error when trying to build my project in a docker container with `@googlemaps/google-maps-services-js` as a dependency:
```
Step 4/10 : RUN npm ci --production
 ---> Running in 61c4470277a5
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/jpoehnelt/query-string.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

If I remove this dependency, my builds work. This broke with the refactor, as it worked with `@google/maps`

**Comment by jpoehnelt** [comment]
Is git installed correctly in the docker image?

**Comment by jpoehnelt** [comment]
fyi: Hoping to remove this forked dependency soon and install it from npm.

**Comment by dcrck** [comment]
@jpoehnelt Nope, I'm using https://github.com/mhart/alpine-node for my base image. Feel free to mark this as closed if you don't want to use this issue to track the forked dependency work. I'll monitor the repository and update to the new package on my end when you make that update.
