### ISSUE TITLE
Where is the documentation for this package?

### ISSUE THREAD

**Issue by adamreisnz** [googlemaps/google-maps-services-js#318]
The examples in the readme are very limited. It is unclear how I can specify the API key globally in the client for example. Do I still have to pass a promise instance? What calls are available to us? Etc.

Either I must be missing a link or reference to the docs for this package or there simply aren't any.

Is there a migration guide to migrate from @google/maps?

**Comment by sakulstra** [comment]
I just tried migrating to the new version and while typings dramatically improved :+1:, the docs are kinda misleading

```
// from the docs: this seems to not be allowed by ts
const maps = new require("@googlemaps/google-maps-services-js");
// using import resolves to undefined
import maps from '@googlemaps/google-maps-services-js';
// working version would be sth like
import { Client } from '@googlemaps/google-maps-services-js';
```

**Comment by jpoehnelt** [comment]
>The examples in the readme are very limited. It is unclear how I can specify the API key globally in the client for example. Do I still have to pass a promise instance? What calls are available to us? Etc.
Either I must be missing a link or reference to the docs for this package or there simply aren't any.

Yeah, need to add some more examples and generate the typedocs. See #313 

> It is unclear how I can specify the API key globally in the client for example.

This is not currently supported. 

> Is there a migration guide to migrate from @google/maps?

Not at this time. Created #319

**Comment by jpoehnelt** [comment]
@sakulstra, @adamreisnz see the linked pr #320

**Comment by adamreisnz** [comment]
> This is not currently supported.

So are we expected to pass in the API key into *every single function call* of this package? Refactoring all our code to suite that is not really something I want to contemplate, so I think we'll stick with the old library for now until this is supported.

> Not at this time. Created #319

Thanks

**Comment by jpoehnelt** [comment]
>Refactoring all our code to suite that is not really something I want to contemplate

As an fyi, there is more than this change. It is going from:
```js
elevation({location:...}) 
```
to 

```js
elevation({params: {location: ..., key: ...}, timeout: 1000, ...}, axiosInstance)
```

See: https://github.com/googlemaps/google-maps-services-js#Migration
