### ISSUE TITLE
Old Documentation Missing

### ISSUE THREAD

**Issue by dw029** [googlemaps/google-maps-services-js#321]
Hi, we were using the old version of this library (published to @google/maps) for a project, but it seems after the migration, the link to the old reference documentation is broken. Could you please provide a link to it? Thanks.

**Comment by jpoehnelt** [comment]
https://github.com/googlemaps/google-maps-services-js/issues/310#issuecomment-583646519

**Comment by jpoehnelt** [comment]
Closing as the old documentation is out of date and it is recommended to use the new library.
