### ISSUE TITLE
[Places Autocomplete]: Session Token should be optional

### ISSUE THREAD

**Issue by avin-kavish** [googlemaps/google-maps-services-js#322]
As per the docs and comment right above it.

https://github.com/googlemaps/google-maps-services-js/blob/2f49ac96da6305c40f107de5f8dbdc1e05bbcea5/src/places/autocomplete.ts#L52

**Comment by kf6kjg** [comment]
Corresponds to PR #323, which is waiting on @avin-kavish signing the CLA.

**Comment by jpoehnelt** [comment]
closed via #323
