### ISSUE TITLE
Ability to set key at client creation

### ISSUE THREAD

**Issue by avin-kavish** [googlemaps/google-maps-services-js#324]
Great rewrite. Good idea to extend from axios req/res/err and pass it through to the user. It would be nice to set a default key (and any other sensible defaults) at client instantiation as not all use cases warrant supplying a different api key for each invocation. (Similar to how it was previously.)

**Comment by jpoehnelt** [comment]
Can probably be fixed with an interceptor.

```
ax.interceptors.request.use((config) => {
    config.params = config.params || {};

    if (!config.params.key) {
         config.params['apiKey'] = key;
    }

    return config;
});
```

 I wanted to get this out without any of these more complex patterns first as it moves the library another step from the actual interface as represented by the type definitions. This would require making the apiKey optional at the request params and required at the client.

**Comment by ibesora** [comment]
@avin-kavish I thought this make be useful to you. I solved this by wrapping the client in a new class, storing the key there and using object destructuring to overwrite the key parameter if found in the request params. 

```js
class GoogleMapsProvider {
  constructor () {
    this.client = new Client({})
    this.key = CONFIG.GOOGLE_MAPS_API_KEY
  }

  directions (params) {
    this.client.directions({
      params: {
        key: this.key,
        ...params
      }
    })
  }
}
```

**Comment by Bielik20** [comment]
I like the idea of using interceptor like in @jpoehnelt example. We would have to do something about `key` being required param though.

**Comment by iBobik** [comment]
It would be nice to solve it by the feature in the library because typescript require to fill it in the call anyway.
