### ISSUE TITLE
Need a clear documentation about how to set retry option for client(axios)?

### ISSUE THREAD

**Issue by mrdulin** [googlemaps/google-maps-services-js#326]
**Is your feature request related to a problem? Please describe.**

I read the source code and documentation. I didn't find any information about how to set the `retry` option for this library(or the axios module).

So I search `retry` keyword in this repository, only find related information on the `over-query-limit` branch. It seems a very old branch, out of date.

I didn't find `axios-retry` or `retry-axios` dependencies in package.json file or E2E tests for it either.

 **Describe the solution you'd like**

It seems this feature does not implement on the `master` branch. If it has been implemented, can you add this part to the documentation? Thanks.

**Alternatively way**

If this feature is not implemented yet. But I want this `retry` feature, what do you suppose to do if I decide to use and integrate `axios-retry` module with this library without modifying the source code.

**Comment by jpoehnelt** [comment]
Globally you can set retries on axios like this and it should work.

```
import axiosRetry from 'axios-retry';
axiosRetry(axios, { retries: 3 });
```

You can also create or modify the [default axios instance](https://github.com/googlemaps/google-maps-services-js/blob/master/src/client.ts#L80) and pass that to any of the lower level methods outside of the client class. See issue #342 about supporting custom axios instance in Client class.
