### ISSUE TITLE
Even though "latlng" is optional in reverse geocoding, the call throws an error when "latlng" is empty.

### ISSUE THREAD

**Issue by garzdin** [googlemaps/google-maps-services-js#327]
#### Environment details

API: Reverse Geocoding
OS: MacOS 10.15.3
Library version: 2.0.2

#### Description
The parameter is optional in the interface ([https://github.com/googlemaps/google-maps-services-js/blob/master/src/geocode/reversegeocode.ts#L27](https://github.com/googlemaps/google-maps-services-js/blob/master/src/geocode/reversegeocode.ts#L27)) and either _latlng_ or _place_id_ has to be supplied, but even when I supply _place_id_ it's still throwing an error, because it's trying to serialize the _latlng_ field.

#### Steps to reproduce

Make a call to the reverse geocoding API with an empty "latlng" parameter.

#### Code example

```javascript
const Client = require("@googlemaps/google-maps-services-js").Client;

const client = new Client({});

client
  .reverseGeocode({
    params: {
      latlng: [],
      key: apiKey,
    },
  })
```

#### Stack trace

```
TypeError: 
    at Object.latLngToString [as latlng] (/node_modules/@googlemaps/google-maps-services-js/src/serialize.ts:17:11)
    at Object.keys.forEach (/node_modules/@googlemaps/google-maps-services-js/src/serialize.ts:93:34)
    at Array.forEach (<anonymous>)
    at /node_modules/@googlemaps/google-maps-services-js/src/serialize.ts:91:25
    at buildURL (/node_modules/axios/lib/helpers/buildURL.js:31:24)
    at dispatchHttpRequest (/node_modules/axios/lib/adapters/http.js:84:13)
    at new Promise (<anonymous>)
    at httpAdapter (/node_modules/axios/lib/adapters/http.js:21:10)
    at dispatchRequest (/node_modules/axios/lib/core/dispatchRequest.js:52:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by danielkv** [comment]
+1

**Comment by jpoehnelt** [comment]
Why pass an empty array? It is not a valid LatLng object: https://github.com/googlemaps/google-maps-services-js/blob/master/src/common.ts#L443-L468

**Comment by garzdin** [comment]
> Why pass an empty array? It is not a valid LatLng object: https://github.com/googlemaps/google-maps-services-js/blob/master/src/common.ts#L443-L468

Because you might want to supply a `place_id` instead.

**Comment by jpoehnelt** [comment]
I added a [test](https://github.com/googlemaps/google-maps-services-js/compare/tests/reversegeocode?expand=1#diff-75c5c21525d719ccae199934c56545beR15-R22
).


```
test("reverseGeocode should return correct response using place_id", async () => {
  const params = {
    place_id: "ChIJKxDbe_lYwokRVf__s8CPn-o",
    key: process.env.GOOGLE_MAPS_API_KEY
  };
  const r = await reverseGeocode({ params: params });
  expect(r.data.results.length).toBeTruthy();
});
```
