### ISSUE TITLE
Cannot read property 'latest' of undefined

### ISSUE THREAD

**Issue by klaudi** [googlemaps/google-maps-services-js#33]
Hi,

**npm install** is failing due to https://registry.npmjs.org/google/maps is an empty JSON. This is the stack trace output.

`npm http 404 https://registry.npmjs.org/google/maps
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/local/Cellar/node/0.10.21/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/local/Cellar/node/0.10.21/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/local/Cellar/node/0.10.21/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/local/Cellar/node/0.10.21/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>`

**Comment by stephenfarrar** [comment]
Perhaps you need to upgrade your npm.

This page suggests that you might need npm 2.7.0:
https://docs.npmjs.com/getting-started/scoped-packages

**Comment by metaColin** [comment]
I ran into this too.

In my case a Docker instance was failing to build because the default version of NPM installed by Fedora's DNF package manager was too old to support scoped packages.

For anyone else encountering this issue in the context of Docker, I suggest updating NPM in your Dockerfile before running any other npm commands are run.

`RUN npm install npm -g`

**Comment by stephenmcd** [comment]
Thanks all for the feedback and advice. 

Closing this since it's unrelated to the lib itself.

**Comment by metaColin** [comment]
Maybe update the README to note the minimum version of NPM this package supports?

I realize it's not unique to this repo, but scoped packages are not super common just yet.

**Comment by stephenmcd** [comment]
@metaColin great idea, I'll do that shortly, thanks
