### ISSUE TITLE
Getting the time zone requires three API calls

### ISSUE THREAD

**Issue by ile** [googlemaps/google-maps-services-js#335]
I'm searching for a place and then finding out the time zone of it:

- First I get the Place ID of a place. I'm using the Autocomplete API for this.
- Then I use the Place Details API to get the latitude, longitude of that place.
- Then I use the lat/lng to get the time zone with Time Zone API.

Currently I have to use **three** APIs to get the time zone. This seems like an oversight, one shouldn't have to use three API calls here, IMO.

I would expect the Time Zone API to support place ids.

**Comment by amuramoto** [comment]
Please submit feature requests for the Time Zone API in the Maps Platform public issue tracker.

https://issuetracker.google.com/issues/new?component=188854&template=788019
