### ISSUE TITLE
Execption: Converting circular structure to JSON

### ISSUE THREAD

**Issue by tamal-appsbee** [googlemaps/google-maps-services-js#351]
Environment:
Nodejs 8.x
Gcoud app engine
Latest "google-maps-services-js" lib

// code 
const googleMap = require('@googlemaps/google-maps-services-js').Client;
const googleMapsClient = new googleMap({})

googleMapsClient.geocode({
        params: {
            address: addressStr,
            key: "____"
        }
    }).then(function (response) {
    }).catch(function(err){
        //  "Converting circular structure to JSON"
    });

The error is not very frequent but its coming sometime.

Thanks!

**Comment by jpoehnelt** [comment]
Can you provide a stack trace?

**Comment by tamal-appsbee** [comment]
I am trying to recreate it.

**Comment by jpoehnelt** [comment]
Please reopen this if you are able to reproduce.

**Comment by tamal-appsbee** [comment]
Ok
Thanks

**Comment by austin-wang** [comment]
This is the error I'm seeing.
```
error: Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'res' -> object with constructor 'IncomingMessage'
    --- property 'req' closes the circle
```
