### ISSUE TITLE
Problem running a simple example

### ISSUE THREAD

**Issue by amirhd23** [googlemaps/google-maps-services-js#352]
I am a Node newbie and I have problem running a simple example for this package. I ran _npm init_, and _npm install @googlemaps/google-maps-services-js_, have only one _index.js_ file with this content:
```
const Client = require("@googlemaps/google-maps-services-js").Client;
const client = new Client({});

client
  .elevation({
    params: {
      locations: [{ lat: 45, lng: -110 }],
      key: process.env.GOOGLE_MAPS_API_KEY
    },
    timeout: 1000 // milliseconds
  })
  .then(r => {
    console.log(r.data.results[0].elevation);
  })
  .catch(e => {
    console.log(e);
  });
```
here is my package.json:
```{
  "name": "google_api_node",
  "version": "1.0.0",
  "description": "Using google api with node",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Amir",
  "license": "ISC",
  "dependencies": {
    "@googlemaps/google-maps-services-js": "^2.1.2"
  }
}
```

when I try to run it by _node index.js_, I get this error: 
```
TypeError: Cannot read property 'elevation' of undefined
    at D:\node_practice\index.js:13:35
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
I am using nvm, and my node version is 13.9.0 .
I appreciate your help.

**Comment by jpoehnelt** [comment]
I'm unable to recreate with https://github.com/jpoehnelt/google-maps-services-js-demo. If you continue to have issues, I would follow up on Stackoverflow.

**Comment by amirhd23** [comment]
Hey, thanks for the reply and demo. I still had problem and created this post:
https://stackoverflow.com/questions/60558401/problem-running-simple-demo-example-google-maps-services-js-with-node

Thanks for your help.
