### ISSUE TITLE
getElevationsAlongPath

### ISSUE THREAD

**Issue by evanlk** [googlemaps/google-maps-services-js#355]
It appears this library is missing the getElevationsAlongPath functionality for elevations.

Below is an example of the request:

https://maps.googleapis.com/maps/api/elevation/json?path=36.578581,-118.291994|36.23998,-116.83171&samples=3&key=[YOUR API KEY]

Instead of 'locations' as the parameter, both 'path' and 'samples' parameters are provided instead.

**Comment by jpoehnelt** [comment]
Hi @evanlk, 

Please check out the new release with this missing request. Thanks for reporting!
