### ISSUE TITLE
Support for Places Nearby Search

### ISSUE THREAD

**Issue by tjchaplin** [googlemaps/google-maps-services-js#36]
From the documentation there is the ability to perform a nearby search within the Places api: 
https://developers.google.com/places/web-service/search

From the code: [places.js](https://github.com/googlemaps/google-maps-services-js/blob/master/lib/apis/places.js) and tests I was unable to find a way to use nearby search.

Here is what I would like to do:

```javascript
googleMapsClient.places({
		location: [-33.8670522,151.1957362],
		rankby : 'distance',
		type: 'restaurant',
		name:'cruise'
	},function(err, response) {
		if (!err) {
			console.log(response.json.result);
		}
	});
```

Is this something you would be willing to add in or is there another way?  I can provide a pull request.

Also, I understand this can be done with the text search request.  The issue is that the text search has a quota multiplier:
` That is, each Text Search request that you make will count as 10 requests against your quota`

## Additional Reference
The nearby search api url is as follows:
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522,151.1957362&radius=500&type=restaurant&name=cruise&key=YOUR_API_KEY

## Temp Solution
I have just added the following to places.js, to get my use case working:

```javascript
exports.places = {
  url: 'https://maps.googleapis.com/maps/api/place/nearbysearch/json',
  validator: v.object({
    location: utils.latLng,
    radius: v.optional(v.number),
    rankby : v.optional(v.string),//prominence, distance,
    type : v.optional(v.string),
    name : v.optional(v.string),
    keyword : v.optional(v.string),
    language: v.optional(v.string),
    minprice: v.optional(v.number),
    maxprice: v.optional(v.number),
    opennow: v.optional(v.boolean),
    pagetoken: v.optional(v.string),
    retryOptions: v.optional(utils.retryOptions),
    timeout: v.optional(v.number)
  })
};
```

**Comment by arch1t3ct** [comment]
+1 Weird this is missing.

**Comment by stephenmcd** [comment]
#37

**Comment by stephenmcd** [comment]
Thanks all for the feedback
