### ISSUE TITLE
not a LatLng or LatLngLiteral with finite coordinates: in property lat: NaN is not an accepted value

### ISSUE THREAD

**Issue by ahasantech** [googlemaps/google-maps-services-js#364]
Dear i facing the error, how i resolved the error

not a LatLng or LatLngLiteral with finite coordinates: in property lat: NaN is not an accepted value

![sdfasdfar44](https://user-images.githubusercontent.com/61349388/76678478-c97a9880-65f1-11ea-9314-1b653d1ac334.PNG)

 
---

**Comment by jpoehnelt** [comment]
Please reopen this at Stackoverflow as it is not related to this library or the Google Maps JS library. I would look at whatever is used to set the latitude property as it is invalid.

You should also revoke the key in the screenshot.
