### ISSUE TITLE
how to only select a set of field in any given api?

### ISSUE THREAD

**Issue by sibelius** [googlemaps/google-maps-services-js#366]
#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...") places detail
2. OS type and version mac os
3. Library version and other environment information: 2.0.2

#### Steps to reproduce

Try to only get minimum fields when calling place detail api

I'd like to avoid request Atmosphere Data (https://developers.google.com/places/web-service/usage-and-billing#atmosphere-data)

how can I avoid to query these fields: `price_level, rating, review, user_ratings_total`

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jpoehnelt** [comment]
You can use the [fields param](https://github.com/googlemaps/google-maps-services-js/blob/master/src/places/details.ts#L38). There is an [example](https://github.com/googlemaps/google-maps-services-js/blob/master/e2e/places/details.test.ts#L4-L11) in the e2e tests.

```
const params = {
    place_id: "ChIJKxDbe_lYwokRVf__s8CPn-o",
    key: process.env.GOOGLE_MAPS_API_KEY,
    fields: ["place_id", "name", "formatted_address"]
  };

  const r = await placeDetails({ params: params });
```

Let me know if this doesn't solve your issue.
