### ISSUE TITLE
Really?Where is the documentation for calculating distance?

### ISSUE THREAD

**Issue by sujeet-agrahari** [googlemaps/google-maps-services-js#367]
Searched everywhere, at `npm`, `/wiki` and also the `home-page`. I am so amazed why don't you guys give method names that are available for calculating distance and other things.

There is only one method mentioned `elevation` , that's it?
I need to calculate distance between two position (using lat and lng).

I couldn't find doc for methods to use.

**Comment by sujeet-agrahari** [comment]
Figured out going through source. Anyone, if new here.
```
const Client  = require('@googlemaps/google-maps-services-js').Client
const {
     GOOGLE_MAPS_API_KEY
 } = require('config')
const client = new Client({
    key: GOOGLE_MAPS_API_KEY
})

client
  .distancematrix({
    params: {
      origins: ["Seattle, WA"],
      destinations: [{ lat: 45, lng: -110 }],
      key: GOOGLE_MAPS_API_KEY
    },
    timeout: 1000 // milliseconds
  })
  .then(r => {
    console.dir(r.data.rows, { depth: 5});
  })
  .catch(e => {
    console.log(e);
  });
```

**Comment by jpoehnelt** [comment]
>Being considerate, kind, constructive, and helpful.

https://github.com/googlemaps/google-maps-services-js/blob/master/CODE_OF_CONDUCT.md

As the sole maintainer of this and many other projects, I do not appreciate this. 😞 

There is an issue for generating documentation, #313. I had it running but Typedoc kept failing.
