### ISSUE TITLE
Cannot find module 'http' and 'https

### ISSUE THREAD

**Issue by ImFranQ** [googlemaps/google-maps-services-js#378]
I installed `google-maps-services-js` and I try use `placeQueryAutocomplete` method. but when i run my app, show thats error..

i try install `http` and `https` modules with `npm i`, but conitnues the same error.

this is a **ionic angular** project.

log:
```
node_modules/@googlemaps/google-maps-services-js/node_modules/agentkeepalive/index.d.ts(2,25): error TS2307: Cannot find module 'http'.
node_modules/@googlemaps/google-maps-services-js/node_modules/agentkeepalive/index.d.ts(3,26): error TS2307: Cannot find module 'https'.
```

**Comment by jpoehnelt** [comment]
Typically this would be solved by modifying your tsconfig similar to https://github.com/TypeStrong/ts-node/issues/216#issuecomment-361606888. I'm not sure what the specific course of action should be for ionic applications. I am going to close this as I do not believe there is an action item here for the library. Let me know what you find!

**Comment by jpoehnelt** [comment]
Similar thread on ionic forums. `npm install @types/node --save`

**Comment by HamzaKhalidMirza** [comment]
ImFranQ, I got into the same problem. If you find any solution, kindly paste the solution here.
