### ISSUE TITLE
LatLon passed as a string not array in origins and destinations Documentation

### ISSUE THREAD

**Issue by tjgionet** [googlemaps/google-maps-services-js#379]
.

**Comment by jpoehnelt** [comment]
Please elaborate on the issue. The LatLng type is documented [here](https://googlemaps.github.io/google-maps-services-js/modules/_common_.html#latlng).

**Comment by tjgionet** [comment]
I was using LatLng when I needed LatLng[]. Thanks!

**Comment by jpoehnelt** [comment]
👍

**Comment by smasinde** [comment]
> 👍

Why are my params incorrect? 

const params = {
        origins: {lat: -34.397,lng: 150.644},
        destinations: {lat: -34.097,lng: 150.344},
        key: process.env.GOOGLE_MAPS_API_KEY
    };

**Comment by tjgionet** [comment]
> > 👍
> 
> Why are my params incorrect?
> 
> const params = {
> origins: {lat: -34.397,lng: 150.644},
> destinations: {lat: -34.097,lng: 150.344},
> key: process.env.GOOGLE_MAPS_API_KEY
> };

You need to use LatLng[] not LatLng. Should just be able to throw it each object in an array. 
I solved this by using strings originally as was done in the test .....

          origin: `${source.lat},${source.lon}`,
          destination : `${destination.lat},${destination.lon}`,
