### ISSUE TITLE
Inaccurate timezone offset when using GoogleMapsAPI.timezone

### ISSUE THREAD

**Issue by rich186** [googlemaps/google-maps-services-js#38]
#### Problem
When making a timezone request with `GoogleMapsAPI.timezone`, the returned timezone offset is incorrect.

#### Potential Cause
It seems the provided timestamp is shortened/rounded to 7 digits before hitting the API.

##### Example
This method call:
```
googleMapsClient.timezone({
  location: "51.47060013,-0.46194100",
  timestamp: 1481714646
});
```
Invokes this API request:
```
GET https://maps.googleapis.com/maps/api/timezone/json?location=51.47060013%2C-0.46194100&timestamp=1481715&key=API_KEY
{
  "dstOffset": 0,
  "rawOffset": 3600, // Incorrect
  "status": "OK",
  "timeZoneId": "Europe/London",
  "timeZoneName": "GMT+01:00"
}
```
As you can see the timestamp gets rounded and as a result the returned offset is incorrect. If I pass the timezone directly to the API then the correct offset is returned.
```
GET https://maps.googleapis.com/maps/api/timezone/json?location=51.47060013,-0.46194100&timestamp=1481714646&key=API_KEY
{
    "dstOffset": 0,
    "rawOffset": 0,
    "status": "OK",
    "timeZoneId": "Europe/London",
    "timeZoneName": "Greenwich Mean Time"
}
```

**Comment by stephenmcd** [comment]
#39
