### ISSUE TITLE
TypeError: Cannot set property 'raxConfig' of undefined

### ISSUE THREAD

**Issue by ronakamlani** [googlemaps/google-maps-services-js#380]
Thanks for the great library, I am getting following error. I have am not able to find similar issue, please help me to come out thanks.
This is TypeError: Cannot set property 'raxConfig' of undefined
```js
const client = new Client({});
client
  .directions({
    params: {
      origin: sourceLocation.latitude + "," + sourceLocation.longitude,
      destination:
        destinationLocation.latitude + "," + destinationLocation.longitude,
      waypoints: wayPointStr || "",
      key: config.GOOGLE_API_KEY,
    },
    timeout: 1000, // milliseconds
  })
  .then((r) => {
    console.log("New Api Request", r.data.results);
  })
  .catch((e) => {
    console.log("ERROR new Api", e);
  });

```

**Comment by jpoehnelt** [comment]
I am guessing this is related to https://github.com/JustinBeckwith/retry-axios/issues/95.

It may be necessary to use a custom axios instance to bypass this for the time being.

```js
const axiosInstance = axios.create(defaultConfig);
const client = new Client({axiosInstance});
```

**Comment by ronakamlani** [comment]
Thanks, I got it.

**Comment by jpoehnelt** [comment]
Fix is in https://github.com/JustinBeckwith/retry-axios/pull/114

**Comment by binjiezhao** [comment]
@jpoehnelt Can you kindly point out what is defaultConfig in below code please? Thanks.
`const axiosInstance = axios.create(defaultConfig);
const client = new Client({axiosInstance});`

**Comment by jpoehnelt** [comment]
>  I'm still getting this 'raxConfig' undefined error

As expected. There is another error that is occurring. See https://github.com/JustinBeckwith/retry-axios/pull/114

> Can you kindly point out what is defaultConfig in below code please?

https://github.com/googlemaps/google-maps-services-js/blob/master/src/client.ts#L95
