### ISSUE TITLE
The README example doesn't work (copy/paste)

### ISSUE THREAD

**Issue by emilioriosvz** [googlemaps/google-maps-services-js#382]
```
const Client = require("@googlemaps/google-maps-services-js").Client;
const client = new Client({});

client
  .elevation({
    params: {
      locations: [{ lat: 45, lng: -110 }],
      key: process.env.GOOGLE_MAPS_API_KEY
    },
    timeout: 1000 // milliseconds
  })
  .then(r => {
    console.log(r.data.results[0].elevation);
  })
  .catch(e => {
    console.log(e);
  });

```

I get: 
```
TypeError: Cannot read property 'elevation' of undefined
```

**Comment by jpoehnelt** [comment]
I added an e2e test to try and recreate this, but was unable to. You can see the test code here: https://github.com/googlemaps/google-maps-services-js/pull/383/files#diff-621a198089dc1bfecee502d10c41b464R47-R65.

Are you sure the client was instantiated?

**Comment by emilioriosvz** [comment]
yes! 
My code was exactly the same as the one that is in the readme (with my API key of course)

**Comment by jpoehnelt** [comment]
I tried with https://github.com/jpoehnelt/google-maps-services-js-demo and am still unable to recreate. 🤔

**Comment by jpoehnelt** [comment]
Going to close for now. Let me know if you have a reproducible example.

**Comment by rferrante1966** [comment]
Is it too late to second this users issue? I can't get the sample in the readme to work either. 
 I tried with https://github.com/jpoehnelt/google-maps-services-js-demo and have the same issue.

I'll read through your test, but thought I would second the issue.

I've been trying to get it to work on an off for a few weeks.  I attached a script that did work. Maybe there are some packages installed on your system (prerequisites) not mentioned?

Thanks  and Regards,
Rick


[geotest.js.txt](https://github.com/googlemaps/google-maps-services-js/files/4466696/geotest.js.txt)
![geotest js output](https://user-images.githubusercontent.com/6255319/79074929-4f573580-7cbd-11ea-9073-6966a7a74178.jpeg)


const Client = require("@googlemaps/google-maps-services-js").Client;
const client = new Client({});

client
  .elevation({
    params: {
      locations: [{ lat: 45, lng: -110 }],
      key: process.env.GOOGLE_MAPS_API_KEY
    },
    timeout: 1000 // milliseconds
  })
  .then(r => {
    console.log(r.data.results[0].elevation);
  })
  .catch(e => {
    console.log(e);
  });

I get:

TypeError: Cannot read property 'elevation' of undefined

**Comment by jpoehnelt** [comment]
I'll check this again.

**Comment by jpoehnelt** [comment]
I added a ci test to the demo repo that installs from a clean github action: https://github.com/jpoehnelt/google-maps-services-js-demo/runs/583339047?check_suite_focus=true. This works without issue. 🤔

**Comment by rferrante1966** [comment]
Hey, so I created a new aws ec2:

 (ImageId='ami-0a887e401f7654935' Amazon Linux AMI (HVM / 64-bit)) which is

 [root@ip-172-31-37-26 ~]# uname -a
Linux ip-172-31-37-26.ec2.internal 4.14.165-131.185.amzn2.x86_64 #1 SMP Wed Jan 15 14:19:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Based on aws docs, I installed Node.  Basically as root i ran :
1. curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
2. . ~/.nvm/nvm.sh
3. nvm install node
Then i ran:
4. yum install git
5. make a project dir (mkdir /opt/geo) and change into that dir (cd /opt/geo).
6. npm init
5.   npm install @googlemaps/google-maps-services-js
6. cd into @googlemaps/google-maps-services-js and ran "npm install"
7.  export GOOGLE_MAPS_API_KEY=[put-my-key-here]
8.   put the sample in a file called index.js with this line at the top:
const Client = require("@googlemaps/google-maps-services-js").Client;
const client = new Client({});

client
  .elevation({
    params: {
      locations: [{ lat: 45, lng: -110 }],
      key: process.env.GOOGLE_MAPS_API_KEY
    },
    timeout: 1000 // milliseconds
  })
  .then(r => {
    console.log(r.data.results[0].elevation);
  })
  .catch(e => {
    console.log(e);
  });

10.  Tried running "node index.js" but got error 
[root@ip-172-31-37-26 geo]# node geotest.js
TypeError: Cannot read property 'elevation' of undefined
    at /opt/geo/geotest.js:13:35
    at processTicksAndRejections (internal/process/task_queues.js:97:5)




I'm sure i'm doing a Node newbie mistake, but I just cant seem to move on. 
Any help would be appreciated.
thanks,
Rick

**Comment by jpoehnelt** [comment]
The problem appears to be that the server returns a 200 for many failed responses such as invalid keys. For the example in the readme, this means that `r.data.results[0]` is undefined in the `.then`. It is **not** that `client.elevation` is `undefined`. 

```js
.then((r) => {
  if (r.data.status === "OK") {
  } else {
    // handle error
  }})
.catch(// handle network error)
```

See https://github.com/googlemaps/google-maps-services-js/issues/393 for more information and a feature request to reject when `r.status !== Status.OK`. 

I will update the readme to reflect this.
