### ISSUE TITLE
AddressType variables update

### ISSUE THREAD

**Issue by jspkevin** [googlemaps/google-maps-services-js#384]
Could you add 'sublocality_level_1' to 'sublocality_level_5' to AddressType so that I can resolve the names when I get values from address_components?

Thank you so much,

**Comment by dvester** [comment]
`establishment` is also missing from `AddressType`

**Comment by dvester** [comment]
The directions API result `data.routes.legs.polyline` is listed as a string, but it should be an object with one property named `points` which is a string.

**Comment by jpoehnelt** [comment]
What are your thoughts on https://github.com/googlemaps/google-maps-services-js/pull/385? 

This is a never ending challenge and even the documentation link isn't entirely accurate at all times. Unfortunately, I've dug through the internals and there is no **single** source of truth for what will be returned here and definitely no way to automate these updates.

@dvester Mind submitting a pr or separate bug for the data.routs.legs.polyline?

**Comment by jspkevin** [comment]
Thought their update was not so frequent but as said if the source was not accurate that is no sense to trace. I got some workaround now so I can close this.

**Comment by jpoehnelt** [comment]
I'm going to also look into make these as enums too.
