### ISSUE TITLE
The directions API result `data.routes.legs.polyline` is listed as a string, but it should be an object with one property named `points` which is a string.

### ISSUE THREAD

**Issue by jpoehnelt** [googlemaps/google-maps-services-js#387]
The directions API result `data.routes.legs.polyline` is listed as a string, but it should be an object with one property named `points` which is a string.

_Originally posted by @dvester in https://github.com/googlemaps/google-maps-services-js/issues/384#issuecomment-612062492_

**Comment by jpoehnelt** [comment]
@dvester I am unable to reproduce. There is no `legs.polyline`.

**Comment by dvester** [comment]
My mistake is actually under steps. Here is the documentation.


https://developers.google.com/maps/documentation/directions/intro#Steps



-------- Original message --------

**Comment by jpoehnelt** [comment]
Got it, thanks!
