### ISSUE TITLE
Waypoints not optimized despite the parameter is set to true ...

### ISSUE THREAD

**Issue by maslopop** [googlemaps/google-maps-services-js#391]
Trying to get the best route to cross some geographical points, I tried to use google directions, but with this library, despite the optimaze parameter set to true, however, it is not possible to obtain the optimized order, much less specify the stopover parameter.

This is part of mi code:
```
const Client = require("@googlemaps/google-maps-services-js").Client;
const client = new Client({});
client
  .directions({
    params: {
      key: api,
      origin: destins[0],
      destination: destins[0],
      mode: "driving",
      waypoints: destins, // max 23 + origin e destination
      optimize: true,
      alternatives: false,
      avoid: ["tolls" | "highways" | "ferries" | "indoor"],
      language: "it",
      units: "metric",
      departure_time: "now",
      traffic_model: "best_guess"
    }
  })
```

Thank you 
Massimo

**Comment by jpoehnelt** [comment]
@maslopop Thanks for finding this bug. I will work on a fix right away.

**Comment by jpoehnelt** [comment]
@maslopop master has this fixed, running into some network issues with our proxy to publish to npm. hopefully those will be resolved shortly
