### ISSUE TITLE
Reject promise if result not 'OK'

### ISSUE THREAD

**Issue by jpoehnelt** [googlemaps/google-maps-services-js#393]
The server returns a 200 for almost every call regardless of the success of the call. This means the user must handle this switch.

```js
.then((r) => {
  if (r.data.status === "OK") {  // note r.data.status and not r.status!!
  } else {
    // handle error
  }})
.catch(// handle network error)
```

It should be possible to do this for the user.

**Comment by MaxMartiFoundry** [comment]
This also makes the retry functionality ineffective, as it's impossible for axios to know that the request should be considered failed. This is especially annoying when we expect a failure as part of normal operation, as in the case of retrieving nearby Places paginated results.

**Comment by jpoehnelt** [comment]
Agreed about how much this pattern stinks! Probably need to implement this via an interceptor.

**Comment by MaxMartiFoundry** [comment]
I've been attempting to do just that (interceptor or transformResponse), but ran into https://github.com/googlemaps/google-maps-services-js/issues/380 . Not having much luck with the workaround...

**Comment by adamreisnz** [comment]
It's really frustrating, the new client feels like a massive step back from the old client, which was able to handle this gracefully. Now I find myself adding non essential boilerplate code to handle issues like this.

**Comment by jpoehnelt** [comment]
I know this is frustrating, I'm dealing with this exact issue with some internal code too. All of us wish that these used the correct HTTP status codes, but that original decision was a decade ago.  Perhaps over the next couple years as these libraries move to gRPC, this can be resolved correctly.

## Background
This [axios issue](https://github.com/axios/axios/issues/1064) is related, but I haven't found a best practice implementation for this logic. 

https://stackoverflow.com/questions/56490410/axio-interceptors-how-to-throw-errors-in-the-onfulfill is an suggestion to patch axios. 

Here is a suggestion to use a custom http adapter https://stackoverflow.com/questions/59401146/how-can-i-change-the-result-status-in-axios-with-an-adapter

 Another set of answers https://stackoverflow.com/questions/54614612/axios-override-get-status-code-from-the-data-response-instead-of-status.

## Design
The thrown error should implement [AxiosError](https://github.com/axios/axios/blob/b03f16159eac889baba067ff1e53e8701c86728e/index.d.ts#L85-L92) using the [createError](https://github.com/axios/axios/blob/master/lib/core/createError.js) from axios.

**Always Resolve**:  `OK, NOT_FOUND`
**Always Reject**: `INVALID_REQUEST,  MAX_WAYPOINTS_EXCEEDED,  MAX_ROUTE_LENGTH_EXCEEDED,  OVER_DAILY_LIMIT,  OVER_QUERY_LIMIT,  REQUEST_DENIED,  UNKNOWN_ERROR,  ZERO_RESULTS`

### Wrap the axios call
One solution is to implement this a function that wraps the axios call. This somewhat helpful but doesn't let the user make use of other axios interceptors. 👎 

```js
function foo() {
  return axios.get().then((r) => {
    if (r.data.status === "OK") {
      throw createError(r.data.status);
    }
    return r;
  });
}

```
### Modify the status code with interceptor
This will still resolve. 👎 

```js
axios.interceptors.response.use(
  function (r) {
    if (r.data && r.data.status) r.status = r.data.status;
    return response;
  },
  function (error) {
    return Promise.reject(error);
  }
);
```

### Custom http adapter
Sourced from [stackoverflow](https://stackoverflow.com/questions/59401146/how-can-i-change-the-result-status-in-axios-with-an-adapter). This is a further upstream change than the interceptor above. I believe this should work without any of the problems above. 👍  

This is probably the riskiest given the surface area to understand between this and what is returned to the user. ❗ 
```js
const httpAdapter = require("axios/lib/adapters/http");
const settle = require("axios/lib/core/settle");

const customAdapter = (config) =>
  new Promise((resolve, reject) => {
    httpAdapter(config)
      .then((r) => {
        if (r.status === 200) {
          r.status = statusStringToCode(r.data.status);
        }
        settle(resolve, reject, r);
      })
      .catch(reject);
  });
```

**Comment by jpoehnelt** [comment]
Please see the #407 pull request and comment if you have any feedback on the implementation. Will merge next week otherwise.

**Comment by adamreisnz** [comment]
For the purpose of throwing errors, this looks good to me. I use a plugin for the purpose of the plugin, and don't really care to mess with whatever http client that plugin chooses to use. If I need to parse output, I will do that in my own code and won't rely on transformations or modifications of the http client that the plugin uses, so feel free to modify with interceptors as much as needed. 

That's why tbh I also find it somewhat annoying that now the params we pass to the plugin are essentially Axios parameters/config.

What if you suddenly decide to switch from Axios to bent or another http client? It will essentially affect every project that has been built on this plugin, and the interface will likely have to be adjusted to suit the new http client.

Why was the decision made to expose the http client implementation and not just keep it under the hood?

**Comment by jpoehnelt** [comment]
> Why was the decision made to expose the http client implementation and not just keep it under the hood and have end users simply use it as a black box?

Not all use cases use just the black box and it is impossible to stay at that pure implementation as users run into issues dealing with proxies or want to manage HTTP retries. This quickly devolves into a unmaintainable mess as the interface of the black box grows. You can see this in the old client library with its own buggy retry and throttling logic and confusing interface. Eventually you have defined another unique interface that matches 80% of what a library like Axios already does. This library tries to skip all of that and just get to that end state. 

Except for this issue around transforming the response, there really isn't anything tying this client library to Axios that would prevent switching or even supporting more transport layers. That would be the ideal solution, but is just not worth the effort at this time. I hope this to be deprecating this library in the next couple years as all of these google maps platform client libraries move to gRPC.

**Comment by adamreisnz** [comment]
Cheers, many thanks for clarifying 👍
