### ISSUE TITLE
Geocoder: Incorrect typing for GeocodeResult["types"]

### ISSUE THREAD

**Issue by OscarBarrett** [googlemaps/google-maps-services-js#402]
It's [currently typed as `AddressType`](https://github.com/googlemaps/google-maps-services-js/blob/e99b4f911b4d4d29efaf78e02de620ea3b683687/src/common.ts#L1319), however AddressType does not describe the possible values. 

For example, geocoding the name of a car dealership I get the following types

```js
[ 'car_dealer', 'establishment', 'point_of_interest', 'store' ]
```

Which appear in `PlaceType1`, `PlaceType2`, `PlaceType2` and `PlaceType1` respectively - not a single value from `AddressType`.

**Comment by jpoehnelt** [comment]
Do you have an example query returning car dealer as a type in a geocoding result?

**Comment by OscarBarrett** [comment]
```typescript
import { Client } from '@googlemaps/google-maps-services-js';

const run = async () => {
  const client = new Client();
  const result = await client.geocode({ params: {
    key: '<key>',
    address: 'Perth 4WD & Commercial Centre',
  } });
  console.log(result.data.results[0].types);
};

run();
```
