### ISSUE TITLE
Cannot set property 'raxConfig' of undefined

### ISSUE THREAD

**Issue by classic0** [googlemaps/google-maps-services-js#403]
## Environment details
node --version v13.9.0
@googlemaps/google-maps-services-js": "^2.6.0

package.json:
"type": "module"

#### Code example

```python
import { createRequire } from 'module';
const require = createRequire(import.meta.url);

const { Client, Status } = require("@googlemaps/google-maps-services-js");
const client = new Client({});
client.distancematrix({
    params: {
        origins: ['place_id:ChIJD7fiBh9u5kcRYJSMaMOCCwQ'],
        destinations: ['place_id:ChIJXSModoWLGGARILWiCfeu2M0'],
        key: 'API_KEY',
    }
})
.then((r) => {
    console.log(r.data, 'response');
})
.catch((e) => {
    console.log(e);
})
```

#### Stack trace
```
TypeError: Cannot set property 'raxConfig' of undefined
    at onError (/home/rando/Kribamine/GMaps/node_modules/retry-axios/build/src/index.js:99:26)
```

Key is definitely not the problem since placeAutocomplete functions with it. 

Also when doing an import as some other usual libraries, express for example:
```
import {Client, Status} from "@googlemaps/google-maps-services-js";
        ^^^^^^
SyntaxError: The requested module '@googlemaps/google-maps-services-js' does not provide an export named 'Client'
```
That's why up there there's createRequire workaround made. Would be great not have to do it for all google libraries, but still keeping type modules, could it be done?

**Comment by classic0** [comment]
#380 solved the problem for the most part but still it would be great to hear if there are any workarounds for the import issue.

**Comment by jpoehnelt** [comment]
I submitted a pr in retry-axios fixing this: https://github.com/JustinBeckwith/retry-axios/pull/114

**Comment by leonarpv** [comment]
Hi, i have the same Issue

node -v v12.8.1

@googlemaps/google-maps-services-js: "^3.1.2"

Code example:
```

import config from 'config';
import axios from 'axios';
import { Client, Status } from "@googlemaps/google-maps-services-js";
```

I have this error when try to up the node backend app.

`import { Client, Status } from "@googlemaps/google-maps-services-js";
         ^^^^^^
SyntaxError: The requested module '@googlemaps/google-maps-services-js' does not provide an export named 'Client'`

**Comment by leonarpv** [comment]
Solved..!
Using requirejs.
Code example:
```
import requirejs from ' ';
import config from 'config';
import axios from 'axios';
const {
  Client,
  PlaceInputType,
  Language,
  Status,
  UnitSystem
} = requirejs('@googlemaps/google-maps-services-js')
```
