### ISSUE TITLE
Status enum does not contain "NOT_FOUND".

### ISSUE THREAD

**Issue by SamCB** [googlemaps/google-maps-services-js#404]
#### Environment details

Concerning the status `Status` Enum
Found on macOS 10.14.6 with `"@googlemaps/google-maps-services-js@2.6.0"` installed via yarn. Typescript version 3.8.3.

#### Steps to reproduce

1. Import `Status` and try and use `Status.NOT_FOUND`. Typescript will complain.
2. Documentation [here](https://developers.google.com/places/web-service/details#PlaceDetailsStatusCodes) suggests it is a valid response status.

#### Code example

```ts
import {Client, Status} from '@googlemaps/google-maps-services-js';
const c = new Client({});
response = await c.PlaceDetails({
  params: {
    place_id: 'xyz',
    fields: [/* ... */],
    key: 'foobar',
  }
});

switch (response.data.status) {
  // ...
  case Status.NOT_FOUND:
    console.log("NOT FOUND");
    break;
  // ...
}

```

Will result in a typescript error

```
foobar:x:y - error TS2339: Property 'NOT_FOUND' does not exist on type 'typeof Status'.

xxx     case Status.NOT_FOUND:
```

**Comment by jpoehnelt** [comment]
Mind submitting a pr?
