### ISSUE TITLE
Geocode to accept param "place_id"

### ISSUE THREAD

**Issue by jasonc624** [googlemaps/google-maps-services-js#408]
The Geocoding endpoint does support querying by placeId.

Feature request: Update library to allow usage of `place_id` as a param.

current support exists only for the following params `address`, `bounds`, `language`, `region`, `components`.

**Comment by Matgsan** [comment]
Just opened a PR about this! I need to use this in my project also.

As mentioned in the docs, 
https://developers.google.com/maps/documentation/geocoding/best-practices#user-input

Its a good practice to use place_id instead of the address string while geocoding.
