### ISSUE TITLE
Image data corrupt

### ISSUE THREAD

**Issue by mendrik** [googlemaps/google-maps-services-js#412]
1. Places API photo
2. Windows 10
3. @googlemaps/google-maps-services-js@3.0.0 nodejs

#### Steps to reproduce

  1. Fetch any photo details by photo reference like so:
```
   const response = await client.placePhoto({
                params: {
                    key: PHOTOS_KEY,
                    photoreference: details.photos![0].photo_reference,
                    maxwidth: 400
                }
            });
```

try to send this back in cloud functions like so:

```
            res.setHeader('cache-control', response.headers['cache-control'])
            res.setHeader('content-type', response.headers['content-type'])
            res.status(200).send(Buffer.from(response.data, 'utf-8')).end()
```
I have tried any kind of combinations with or without Buffer conversion, but the result is never a valid image. response.data seems to contains some sort of image information. (logs show it as:
`����JFIF��*ExifII*1Google���[...]´

However I cannot convert it to anything useful. If I use fetch to the photo endpoint and redirect() to res.url instead I can see a valid place photo.

**Comment by mendrik** [comment]
not sure if it helps but when I by-pass the lib and do it like so:
```
            const url = new urls.URL('https://maps.googleapis.com/maps/api/place/photo')
            url.searchParams.append('key', PHOTOS_KEY)
            url.searchParams.append('photoreference', photos[0].photo_reference)
            url.searchParams.append('maxwidth', '480')

            const imageDataRes = await fetch(url.toString())
            const data = await imageDataRes.buffer()
            res.status(200)
                .set('Cache-Control', 'public, max-age=300, s-maxage=600')
                .contentType(imageDataRes.headers.get('content-type')!)
                .send(data)
```

it works.

**Comment by jpoehnelt** [comment]
The issue is that axios default responseType is json and should be one of `arraybuffer`, `stream`, etc. I have a fix incoming to update the type definitions and set a better default.

This is also probably the issue in #396
