### ISSUE TITLE
Params Location and Components

### ISSUE THREAD

**Issue by mikeycrostar** [googlemaps/google-maps-services-js#415]
Hello,

I'm trying to implements the google API placeQueryAutocomplete with address restrictions on the US but it doesn't seem to work properly with the params I gave (I still have results in others countries than the US), the documentation is really unclear about that and I've tried some fix issued who talk about this, still doesn't work.
I tried this:
`
return await client.placeQueryAutocomplete({
            params: {
                input: address,
                key: config.googleApiMap,
                location: {lat: config.geolocation.geopoint.lat, lng: config.geolocation.geopoint.lng},
                radius: config.geolocation.radius
            },
        } as PlaceQueryAutocompleteRequest);
`
and that: 

`
return await client.placeQueryAutocomplete({
            params: {
                input: address,
                key: config.googleApiMap,
                components: "country:US"
            },
        } as PlaceQueryAutocompleteRequest);
`

API version: 2.6.1

**Comment by jpoehnelt** [comment]
You like want to use `client.placeAutocomplete`(https://developers.google.com/places/web-service/autocomplete) as this supports the components param. `placeQueryAutocomplete` does not.

**Comment by mikeycrostar** [comment]
Oh ok thank you,
it's working properly now.
