### ISSUE TITLE
Help with reject conditions

### ISSUE THREAD

**Issue by tim-rohrer** [googlemaps/google-maps-services-js#417]
Related to #393, I think

I'm trying to understand and implement this lib. I understand `Status.OK` resolves. #393 reads as though `Status.NOT_FOUND` should have also resolved, but the code [here](https://github.com/googlemaps/google-maps-services-js/blob/master/src/adapter.ts) reads to me as if the api will resolve for `Status.ZERO_RESULTS` and `Status.OK` while rejecting for `Status.NOT_FOUND`. What am I misunderstanding?

Second, is there a way to capture the reason for the rejection?

Thanks.

**Comment by jpoehnelt** [comment]
`Status.NOT_FOUND` only occurs when an id is passed and does not exist and is most like a 404. `Status.ZERO_RESULTS` is for the search methods and an empty list as a response and would still be a 200.

> Second, is there a way to capture the reason for the rejection?

Nope 😞

**Comment by tim-rohrer** [comment]
For my code, the `Status.NOT_FOUND` is rejected then?

**Comment by jpoehnelt** [comment]
>For my code, the Status.NOT_FOUND is rejected then?

It should be.

**Comment by tim-rohrer** [comment]
Thank you. I appreciate your quick reply.
