### ISSUE TITLE
Places API: Request failed with status code 400 Error

### ISSUE THREAD

**Issue by mhaas2-tgm** [googlemaps/google-maps-services-js#419]
Please be sure to include as much information as possible:

#### Environment details

1. Places-API (NearByPlaces Search)
2. NodeJS 10 Firebase Function Instance

#### Steps to reproduce
I tried to get Places, but I keep getting an code 400 Error.
This is my code:

#### Code example

```javascript
exports.testPlace = functions.https.onRequest((request, response) => {

    client
    .placesNearby({
        params: {
            locations: "sample,sample",
            key: "*****************************",
            radius: 1500,
        },
    })
    .then((r) => {
        console.log(r.data.results[0]);
        return null;
    })
    .catch((e) => {
        console.log(e+" Error");
    });
});
```
Also I am very new to NodeJS, so this might be a really stupid Error.

**Comment by kevsjh** [comment]
@mhaas2-tgm Were you able to resolve this? I am getting the same error as well

**Comment by pnyennhi** [comment]
Hi @markusbug, did you find the way to solve this error?
