### ISSUE TITLE
Get Distance from latitude and longitude

### ISSUE THREAD

**Issue by ankurlogistic** [googlemaps/google-maps-services-js#425]
**PLEASE READ** 

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response. 

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/). 

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

Is it possible to get a distance from Latitude and Longitude
example
```
client
      .distancematrix({
        params: {
          key: key
          units: "imperial",
          origins: ["22.2805459", "70.8011263"],
          destinations: ["22.2970336", "70.8148468"],
        },
      })
      .then((r) => {
       
      })
      .catch((e) => {
     
      });
```

**Comment by jpoehnelt** [comment]
I added a test for this example, https://github.com/googlemaps/google-maps-services-js/commit/4bc28d33af0db40292c00651c8d3cef6c33f0ae6#diff-185e6932aecd3bb1b6df5d41950d38dbR33
