### ISSUE TITLE
PlaceAutocompleteResult interface not exported on main module

### ISSUE THREAD

**Issue by jmurgey** [googlemaps/google-maps-services-js#429]
Hello,

First of all, thanks for this rewriting of the old library!

I have an issue while trying to type my own code using the embedded typings: I want to use the `PlaceAutocompleteResult` interface, but it isn't exposed on the public API. It surprised me as the other result interfaces like `GeocodeResult` are exposed.
Is there a reason not to expose the `PlaceAutocompleteResult` interface?

If you're ok with exposing it, I'd be glad to send a pull request. 😃 

Thanks again for this work!

**Edit:** I imported it directly from the autocomplete sub-module as a temporary solution
```
import { PlaceAutocompleteResult } from '@googlemaps/google-maps-services-js/dist/places/autocomplete';
```

**Comment by jpoehnelt** [comment]
Thanks for catching this. Should be in the release published shortly.
