### ISSUE TITLE
[docs] Simple, yet effective, example use of each API method

### ISSUE THREAD

**Issue by gregfenton** [googlemaps/google-maps-services-js#454]
**Is your feature request related to a problem? Please describe.**
Get a Node/Javascript developer who is not familiar with this API set to use just the published documentation from this project to figure out how to use `geocode()`.  The information is here, but it involved me following links to several other Google Maps projects/APIs, having to decode examples not using `geocode()`, and trying to leverage [the info at this page that was ...](https://googlemaps.github.io/google-maps-services-js/modules/_geocode_geocode_.html) not straightforward. 

 **Describe the solution you'd like**

A simple, "realistic" example of the invocation of each API.  For example for `geocode()` it could be:
```js
import { Client } from '@googlemaps/google-maps-services-js';

const run = async () => {
  const client = new Client();
  const result = await client.geocode({ params: {
    key: '<key>',
    address: 'Perth 4WD & Commercial Centre',
  } });
  console.log(result.data.results[0].types);
};

run();
```

 **Describe alternatives you've considered**

Google searches, YouTube views, and eventually figured things out by looking over [Issues ](https://github.com/googlemaps/google-maps-services-js/issues/402) for this very GitHub repo.

 **Additional context**

The info is here.  But it isn't readily "accessible".  It involves a lot of jumps.  Could be simpler with just a few lines of docs.

**Comment by jpoehnelt** [comment]
This runs into the perpetual challenge of keeping functioning code snippets in documentation. At this time I do not have a solution other than linking to the e2e tests folder.

**Comment by jpoehnelt** [comment]
@gregfenton Do you use TypeScript?

**Comment by gregfenton** [comment]
> @gregfenton Do you use TypeScript?

I do not.

**Comment by gregfenton** [comment]
> This runs into the perpetual challenge of keeping functioning code snippets in documentation.

Directionally correct is more important than perfectly correct "copy-n-paste" examples.

> At this time I do not have a solution other than linking to the e2e tests folder.

First, many API documentations have examples in them.  This is not a new pattern.

Second, I would be fine with pointing to any test code as long as those tests showcase "realistic uses" rather than just passing in trivial and meaningless data (i.e. use a real address, or real lat/long values, etc.  Show how to work with the return values.  This is what took time to figure out just looking at the API docs themselves.  See the above example...it shouldn't take several searches to pull together a few lines of code.)

Thanks for the consideration!

**Comment by gregfenton** [comment]
I'll happily submit a docs PR, if someone would provide direction as to where such an above example should be submitted.  Or maybe a pointer to a guide on documentation for this project so I am submitting something inline with the "docs standard".

**Comment by jpoehnelt** [comment]
It should be possible to add examples to the comments using markdown syntax and the running `npm run docs` to see the output. 

The docs are generated by TypeDoc, see https://typedoc.org/guides/doccomments/#code-blocks.

**Comment by gregfenton** [comment]
@jpoehnelt  When I run `npm run docs`, the docs folder is created and files are generated but I do not see the particular documentation page this issue describes.  Should I not be finding a file `./docs/modules/_geocode_geocode_.html` ?

I am adding a code snippet example to `src/geocode/geocode.ts`.  But grep'ing all of `./docs` I do not find my code?

**Comment by jpoehnelt** [comment]
Might need to document the method in https://github.com/googlemaps/google-maps-services-js/blob/master/src/client.ts on the `Client` class. I'm guessing that is why they are not showing up. The non client api functions are not document in the ref docs, because they aren't exported in the index.ts.

**Comment by wangela** [comment]
These all follow the same pattern demonstrated in the README on [GitHub,](https://github.com/googlemaps/google-maps-services-js), NPM, and in [the docs](https://googlemaps.github.io/google-maps-services-js/#quick-start). That example plus an inspection of the supported params provides the necessary information to form a working request.
