### ISSUE TITLE
Compatibility of back-end and front-end directions services

### ISSUE THREAD

**Issue by tim-rohrer** [googlemaps/google-maps-services-js#464]
I wrote a server using this lib because I assumed (you know how that goes) that the results produced would be compatible with the front-end, meaning I could take a directions results and provide these routes to the front end for mapping. Now, if I understand this linked issue and comment correctly, that isn't possible without trying to duplicate the functions Google (front-end javascript) has on the `bounds` element of DirectionsResult?

BTW, I discovered this potential issue when I got a Typescript error trying to add the results from my server to the Redux slice I have for my app. So I'm not sure the solutions in the linked issue are germane for me? Or maybe I don't understand. 

Does anyone have a link to example code where someone has patched the back-end data with the rest of the methods on `LatLngBounds`?

I realize I may be looking at two different issues here, so I welcome help in understanding how to proceed.

Thanks.

=======
The front-end and back-end services aren't intended to work together in the way you're trying to do. 

At a guess you might be able to manually patch the back-end route data with the missing attributes that the front-end API expects.

_Originally posted by @stephenmcd in https://github.com/googlemaps/google-maps-services-js/issues/161#issuecomment-390554207_

**Comment by jpoehnelt** [comment]
There are definitely challenges here. For example, `LatLng` obects vs `LatLngLiteral`s correspondingly returned by the frontend vs backend interfaces. There are also cases where the returned value is enhanced in other ways. 

It should be possible to translate most of these, especially given the typings. This patching would need to occur on the client.

**Comment by tim-rohrer** [comment]
@jpoehnelt,  I decided to rewrite using the Google Maps Javascript v3 API for this project, but I can still see future applications where this ability would be handy.
