### ISSUE TITLE
Expose AutoCompleteSessionToken Endpoint

### ISSUE THREAD

**Issue by jlukic** [googlemaps/google-maps-services-js#470]
Currently [placeDetails](https://googlemaps.github.io/google-maps-services-js/modules/_places_autocomplete_.html) endpoint takes as a param `sessionToken`, but does not expose any way of generating a session token. 

It'd be really nice if there was an endpoint in this library that let you generate a session token to use with this endpoint, as this can be a huge cost-savings for per-session billing.

For example in the clientside gmaps js library there is 
```javascript
google.maps.places.AutocompleteSessionToken()
```

https://developers.google.com/places/web-service/session-tokens

**Comment by jpoehnelt** [comment]
There are many ways to generate a sessionToken, but it is up to the application to manage its storage. I don't see the benefit in adding this at this time. You may want to check out https://www.npmjs.com/package/uuid.

```
import { v4 as uuidv4 } from 'uuid';
let sessionToken = uuidv4();
```
