### ISSUE TITLE
[TypeScript] Axios 0.20 Error in their Typings which Google-Maps-Services-JS depends on. Cannot find name ProgressEvent

### ISSUE THREAD

**Issue by pratikpc** [googlemaps/google-maps-services-js#480]
Thanks for stopping by to let us know something could be better!

Please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
Maps API
2. OS type and version
Windows 10 although I believe the issue is Platform Agnostic
3. Library version and other environment information
Latest
NodeJS Latest
Axios Google's
TypeScript Latest
#### Steps to reproduce

  1. Create a TypeScript based Node.JS Project
  2. Add Latest GoogleMaps API as dependency
  3. Do not add dependency on DOM in Libs in tsconfig.json
  4. (Edit) Add ES6,ES2015,16,17... etc to tsconfig as libs  
  ```json
"lib": [ "ES6" ] 
  ```
  5. Run tsc

#### Code example

Most basic code, Issue Lies with Axios Typings in 0.20.0

#### Stack trace
```js
node_modules/@googlemaps/google-maps-services-js/node_modules/axios/index.d.ts:63:40 - error TS2304: Cannot find name 'ProgressEvent'.

63   onDownloadProgress?: (progressEvent: ProgressEvent) => void;
```
Caused by

[Updating to Axios 0.20.0](https://github.com/googlemaps/google-maps-services-js/pull/456)

[Related issue in Axios](https://github.com/axios/axios/issues/3219)

How to Solve?

Fix version to 3.1.7 as a user which was the last unaffected version "@googlemaps/google-maps-services-js": "3.1.7",

I am not sure if downgrading Axios versions would be possible for Google but it could serve as a nice solution till the release of the version of Axios without this issue

[(Code with issue present)](https://github.com/pratikpc/google-maps-javascript-axios-issue)

**Comment by jpoehnelt** [comment]
Thanks for reporting. The default libs in TypeScript compiler options is a bit of a gotcha. Fix should be released shortly.

**Comment by pratikpc** [comment]
@jpoehnelt fix works  
Thanks!
