### ISSUE TITLE
Error while parsing 'fields' parameter: Unsupported field name 'utc_offset_minutes'. 

### ISSUE THREAD

**Issue by weilinzung** [googlemaps/google-maps-services-js#483]
Try to switch from `utc_offset` to `utc_offset_minutes`, but we are getting this error: `Error while parsing 'fields' parameter: Unsupported field name 'utc_offset_minutes'.`.

```
mapsClient.placeDetails({
 params: {
  fields: ['name', 'utc_offset_minutes' 'opening_hours']
 }
})
```

Thanks!

**Comment by jpoehnelt** [comment]
`utc_offset_minutes` and its deprecation is only applicable to the Web JS API as far as I am aware.

**Comment by weilinzung** [comment]
@jpoehnelt ok.

Can you give us a bit more detail on how this nodejs lib is using rather than below?

https://maps.googleapis.com/maps/api/place/details/json?fields=place_id,geometry,address_components,formatted_address,name,photo,utc_offset_minutes,website,opening_hours,website,rating,user_ratings_total&key=`${api-key}`&place_id=ChIJQ87td3bT1IkR2dvU6bXCHHE%27

Thanks!
