### ISSUE TITLE
Client geocode doesn't find Nordgrønland, Groenlandia

### ISSUE THREAD

**Issue by VictorioMolina** [googlemaps/google-maps-services-js#484]
Hello,

I am validating locations in my server using your API and I have an error when trying to validate "Nordgrønland, Groenlandia" using the client geocode. For other places, everything works fine.

This is my function:

```
exports.placeExists = async function (place) {
  /* This function gets the name of a place and check if exists */

  const params = {
    address: place,
    key: googleMapsServiceAccount.key,
  };

  const response = await client.geocode({
    params,
  });

  return response.data.status === "OK";
};
```

Just try it like this:

```
  const myPlace = "Nordgrønland, Groenlandia"; 
  const myPlaceExists = await placeExists(myPlace);
  console.log(myPlaceExists); 
```

**Comment by VictorioMolina** [comment]
I don't know if this is happening because of the "ø" character, but I would really appreciate your feedback.

**Comment by jpoehnelt** [comment]
Have you tried making this request outside of the client library using the HTTP calls?

**Comment by VictorioMolina** [comment]
Okey, I have tried this and not found. Sorry.

**Comment by jpoehnelt** [comment]
If you still think this is in error, please submit a ticket at https://issuetracker.google.com/issues/new?component=188871&template=788905.
