### ISSUE TITLE
[fixed, no bug] No response place details

### ISSUE THREAD

**Issue by matthijsdewit** [googlemaps/google-maps-services-js#49]
When requesting details for a place using: 

`
const googleMapsClient = require('@google/maps').createClient(
    {
        key: '[my key]'
    }
)
## `

`
const googleMapsClientplace = googleMapsClient.place({
                        placeid: 'fbd360e5d31edc4b889f19daa70cf802f483f0a2'
                    }, function(err, response) {
                        if (!err) {
                            const details = response.json.results;
                            console.log('place details: ' + details)
                            reply.view('location', {
                                details: details
                            })
                        }
                    });
`

Whatever the placeid I declare, no response is returned. 

Doing a places search however, does return a results list:
`const gPlaceslookup = googleMapsClient.places({
                        query: 'supermarket',
                        location: locatie
                    }, function(err, response) {
                        if (!err) {
                            const locations = response.json.results;
                            console.log(response.json.results);
                            reply.view('index', {
                                locations: locations
                            })
                        }
                    });`

What seems to be going on here?

EDIT: my bad, it was a conflict in hapi. 

Edit 2: the keen observer noticed I used this for the place response:
`const details = response.json.results;`

This shouldn't be plural, but just

`const details = response.json.result;`

**Comment by stephenfarrar** [comment]
I don't believe that `fbd360e5d31edc4b889f19daa70cf802f483f0a2` is a valid place ID.

Place IDs usually begin with `Ch`. See https://developers.google.com/places/place-id
