### ISSUE TITLE
Provide DirectionsStep.path prop in the NodeJS client.

### ISSUE THREAD

**Issue by Jeandcc** [googlemaps/google-maps-services-js#490]
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**
I'm frustrated because this is something that exists in the client library and there's no reason for it to not exist in the Server Library as well. I need the "path" property to be available to a "DirectionStep" after making a request to the Directions API.

JS Client Interface (contains path): https://developers.google.com/maps/documentation/javascript/directions#Steps
Directions API Interface (doesn't contain path): https://developers.google.com/maps/documentation/directions/overview#Steps

 **Describe the solution you'd like**
Provide the "path" property inside each step. after a successful call to the Directions API.

 **Describe alternatives you've considered**
I'm currently generating my coordinates array by iterating through all the end locations of the route. That's not ideal since a road/step can be curved and connecting the start and end locations might not produce an accurate line over the road.

![image](https://user-images.githubusercontent.com/47673012/95784058-79f46c00-0ca9-11eb-97bd-bd19dabab888.png)

**Comment by jpoehnelt** [comment]
Having looked at the internal implementation, the difference is that it uses the encoded polyline and not the start and end locations.

**Comment by Jeandcc** [comment]
Hey @jpoehnelt , thanks for commenting on this matter. 

I was expecting both libraries to have very similar functionality. It's hard to think of why that difference exists. 

You can see the difference between both methods with these two images:

![image](https://user-images.githubusercontent.com/47673012/95785459-2cc5c980-0cac-11eb-9cfd-2ef8fd528833.png)
This one used the client-side (JS) library

![image](https://user-images.githubusercontent.com/47673012/95785528-5121a600-0cac-11eb-9efb-2d377436710d.png)
This one used the start and end_location from the snippet above

Do you see the reason why I'm not happy with the workaround? Do you think it's possible to add it or would it involve a great deal of development to make that "small" addition?

**Comment by jpoehnelt** [comment]
The start and end location method is obviously incorrect and that is expected. 

Some pseudocode:

```
for leg in legs
  for step in leg.steps
     step.path = decode(step.polyline.points)
     routelocations.push(step.path)

routlocations.flat()
```

**Comment by Jeandcc** [comment]
Hey @jpoehnelt , thanks for that! 

Decoding polylines indeed seems like the best way to go. I'll close this issue, but I still believe that the "path field" should be available in the NodeJS the same way it is in JS (if it's not a big hassle to make that happen). 

Thanks for your comments! 

Have a good day

**Comment by jpoehnelt** [comment]
I recently published https://www.npmjs.com/package/@googlemaps/polyline-codec which might help here.
