### ISSUE TITLE
This package needs a quick way to test the validity of an API key

### ISSUE THREAD

**Issue by 333one** [googlemaps/google-maps-services-js#507]
**Is your feature request related to a problem? Please describe.**
This package needs a quick/easy way to test the developers API key.  This will save devs countless hours.

 **Describe the solution you'd like**
Something like this,
`client.testConnection({key: process.env.GOOGLE_MAPS_API_KEY});`

 **Describe alternatives you've considered**
From my Windows desktop I tried the example code below but received a 403 error.  However I'm not entirely certain if the problem is my key,  the fact I didn't include an axiosInstance or something else.  From my Google control panel the key currently has no application or API restrictions.

```
const client = new Client({});

client
  .elevation({
    params: {
      locations: [{ lat: 45, lng: -110 }],
      key: process.env.GOOGLE_MAPS_API_KEY
    },
    timeout: 1000 // milliseconds
  }, axiosInstance)
  .then(r => {
    console.log(r.data.results[0].elevation);
  })
  .catch(e => {
    console.log(e);
  });
```

**Comment by jpoehnelt** [comment]
The information is already there, https://github.com/axios/axios#handling-errors. For example, https://maps.googleapis.com/maps/api/elevation/json?key=1234&locations=50,50 returns:

```
{
   "error_message" : "The provided API key is invalid.",
   "results" : [],
   "status" : "REQUEST_DENIED"
}
```

**Comment by 333one** [comment]
I can retrieve an error message but 403 can mean multiple things,  

`{"time":"11/17/2020, 2:04:48 PM","level":"error","message":"Request failed with status code 403"}`

[](https://developers.google.com/maps/documentation/geocoding/get-api-key#troubleshooting-authentication-issues)
_If your request is malformed or supplies an invalid signature, the Geocoding API returns an HTTP 403 (Forbidden) error._

**Comment by jpoehnelt** [comment]
And the body of the response should have more information for most of these.

```js
.catch(e => {
    console.log(e.response);
  })
```

**Comment by 333one** [comment]
Actually you are correct.  I dug a couple layers down to `response.data.error_reponse` and found this, "This API project is not authorized to use this API."

Thank you!
