### ISSUE TITLE
How to create static map?

### ISSUE THREAD

**Issue by mathishuettl** [googlemaps/google-maps-services-js#51]
Hello,

how can I make a static map with this package?
Like in this example from Google: https://developers.google.com/maps/documentation/javascript/examples/map-simple?hl=de

**Comment by stephenmcd** [comment]
It's unrelated to this library, but you can see how to here:

https://developers.google.com/maps/documentation/static-maps/intro

**Comment by grant** [comment]
Is there a library that does make static maps?
I think this issue should be converted to a feature request.

With support for these query parameters:
https://developers.google.com/maps/documentation/maps-static/intro

i.e. 
```js
await maps.static({
    center: ...,
    zoom: 10,
    size: '600x400'
    ...
})
```
