### ISSUE TITLE
Can't find module

### ISSUE THREAD

**Issue by mandysimon88** [googlemaps/google-maps-services-js#52]
As you can see, the package is installed to node_modules, yet, require can't find it.

NPM version: 3.8.3

![screen shot 2016-10-31 at 1 54 36 pm](https://cloud.githubusercontent.com/assets/12855692/19865219/ab1887c0-9f71-11e6-93cb-f9e159466dfb.png)

**Comment by yellowbang** [comment]
same problem

**Comment by sudharsanmit** [comment]
Ditto. I am using typescript though. I installed the typings but don't know how to make it work.

**Comment by franknwankwo** [comment]
same issue here, installed @types and I'm using typscript /Angular 2

**Comment by milesibastos** [comment]
Any update?
I have the same problem on react-native app...
![screen shot 2017-01-12 at 14 59 55](https://cloud.githubusercontent.com/assets/55114/21899583/e0c88128-d8d7-11e6-9305-25a7d5a3a3b1.png)

**Comment by stephenmcd** [comment]
Three entirely separate issues are mentioned here, and they're all duplicates:

Installation / NPM issue: #42 
Typescript support: #50 
Reactive Native support: #63
