### ISSUE TITLE
"use strict" errors are suppressed

### ISSUE THREAD

**Issue by schongo** [googlemaps/google-maps-services-js#53]
When I use the library in Node and do something like

```
"use strict";
googleMapsClient.geocode({ address: 'Sesame Street 1' }, function(err, result) {
   raise_ReferenceError = true;
});
```

the ReferenceError that would normally be raised is caught by the Maps Lib. This is very annoying because it hides errors that are explicitly requested by "use strict". Maybe I get some fundamental point wrong here but right now I think the error handling of the maps module should detect "use strict" errors and throw them.

**Comment by stephenfarrar** [comment]
That's bad!

This actually has nothing to do with "use strict". Any exceptions thrown by the callback are caught.

Why? Because this is what Promises do.
Is it surprising and unhelpful? Yes.
What can you do? If you use Promises, then you can get a hold of the error.

```
googleMapsClient.geocode({ address: 'Sesame Street 1' })
    .asPromise()
    .then(function(result) {
        raise_ReferenceError = true;
    })
    .catch(function(err) {
        // Throw the error outside the Promise, or log it, or something.
        process.nextTick(function() { throw err; });
    });
```
