### ISSUE TITLE
Retrying on 'OVER_QUERY_LIMIT' obfuscates errors

### ISSUE THREAD

**Issue by migueloller** [googlemaps/google-maps-services-js#55]
I had a major issue with our product today when all of our app's requests were timing out and we couldn't figure out why.

After fixing the issue and looking for the root cause, we pinpointed it down to the fact that if the request results in a `OVER_QUERY_LIMIT` error, this library will keep trying to make a request until it doesn't result in an error or it times out (at 60 seconds). Because our routing mechanism timed out at 30 seconds, this library never showed an error and the request simply timed out silently, even though Google's API was getting blasted with retries.

Given that it is extremely likely that if an `OVER_QUERY_LIMIT` response is returned it will be most likely returned again within the 60 second timeout window, would it be sensible to not try to make the request again?

[This](https://github.com/googlemaps/google-maps-services-js/blob/master/lib/internal/make-api-call.js#L100) is the line in question.

**Comment by wolleysesom** [comment]
I would also like OVER_QUERY_LIMIT response returned immediately without retrying

**Comment by jigarunjha** [comment]
Is there any way to set the QPS limit as i have a premium subscription of Google Maps for Some of the paid API and want to utilize my spendings.

**Comment by priidikvaikla** [comment]
@jigarunjha You can set the limit with the rate.limit option: https://github.com/googlemaps/google-maps-services-js/blob/master/lib/internal/make-api-call.js#L29

**Comment by justinrouleau** [comment]
I would just like to reiterate that `OVER_QUERY_LIMIT` needs to throw immediately without retrying and then eventually resulting in a timeout. It's very unlikely that retrying would result in a success before timing out.

Also, the timeouts really should return some sort of error summary so we have an idea what's causing the timeout.

Thanks.
