### ISSUE TITLE
Add key rotation support for Google maps browser keys

### ISSUE THREAD

**Issue by bacloud14** [googlemaps/google-maps-services-js#551]
There is domain and API restrictions already described [here](https://developers.google.com/maps/documentation/javascript/get-api-key) . It seems fine and 100% secure.

If we want to enforce Google maps serving on browsers, I think it is easy and better to set key rotation. In such case, webmaster would choose (optional) to rotate the active key by any logic on server side (like per user session, time period or both).
He can also limit user access on Google Map which is not possible I believe now (per user usage limit).

It helps setting a user / session / time window specific limit.

Thanks!

**Comment by bacloud14** [comment]
I forgot to mention, a function rotate() needs to be called in webmaster's server side. It needs to be part of maps API. It sets a new key and returns it.

**Comment by jpoehnelt** [comment]
It is definitely beneficial to rotate keys. Given that this is a server side library to run in nodejs, it is not as applicable. I am going to close for this reason.
