### ISSUE TITLE
SSL Error: Self signed certificate in certificate chain

### ISSUE THREAD

**Issue by udit2910** [googlemaps/google-maps-services-js#554]
I'm getting this error while trying to get response from distancematrix API. you can see error in below image.
![error](https://user-images.githubusercontent.com/43945526/106441230-cef9ff00-649f-11eb-9ba8-99ccab97ba54.PNG)

---
We tried their Standalone API as well. It is also giving the same error. but, after disabling the SSL certificate verification we can get proper response. Please see below images for reference. 
![map_error](https://user-images.githubusercontent.com/43945526/106441082-9ce89d00-649f-11eb-8b38-8db7123487d8.PNG)
![mapResp](https://user-images.githubusercontent.com/43945526/106441091-9eb26080-649f-11eb-8878-d9a12d042212.PNG)

**Comment by jpoehnelt** [comment]
This is likely due to a proxy being used or a compromised system/network. Closing as there is nothing to do here.
