### ISSUE TITLE
Does placeAutocomplete have setFields?

### ISSUE THREAD

**Issue by mtergel** [googlemaps/google-maps-services-js#566]
Hello,
It says on the [docs](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete#maps_places_autocomplete-typescript) here. 

```
  // Avoid paying for data that you don't need by restricting the set of
  // place fields that are returned to just the address components.
  autocomplete.setFields(["address_component"]);
```
Is this field only related to the Places Autocomplete Widget or do I have to add this to placeAutocomplete if so how do I add it?

**Comment by jpoehnelt** [comment]
You can try passing 'fields` to the request. Looks like it isn't in https://github.com/googlemaps/google-maps-services-js/blob/master/src/places/autocomplete.ts#L58, but that might be a mistake. Please report back here if it works for you.

**Comment by jpoehnelt** [comment]
https://github.com/googlemaps/google-maps-services-js/blob/master/e2e/places/findplacefromtext.test.ts#L26 is an example of using fields with a different api.

**Comment by mtergel** [comment]
Thanks for the quick reply, it works STATUS: 200 OK
`        //@ts-ignore
        fields: ["place_id", "name", "formatted_address"]
`

**Comment by jpoehnelt** [comment]
Thanks for trying it out. I'll update the request object.

**Comment by mtergel** [comment]
But what does it actually supposed to do though?
I'm getting the same fields in the predictions array.

**Comment by jpoehnelt** [comment]
Maybe it gets ignored then. I'll do some more testing.

**Comment by jpoehnelt** [comment]
Ok, figured it out. The reason the fields param doesn't work on this is that it doesn't actually return the place fields at all, just the fields asociated with the lookup.

```
"description",
"matched_substrings",
"place_id",
"reference",
"structured_formatting",
"terms",
"types",
```

**Comment by mtergel** [comment]
Ok, so for someone who is using this method just for autocomplete I don't have to worry about fields right?

Place Search, Nearby Search, and Text Search requests all return a subset of the fields that are returned by Place Details requests.

**Comment by jpoehnelt** [comment]
> Ok, so for someone who is using this method just for autocomplete I don't have to worry about fields right?

Correct.

> Place Search, Nearby Search, and Text Search requests all return a subset of the fields that are returned by Place Details requests.

If specified with fields, yes.

**Comment by mtergel** [comment]
Thanks I'll close this now :)
