### ISSUE TITLE
Is there any API I could get if a point(lat, lng) exists inside a location i.e Kormangala, HSR Layout, Bengaluru India?

### ISSUE THREAD

**Issue by sujeet-agrahari** [googlemaps/google-maps-services-js#578]
Currently I am doing circular matching to suggest a user a location.

Let's say there are five location, so I take center of those five locations and I get the distance from user's current location (lat, lng).

Then, I sort them by ascending order to get the nearest location.

I need the exact location now i.e. If a user falls within a given location or not.

![image](https://user-images.githubusercontent.com/22151975/110588731-7521de80-819b-11eb-92fa-4e87527ad4d3.png)

What I can possible do is to get polygon coordinates of the above location and using contains location method I could get the result.

If I get more points for the polygon, the result will be more accurate.

 _How can I get the polygon of the above area?_

But if there is some API in google map that I can use to check if a user is within a location. That would be much better.

**Comment by jpoehnelt** [comment]
There are three options that I can think of:

1. Use https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API
2. Use similar functionality in mobile app.
3. Use Google Maps Geolocation API which uses one of IP, cell tower, or wifi mac addresses. This is likely to be the least accurate.

**Comment by sujeet-agrahari** [comment]
@jabelone Thanks, Is there any equivalent method for `[containsLocation()](https://developers.google.com/maps/documentation/javascript/examples/poly-containsLocation)` in node.js library?

**Comment by jpoehnelt** [comment]
You can probably use something like https://github.com/Turfjs/turf/tree/master/packages/turf-points-within-polygon (I have never used this library).

**Comment by sujeet-agrahari** [comment]
So, with help google map nodejs library I cannot achieve that? I am closing the issue. If you have additional info please reopen.

**Comment by techgerm** [comment]
You can also use https://github.com/Turfjs/turf/tree/master/packages/turf-boolean-point-in-polygon if you simply need to check if one point is within the boundaries of a polygon (that's what I ended up using for my project).
