### ISSUE TITLE
Support for default service account credentials within GCP

### ISSUE THREAD

**Issue by mbyrne00** [googlemaps/google-maps-services-js#587]
**Is your feature request related to a problem? Please describe.**
When making a request for `placeAutoComplete` the `params` portion of the request requires a `key` to be supplied as one of the properties. The `@google-cloud` libraries support zero-config defaulting to use the default service account credentials, removing the need for explicit api key config.

This works in app engine, google cloud functions for example.

 **Describe the solution you'd like**
Fall back to using default GCP service account credentials. `<project-id>@appspot.gserviceaccount.com`.

 **Describe alternatives you've considered**
This can be worked around by passing the `key` in every request meantime.

 **Additional context**

**Comment by mrowles** [comment]
This would be great, we're using the same auth for Firebase + Google Calendar atm.

**Comment by jpoehnelt** [comment]
I agree this would be great! I've been pushing for this internally for nearly two years now. There is a ton of technical debt in the way unfortunately.

Please create some a feature request for this at https://developers.google.com/maps/support#issue_tracker and post the link here.

**Comment by mrowles** [comment]
Isn't that was this is issue tracker is for? :P Send them this link, let 'em know at least 3 people in the world are keen.

**Comment by jpoehnelt** [comment]
It's always better if it comes from a customer. I can then help escalate with additional references.

**Comment by mrowles** [comment]
@jpoehnelt Done: https://issuetracker.google.com/issues/199304064

**Comment by mbyrne00** [comment]
Well that didn’t take long to get rejected :). At least they were quick to get back

**Comment by jpoehnelt** [comment]
Yeah, I know 😅 . 

I don't have write access to that particular issue but am fixing and linking to some other issues.

**Comment by mrowles** [comment]
Ha, oh well. The tech debt from Google Maps must be really bad!

I think it was initially built in Sydney, so for that I apologise on behalf
of Aussies for the code that has now come back to bite us 🥲

**Comment by jpoehnelt** [comment]
Going to close this as the path forward is to provide new APIs built with more modern infrastructure. These APIs will have client libraries matching the pattern used by GCP APIs.

**Comment by mrowles** [comment]
@jpoehnelt erm, but it’s not been done yet. Shouldn’t this stay open until it’s done?

**Comment by jpoehnelt** [comment]
There is no work to be done here in this library. It's not possible with the APIs used by this library. 

New versions of the APIs are being created that will enable service accounts. The feature request you opened has active work that will not be part of this particular library and instead replace it with autogenerated libraries similar to cloud APIs.

**Comment by mbyrne00** [comment]
Sounds promising. Can you please provide links to any issues/resources from this issue so that people will know where to look to keep updated on progress of new libs.

**Comment by jpoehnelt** [comment]
It will be announced through many of the normal channels. I suggest following https://cloud.google.com/blog/products/maps-platform.
