### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by sudharsanmit** [googlemaps/google-maps-services-js#59]
CORS error with a distancematrix request. But geocoder request works fine. What am I missing?

Fetch API cannot load https://maps.googleapis.com/maps/api/distancematrix/json?destinations=New%2…%20Lake%20City%2C%20UT%2084116&key=AIzaSyAaXJs0ZDx3rjhxrsjUO6pT7WU2yNI. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by sudharsanmit** [comment]
This is how I made the request. I am using ionic.

This works -
```
      googleMapClient.geocode({
         address: '1600 Amphitheatre Parkway, Mountain View, CA'
       }, function(err, response) {
         if (!err) {
           console.log(response.json.results);
         }
       });


```

This fails - 
```
      googleMapClient.distanceMatrix({
          origins:['152 **** Terrace, Salt Lake City, UT 84116'],
          destinations:['255 ***** Rd, UT 84116','Las Vegas, USA','New York, USA', 'Washington DC, USA']
      }, function(err, response) {
         if (!err) {
           console.log(response.json.results);
         }
       });
```

**Comment by sudharsanmit** [comment]
I worked through proxy though. Just wanted to understand the difference in behaviour...

**Comment by jamieshark** [comment]
I'm also experiencing this issue. Since most times the response would be read-only, is it possible to add a `no-cors` param to the request? or open up request options as an argument?

**Comment by collink** [comment]
Same exact issue here.  `geocode()` works flawlessly, but `directions()` barks a CORS error.

**Comment by stephenmcd** [comment]
Does this error occur server-side or client-side? My guess is you're trying to use this library client-side, which it's not intended for. For client-side directions, please see the JavaScript API: https://developers.google.com/maps/documentation/javascript/directions

**Comment by petersandor** [comment]
Also experiencing this issue, but on `placesAutoComplete()` API, `geocode()` works. Using both in the browser, so why the inconsistent result?

**Comment by LeoAref** [comment]
@stephenmcd Is that possible to make it working client-side as well?

**Comment by holotrek** [comment]
I'm very confused by this answer. There's nothing in the [Distance Matrix API documentation](https://developers.google.com/maps/documentation/javascript/distancematrix) that indicates that it should be restricted to server-side calls. In fact in the blue box at the top, it literally says "This page describes the **_client-side_** service available with the Google Maps JavaScript API". What do you mean client-side is not what it's "intended for"?

I suppose the Directions API will be sufficient, but I agree with LeoAref that Distance Matrix should also be supported, as consistency would be appreciated.

Thank you for your work on this library!

**Comment by mikegarite** [comment]
@mbylstra - thanks for that - saved me a lot of time.

**Comment by oyewodayo** [comment]
If you're still experiencing this error, download this extension and enable CORS 
[https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en)

**Comment by AlastairTaft** [comment]
@mbylstra I agree with your points but is that really it? There's no way to make it work. On the places documentation it states at the top 'Note: Server-side and client-side libraries', which leads you to believe it should work on client-side libraries. I'm wondering how they make it work on their client side library. 

I really don't want to use their abstraction client libs, and I don't think I even can with React-Native, very frustrating experience.

**Comment by raj-2011503554** [comment]
Hi All 
In our application we are using the google map api 
When Cross-Origin-Embedder-policy set to require-corp and Cross-orgin-Opener-policy set to require-corp 

Google map places Api and satellite mode images are not loading 
Please help !!!
<img width="924" alt="SatelliteImageLoadingFailed" src="https://user-images.githubusercontent.com/78357842/134338555-7d089a49-80bf-4d08-a5c5-164d0f0d9a15.PNG">

<img width="956" alt="AutoCompletionServiceFailing" src="https://user-images.githubusercontent.com/78357842/134338435-2002feb7-8d3b-4741-af14-d16164347dde.PNG">
