### ISSUE TITLE
Waypoints are not considered while calculating route

### ISSUE THREAD

**Issue by kuljeetgvirk288** [googlemaps/google-maps-services-js#591]
Trying to use waypoints of direction route service. But, it is giving the same route(default route as shown in Google Maps) irrespective of the waypoints mentioned in the params.

![Screenshot 2021-04-02 at 6 11 47 PM](https://user-images.githubusercontent.com/81812477/113416426-f0fbf900-93de-11eb-9428-ac452f5894ec.png)

Thanks!

**Comment by jpoehnelt** [comment]
Please open in the issue tracker if it is still a problem. https://developers.google.com/maps/support#issue_tracker
