### ISSUE TITLE
Set request user-agent and Accept-Encoding headers cause error

### ISSUE THREAD

**Issue by AhmadPirzargar** [googlemaps/google-maps-services-js#595]
Since request has "user-agent" and "Accept-Encoding" header in browser cause below errors:
 **Refused to set unsafe header "User-Agent"
 Refused to set unsafe header "Accept-Encoding"**
 Because these headers must be filled by the browser.

**Comment by jpoehnelt** [comment]
This library is not for usage in the browser. 
![Screenshot 2021-04-27 9 32 35 AM](https://user-images.githubusercontent.com/3392975/116269500-83bc5900-a73b-11eb-859d-0d89045f50f2.png)

See https://developers.google.com/maps/documentation/javascript/.
