### ISSUE TITLE
Ranking by proximity Next Js

### ISSUE THREAD

**Issue by fullstackslayer** [googlemaps/google-maps-services-js#596]
So I have a next js application, and my use case is I want to allow users to choose their location and then I want to allow users to make "posts" with a particular location as well. When a user goes to their "feed" they should see these posts sorted by how close their location is from the user's location. 
Hope someone can help me out here.

**Comment by jpoehnelt** [comment]
The https://googlemaps.github.io/google-maps-services-js/classes/client.html#distancematrix distance matrix api can be used for this. I recommend using Stackoverflow or silar for questiosn like this.
