### ISSUE TITLE
Language codes

### ISSUE THREAD

**Issue by sudharsanmit** [googlemaps/google-maps-services-js#60]
Where can I get the language codes ("en", "fr", etc) supported by google maps if I want to use them in direction services api?

**Comment by sudharsanmit** [comment]
Menu of google maps (74 languages) - ![image](https://cloud.githubusercontent.com/assets/16746593/21026234/f440adde-bd48-11e6-800e-7c90e4b8d66b.png)

Google developer site (52 languages) - https://developers.google.com/maps/faq#languagesupport

Google supported (149 languages) -
https://sites.google.com/site/tomihasa/google-language-codes

Which one is right?

**Comment by stephenmcd** [comment]
https://developers.google.com/maps/faq#languagesupport
