### ISSUE TITLE
Is multilanguage support planned?

### ISSUE THREAD

**Issue by Isanderthul** [googlemaps/google-maps-services-js#61]
Is there any plan to support localization? 
such as passing the localization in the constructor, http://stackoverflow.com/questions/14815192/setting-language-for-reverse-geocoding-gmaps-v-3

**Comment by stephenmcd** [comment]
Added in 401f02060b8e8f57af14211376f65d8853bf7b66

**Comment by diegohaz** [comment]
Hey, @stephenmcd. Could you please publish that?
