### ISSUE TITLE
Query: More than 10 photos placesPhoto api?

### ISSUE THREAD

**Issue by sudharsanmit** [googlemaps/google-maps-services-js#62]
How to get more than 10 photos from placesPhoto api? Currently, the places api returns an array of 10 photos. Is there a way to page for the next set of 10 photos?

**Comment by sudharsanmit** [comment]
Especially for accessing the photos of Google Business listed ones? Google business provides a photo manager to add/manage photos but the same can't be accessed through API. I referred the original API documentation, I saw the same 10 as the limit.

**Comment by piercefreeman** [comment]
Wondering the same thing about Google Business listed images

**Comment by sudharsanmit** [comment]
Crazy thing is google promotes it so much and encourages businesses to get
listed and not giving opportunity to access content through API.

On Saturday, December 31, 2016, Pierce Freeman <notifications@github.com>
wrote:
> Wondering the same thing about Google Business listed images
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/btLIHA1ejgJGkDDi6n6n0r1c6QqT5bie0Zc0Wq2gaLy11VCv0fp59nGExEPQg3B-E-gubflZ14ulJzjQMDInxYj4NZp5It8RVqUAVbynj_Ufs80qO8QodKk7JdMpg2qjcmxCTSD4PWfK6SpcHnKVBRWeHFhdTQ=s0-d-e1-ft#https://github.com/notifications/beacon/AP-IYXFFKPxzZdtDeOLwW124zl9Fmpu9ks5rNsIngaJpZM4LRg8S.gif>

**Comment by stephenmcd** [comment]
This currently isn't supported by the API, and this issue tracker is for the Node.js client library, not the API itself, so this isn't the correct channel.

I've opened a feature request on the issue tracker for the Places API:

https://code.google.com/p/gmaps-api-issues/issues/detail?id=11198

Please star the issue and subscribe to it to track its progress.

**Comment by sudharsanmit** [comment]
Thank you @stephenmcd
