### ISSUE TITLE
Compatibility with React Native?

### ISSUE THREAD

**Issue by joncursi** [googlemaps/google-maps-services-js#63]
Would love to be able to use this library within React Native, as I use this already in a complimentary React web-based app, however RN has more specific networking requirements: https://facebook.github.io/react-native/docs/network.html

This results in dependency issues that I can't seem to get past:

![screen shot 2017-01-06 at 7 41 09 pm](https://cloud.githubusercontent.com/assets/4974609/21737577/2b3a96e0-d448-11e6-858d-6882a65b60a0.png)

**Comment by stephenmcd** [comment]
One note on this - using the web services from a mobile device is highly discouraged, as it exposes your unrestricted API key to malicious users.

**Comment by joncursi** [comment]
@stephenmcd Indeed, it is not a perfect solution. I am using [react-native-config](https://github.com/luggit/react-native-config) to manage keys the best I can, but they still get bundled with the app and could get reverse engineered out I suppose.

Is there a better way to call these APIs from a React Native app?

**Comment by stephenmcd** [comment]
Best approach is a server-side component that acts as a proxy between devices and third-party APIs such as maps.

**Comment by stephenmcd** [comment]
I'll close this for now - we could probably get it working by swapping out `https` with `fetch`, but doing so would encourage insecure practices as mentioned above. You can always fork the library and patch it if you'd like to ignore this.

**Comment by sibelius** [comment]
@stephenmcd are you willing to accept a pull request to make compatible with react-native?

it would make this package https://github.com/FaridSafi/react-native-google-places-autocomplete easier to maintain

**Comment by stephenmcd** [comment]
How would you address the issues I mentioned?

**Comment by sibelius** [comment]
I think it is a good idea to move to `fetch` instead of `https`

making it available in react-native could be a good thing for simple demos

**Comment by iBobik** [comment]
Possible workaround is to use this library only for types, but send requests by anything our environment likes.

This is how I use it in Nitro on edge worker:
```ts
import { defaultUrl, PlaceAutocompleteRequest, PlaceAutocompleteResponseData } from '@googlemaps/google-maps-services-js/dist/places/autocomplete'

const { googleMapsApiKey } = useRuntimeConfig()

export default defineEventHandler<{ query: {
  input: string
  language: string
  sessionToken: string
} }>(async (event) => {
  const { input, language, sessionToken } = getQuery(event)

  try {
    const data = await $fetch<PlaceAutocompleteResponseData>(defaultUrl, {
      query: {
        input,
        language,
        key: googleMapsApiKey,
        sessiontoken: sessionToken,
      } as PlaceAutocompleteRequest['params']
    })
    if (data.status !== 'OK' && data.status !== 'ZERO_RESULTS')
      throw createError({ statusCode: 400, statusMessage: 'Bad Request' })

    return data
  }
  catch (err) {
    console.log(err)
    throw createError({ statusCode: 500, statusMessage: 'Internal Server Error' })
  }
})
```

**Comment by iBobik** [comment]
Btw, on all frontends we need to use proper API key - read only access. It does not matter what client library we use.
