### ISSUE TITLE
provide a [color] param for markers

### ISSUE THREAD

**Issue by Geek-Jokey** [googlemaps/google-maps-services-js#638]
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ** 

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response. 

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/). 

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

 **Is your feature request related to a problem? Please describe.**
I just want to use different color of some markers in my project. 
 [https://developers.google.com/maps/documentation/javascript/custom-markers](https://developers.google.com/maps/documentation/javascript/custom-markers) 
This docs provide [icon] param  to realize this requirement，But I need to provide a lot of icon Pictures.

 **Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/27495489/132444518-83657809-0099-4edf-a03f-1250d73e2d2c.png)
like this api 
![image](https://user-images.githubusercontent.com/27495489/132444634-be5eb576-caba-42d7-882d-5fc1b6042b52.png)

 **Describe alternatives you've considered**

 **Additional context**

**Comment by jpoehnelt** [comment]
Please submit this feature request at https://issuetracker.google.com/issues/new?component=188853&template=787814. This library is for usage in NodeJs.
