### ISSUE TITLE
Support client + signature authentication

### ISSUE THREAD

**Issue by noahw3** [googlemaps/google-maps-services-js#639]
**Is your feature request related to a problem? Please describe.**
From everything that I can tell, this library only supports API key based authentication. However, client + signature based authentication is still an available option on the backing API: https://developers.google.com/maps/premium/authentication/client-id/request-signing

 **Describe the solution you'd like**
Ideally this library would be able to support either key-based auth or client + signature-based auth.

 **Describe alternatives you've considered**
I may be able to resolve this via messing with the underlying Axios code, I haven't tried that. That's not the best developer experience though.

 **Additional context**
I realize that this is a legacy authentication method and API keys are the preferred form. However I'm upgrading an existing application from [an unmaintained googlemaps library](https://github.com/moshen/node-googlemaps) in an attempt to clean things up and address security vulnerabilities. Generating a new key and working out the billing complexities therein would be a nontrivial task, solely upgrading the library without needing to change the actual account information would be ideal.

If nothing else, hopefully this issue will help anyone else who stumbles across this issue, as there didn't appear to be any existing issues open or references to this feature.

I'm also happy to take a stab at opening a PR for this, assuming this is something that isn't intentionally omitted.

**Comment by jpoehnelt** [comment]
Hi @noahw3,

I think if premium plan support is added, it should not be a default option and hidden away. Feel free to post possible designs if you want feedback prior to implementation.

**Comment by noahw3** [comment]
Do you have suggestions for how to "hide" it? My initial thought was to add a union type for RequestParams, since the two authentication methods are mutually exclusive and "key" would need to be omitted from the requests.

Some sort of "enablePremiumPlan" flag could also potentially be passed through on client creation and checked against later to make doubly sure that this option is being explicitly opted into.

**Comment by noahw3** [comment]
@jpoehnelt I've opened a strawman PR to get things rolling, very much open to feedback. https://github.com/googlemaps/google-maps-services-js/pull/640
