### ISSUE TITLE
Is it possible to change the base url?

### ISSUE THREAD

**Issue by zbobyuan** [googlemaps/google-maps-services-js#64]
I need to replace https://maps.googleapis.com with http://maps.google.cn.
My code:

var geocodeApi = require('@google/maps/lib/apis/geocode');
geocodeApi.geocode.url = geocodeApi.geocode.url.replace('maps.googleapis.com', 'maps.google.cn');
geocodeApi.reverseGeocode.url = geocodeApi.reverseGeocode.url.replace('maps.googleapis.com', 'maps.google.cn');
var googleMapsClient = require('@google/maps').createClient({
  key: 'my api key'
});

it works, but looks not an elegant way, is it possible to pass the base url var the options argument?

**Comment by josephfrazier** [comment]
Another approach is to pass a custom [`options.makeUrlRequest`](https://github.com/googlemaps/google-maps-services-js/blob/fafd7541a2c5c425e7c79458e6f9826d6e63977a/lib/internal/make-api-call.js#L32) that changes the URL as needed. For example, the following code allows browser-based usage despite CORS via http://cors-anywhere.herokuapp.com/:

```js
const googleMaps = require('@google/maps')
const makeUrlRequest = require('@google/maps/lib/internal/make-url-request.js')

const googleMapsClient = googleMaps.createClient({
  makeUrlRequest: function (url, onSuccess, onError) {
    const corsProxy = process.env.CORS_PROXY || ''
    return makeUrlRequest(corsProxy + url, onSuccess, onError)
  }
})
```
