### ISSUE TITLE
Places API - Nearby Search keeps returning 400 error

### ISSUE THREAD

**Issue by pnyennhi** [googlemaps/google-maps-services-js#642]
I'm using `placesNearby` and it returns 400 error while `geoCode` method is working fine.
Can you show me which mistake I made or some guides about this `placesNearby` method?

#### Environment details

NodeJS v14.17.0

#### My Code

```javascript
client.placesNearby({
      params: {
        location: {
          "lat": 40.7479343,
          "lng": -73.98856889999999
        },
        type:'restaurant',
        key: GOOGLE_MAPS_API_KEY
      }
    }).then(res => {
      return callback(null, res.data)
    }).catch(err => {
      return callback(err)
    })
```

Thank you!

**Comment by marisancans** [comment]
Hi there, im facing the same issue:

        await client.placesNearby({
            params: {
              location: {latitude: 56.9978375, longitude: 24.161321},
              type: "hospital",
              key: key,
            }
        }).then((r) => {
            res.json(r);
        })
          .catch((e) => {
            res.json("Error occured");
            console.log(e.message);
        });

**Comment by marisancans** [comment]
Solution is to add radius param
