### ISSUE TITLE
Error: Unable to resolve module crypto (React Native)

### ISSUE THREAD

**Issue by Darapsas** [googlemaps/google-maps-services-js#647]
After upgrading from `"@googlemaps/google-maps-services-js": "3.1.16"` -> `"@googlemaps/google-maps-services-js": "3.2.0"` started getting this error:
![20210922_170844](https://user-images.githubusercontent.com/20926795/134359507-df4aefe7-68e0-42fb-9d12-74f5e17e0377.png)

Using `"react-native": "0.65.1"`.

Tried [this](https://github.com/brix/crypto-js/pull/259#issuecomment-799973769), but it didn't help, other solutions involve deprecated packages and for that reason, I won't try them, for now downgrading to `3.1.16` works just fine for me.

**Comment by jpoehnelt** [comment]
@Darapsas let me know if this works for you!

**Comment by Darapsas** [comment]
Tried `3.2.2` today, but no luck:
![20210923_172617](https://user-images.githubusercontent.com/20926795/134526251-65f27615-3142-451e-99c0-654e38342175.png)
Looking a bit deeper, the `crypto` package is empty with a deprecation warning:
![20210923_173056](https://user-images.githubusercontent.com/20926795/134526623-5d791908-366f-4f6d-a8f5-6b2fb01cc561.png)
Tried [rn-nodeify workaround](https://www.npmjs.com/package/rn-nodeify) with the latest `3.2.2`, seems to be working (didn't test it that much, but at least the application starts without errors). Of course, this is a very hacky way, I will try to look for a cleaner solution if it exists, but it will suffice for now.

It would be really cool to see this package use `crypto-js` instead of the core node module - `crypto`, for all the people who use `google-maps-services-js` with client applications (like react-native or other web-applications). All things considered I am pretty sure this is not going to happen, but at least you could add this workaround to the documentation for others to see.
