### ISSUE TITLE
CORS error (No 'Access-Control-Allow-Origin')  while using direction api

### ISSUE THREAD

**Issue by immanojverma2010** [googlemaps/google-maps-services-js#65]
on cli **direction** api is working fine but if i call it from a program it doesn't work. it gives me an error on console of browser.

**# error:**
 Fetch API cannot load https://maps.googleapis.com/maps/api/directions/json?destination=12.9766%2C…origin=12.9097695%2C77.6814536&key=AIzaSyCUJND4EXkdBpb0BTE_TURO1dEAb5PPf8. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
 TypeError: Failed to fetch

**# call-**
var googleMapsClient = require('@google/maps').createClient({
  key: 'AIzaSyCUJND4EXkdBpb0BTE_TURO1dEAb5PPf8'
});

googleMapsClient.directions({
    origin: '12.9097695,77.6814536',
    destination: '12.9766,77.5993',
    
  }, function(err, response) {
    if (!err) {
      console.log(response.json.results);
    }
    else{
      console.log(err);
    }
  });

**Comment by stephenmcd** [comment]
Duplicate #59

**Comment by masadhashmi** [comment]
i want to fuck google very hard, because they developed such a shit. stupids, making technology a fucking job. Fuck you all google developers. fuck your thinking.

**Comment by masadhashmi** [comment]
crazy people, devloped something direction api only supports in their fucking api, fuck you all.. do not providing fucking stupid api support in jquery... fuck you.. Goolge is a Second Microsoft now. fuckk your platforms
