### ISSUE TITLE
Access to Google Maps Javascript Geometry Library?

### ISSUE THREAD

**Issue by PatNeedham** [googlemaps/google-maps-services-js#68]
I'm interested in using the [containsLocation](https://developers.google.com/maps/documentation/javascript/geometry#containsLocation) method of the Google Maps Javascript Geometry Library, but this is more of a general question regarding how to access any of the Google Maps APIs not listed in this project.

I initially tried to use a `require` statement in my Node,js file, using the source url as is listed on the Javascript libraries [Overview page](https://developers.google.com/maps/documentation/javascript/libraries). That didn't work so I then attempted to use node's `vm` module like so:

```
var fs = require("fs")
var http = require("http");
var vm = require('vm')

http.get("http://maps.googleapis.com/maps/api/js?key=my-key&libraries=geometry", function(res) {
  var rawData = "";
  res.on('data', function(data) {
    rawData += data;
  });
  res.on('end', function() {
    vm.runInThisContext(rawData);
  });
});
```

That didn't work either because of `window` not being defined in Node. My next approach was to try and understand how this Node.js client library makes calls to the APIs supported. I looked in the source code under /lib/apis/road.js as an example and it seems like each function belonging to that  API has its own url and configurations used for the `makeUrlRequest` function inside /lib/interal/make-url-request.js. So I attempted to find an equivalent geometry.googleapis.com url inside the Javascript source file but none existed.

How would I be able to make a get/post request (and what url to use) in order to get the same results as the containsLocation function?

**Comment by stephenmcd** [comment]
Sorry about the confusion, but you're conflating the APIs for two different platforms - JavaScript for the web which provides the geometry library, and the Google Maps Web Services which are designed for server-side applications like Node.js. This library is a wrapper for the latter and has nothing to do with the web API.

**Comment by saikiranvadlakonda** [comment]
Hi,

How can we use [containsLocation](https://developers.google.com/maps/documentation/javascript/examples/poly-containsLocation) in nodejs, please suggest.

Thank you.
