### ISSUE TITLE
Add function to sign Image API requests

### ISSUE THREAD

**Issue by rdennett** [googlemaps/google-maps-services-js#688]
**Is your feature request related to a problem? Please describe.**
There is no clear function which allows you to generate signatures for either Static Maps or Static Streetview requests, e.g. what's found at 

https://developers.google.com/maps/documentation/maps-static/get-api-key#apikey-signatures

 **Describe the solution you'd like**
Add a function called createImageAPISignature which takes the URL and the Signing Secret from the Cloud Console

 **Describe alternatives you've considered**
createPremiumPlanSignature does this already, but is not semantically correct.

**Comment by jpoehnelt** [comment]
Solved by https://www.npmjs.com/package/@googlemaps/url-signature.
