### ISSUE TITLE
Wrong place fetched by prediction

### ISSUE THREAD

**Issue by NivMedflyt** [googlemaps/google-maps-services-js#696]
I use in my project angular-google-places-autocomplete directive like this:
`<input type="text" g-places-autocomplete id="address" ng-model="myAddress" autocomplete="nope" force-selection="true" />`

When I type for example "19-15 Seagirt Boulevard" inside I get these predictions as expected:
![image](https://user-images.githubusercontent.com/54893763/139722361-75c1c361-0797-4b9e-b68a-3648ea6161e9.png)
**But when I click** on the first option (19-15 Seagirt Blvd, Far Rockaway, NY 11691, USA), **I get** "26-19 Seagirt Blvd, Far Rockaway, NY 11691, USA" **placed instead**.

When I debugged the library https://github.com/kuhnza/angular-google-places-autocomplete I found that the wrong place is fetched from placesService.getDetails by prediction.place_id:

    function select() {
        var prediction;

        prediction = $scope.predictions[$scope.selected];
        if (!prediction) return;

        if (prediction.is_custom) {
            $scope.$apply(function () {
                $scope.model = prediction.place;
                $scope.$emit('g-places-autocomplete:select', prediction.place);
                $timeout(function () {
                    controller.$viewChangeListeners.forEach(function (fn) { fn(); });
                });
            });
        } else {
            placesService.getDetails({ placeId: prediction.place_id }, function (place, status) { // <--
                if (status == google.maps.places.PlacesServiceStatus.OK) {
                    $scope.$apply(function () {
                        $scope.model = place;
                        $scope.$emit('g-places-autocomplete:select', place);
                        $timeout(function () {
                            controller.$viewChangeListeners.forEach(function (fn) { fn(); });
                        });
                    });
                }
            });
        }

        clearPredictions();
    }

The **prediction** in the **request** that is sent to the function is:
`
{
  description: "19-15 Seagirt Boulevard, Far Rockaway, NY, USA",
  matched_substrings: [
    {
      length: 18,
      offset: 0,
    },
  ],
  place_id: "Ei4xOS0xNSBTZWFnaXJ0IEJvdWxldmFyZCwgRmFyIFJvY2thd2F5LCBOWSwgVVNBIlASTgo0CjIJ1dYwYaVowokRd8-srfeuV5oaHgsQ7sHuoQEaFAoSCQ2Z93WiaMKJEVeWApzy2pjoDBATKhQKEgllPdEurGjCiRFQowvfrORuWw",
  reference: "Ei4xOS0xNSBTZWFnaXJ0IEJvdWxldmFyZCwgRmFyIFJvY2thd2F5LCBOWSwgVVNBIlASTgo0CjIJ1dYwYaVowokRd8-srfeuV5oaHgsQ7sHuoQEaFAoSCQ2Z93WiaMKJEVeWApzy2pjoDBATKhQKEgllPdEurGjCiRFQowvfrORuWw",
  structured_formatting: {
    main_text: "19-15 Seagirt Boulevard",
    main_text_matched_substrings: [
      {
        length: 18,
        offset: 0,
      },
    ],
    secondary_text: "Far Rockaway, NY, USA",
  },
  terms: [
    {
      offset: 0,
      value: "19-15 Seagirt Boulevard",
    },
    {
      offset: 25,
      value: "Far Rockaway",
      $$hashKey: "object:548",
    },
    {
      offset: 39,
      value: "NY",
      $$hashKey: "object:549",
    },
    {
      offset: 43,
      value: "USA",
      $$hashKey: "object:550",
    },
  ],
  types: [
    "street_address",
    "geocode",
  ],
}
`

And the **response place** is:
`
{
  address_components: [
    {
      long_name: "26-19",
      short_name: "26-19",
      types: [
        "street_number",
      ],
    },
    {
      long_name: "Seagirt Boulevard",
      short_name: "Seagirt Blvd",
      types: [
        "route",
      ],
    },
    {
      long_name: "Far Rockaway",
      short_name: "Far Rockaway",
      types: [
        "neighborhood",
        "political",
      ],
    },
    {
      long_name: "Queens",
      short_name: "Queens",
      types: [
        "sublocality_level_1",
        "sublocality",
        "political",
      ],
    },
    {
      long_name: "Queens County",
      short_name: "Queens County",
      types: [
        "administrative_area_level_2",
        "political",
      ],
    },
    {
      long_name: "New York",
      short_name: "NY",
      types: [
        "administrative_area_level_1",
        "political",
      ],
    },
    {
      long_name: "United States",
      short_name: "US",
      types: [
        "country",
        "political",
      ],
    },
    {
      long_name: "11691",
      short_name: "11691",
      types: [
        "postal_code",
      ],
    },
  ],
  adr_address: "<span class=\"street-address\">26-19 Seagirt Blvd</span>, <span class=\"locality\">Far Rockaway</span>, <span class=\"region\">NY</span> <span class=\"postal-code\">11691</span>, <span class=\"country-name\">USA</span>",
  formatted_address: "26-19 Seagirt Blvd, Far Rockaway, NY 11691, USA",
  geometry: {
    location: {
      lat: function(){return d},
      lng: function(){return e},
    },
    viewport: {
      yb: {
        g: 40.5947370197085,
        h: 40.5974349802915,
      },
      Pa: {
        g: -73.76123848029151,
        h: -73.75854051970849,
      },
    },
  },
  icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png",
  icon_background_color: "#7B9EB0",
  icon_mask_base_uri: "https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet",
  name: "26-19 Seagirt Blvd",
  place_id: "Ei8yNi0xOSBTZWFnaXJ0IEJsdmQsIEZhciBSb2NrYXdheSwgTlkgMTE2OTEsIFVTQSJQEk4KNAoyCdXWMGGlaMKJEXfPrK33rleaGh4LEO7B7qEBGhQKEgkNmfd1omjCiRFXlgKc8tqY6AwQEyoUChIJZT3RLqxowokRUKML36zkbls",
  reference: "Ei8yNi0xOSBTZWFnaXJ0IEJsdmQsIEZhciBSb2NrYXdheSwgTlkgMTE2OTEsIFVTQSJQEk4KNAoyCdXWMGGlaMKJEXfPrK33rleaGh4LEO7B7qEBGhQKEgkNmfd1omjCiRFXlgKc8tqY6AwQEyoUChIJZT3RLqxowokRUKML36zkbls",
  types: [
    "street_address",
  ],
  url: "https://maps.google.com/?q=26-19+Seagirt+Blvd,+Far+Rockaway,+NY+11691,+USA&ftid=0x89c268a56130d6d5:0xd4096708949a1bfb",
  utc_offset: -240,
  vicinity: "Queens",
  html_attributions: [
  ],
  utc_offset_minutes: -240,
}
`

Expected result, "19-15 Seagirt Blvd, Far Rockaway, NY 11691, USA" in the response place as well.

See video of the bug
https://www.loom.com/share/5d33423fc4724873a1941d445a82244c

Please fix or explain as soon as possible.

**Comment by jpoehnelt** [comment]
Seems like an issue with that https://github.com/kuhnza/angular-google-places-autocomplete and unrelated to this NodeJS client library.
