### ISSUE TITLE
Maps: Error: export 'URL' (imported as 'URL') was not found in 'url'

### ISSUE THREAD

**Issue by xinthose** [googlemaps/google-maps-services-js#702]
#### Environment details

1. OS: Windows 10
2. Library version: 3.3.1
3. Node version: 14.17.3

#### Steps to reproduce

  1. `npm i @googlemaps/google-maps-services-js@latest`
  2. `ng build`

#### Error
3-4 lines of the following:
```
./node_modules/@googlemaps/url-signature/dist/index.esm.js:50:26-29 - Error: export 'URL' (imported as 'URL') was not found in 'url' (possible exports: Url, format, parse, resolve, resolveObject)
```

#### ng version
```
Angular CLI: 13.0.2
Node: 14.17.3
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.2.13
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.13
@angular-devkit/build-angular   12.2.13
@angular-devkit/core            12.2.13
@angular-devkit/schematics      12.2.13
@angular/cli                    13.0.2 (cli-only)
@angular/language-service       <error>
@schematics/angular             9.1.15
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by xinthose** [comment]
after running `npm i @googlemaps/google-maps-services-js@3.2.5`, my app builds again

**Comment by jpoehnelt** [comment]
Probably introduced in https://github.com/googlemaps/google-maps-services-js/releases/tag/v3.3.0. I have a fix in https://github.com/googlemaps/js-url-signature/pull/28 to generalize for both browser and node environments. 

Please note that this library isn't really compatible with browser environments and you are likely unable to make the request that you want. Instead use the [Google Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/overview) loaded with [@googlemaps/js-api-loader](https://www.npmjs.com/package/@googlemaps/js-api-loader) to make a call to the services ([ref docs](https://developers.google.com/maps/documentation/javascript/reference)).

**Comment by jpoehnelt** [comment]
To expand on the why... most of the endpoints do not support the necessary CORS headers to make requests from the browser. https://github.com/googlemaps/google-maps-services-js/issues?q=is%3Aissue+CORS+

**Comment by xinthose** [comment]
@jpoehnelt I see. Thank you sir.
