### ISSUE TITLE
Memory issue in node application

### ISSUE THREAD

**Issue by priidikvaikla** [googlemaps/google-maps-services-js#71]
Hey guys,

I'm using this library v0.3.1 in a node v6.9.5 application. Actually the application runs inside docker container but I'm able to reproduce the problem with following script. The script is
```javascript
'use strict';

const googleMapsClient = require('@google/maps').createClient({
  key: '...'
});

setInterval(() => {
  googleMapsClient.geocode({
    address: '1600 Amphitheatre Parkway, Mountain View, CA'
  }, function(err, response) {
    if (!err) {
      console.log(response.json.results[0].formatted_address);
    }
  });
}, 2000);
```
and I see memory increasing as every new address gets geocoded. Is it supposed to increase like this or am I doing something in a wrong way? Memory heap snapshots are here [Heap.zip](https://github.com/googlemaps/google-maps-services-js/files/811680/Heap.zip)

**Comment by priidikvaikla** [comment]
The other thing was that I was thinking that maybe it's more GC issue in node so I set --max-old-space-size= limit and it seemed that more memory was freed but it still went over that limit eventually

**Comment by priidikvaikla** [comment]
@stephenfarrar @stephenmcd Is there any way you could look into this issue?

**Comment by jaumebn** [comment]
Hi!

I am experiencing the same issue here. Every time a call to `googleMapsClient` is performed, the memory usage keeps increasing and increasing. I had a script to geocode 35k addresses and it runs out of memory (1GB+) before reaching 40% of addresses processed. I am not sure if it is safe to use this client in production as after some hours running it would be using tons of memory.

If if `require` the googleMaps client again every 100 calls, memory usage keeps at reasonable levels. However, I don't think this is a good solution for production environments. Any advise on this?

Thanks!

**Comment by kilpa** [comment]
When looking trough the heapdumps I saw that in some array lots of objects are held, and found out that those objects refer to some kind of buffer. It looks like that https://github.com/googlemaps/google-maps-services-js/blob/d706e5f567280e0ff032dc272a969cdcdd9eaaf8/lib/internal/circular-buffer.js#L19 this array is filled for every request but never cleaned up after usage.

**Comment by priidikvaikla** [comment]
This seems not to be the issue because the size of that items array doesn't go beyond the [size](https://github.com/googlemaps/google-maps-services-js/blob/d706e5f567280e0ff032dc272a969cdcdd9eaaf8/lib/internal/circular-buffer.js#L18) which is 10 by default. Any other ideas?

**Comment by stephenfarrar** [comment]
Thanks for reporting. I'll take a look...
