### ISSUE TITLE
Adding locations after use of Quick Builder

### ISSUE THREAD

**Issue by Roosjeva** [googlemaps/google-maps-services-js#729]
Hi, 

Last week i've been working on a store locator. 
I used the quick builder to implement all store locations, unfortunately, I've forgotten a few and came to the problem that I can not find how to add new locations with the Quick Builder, till so far I only see the option to make a new link which takes me a lot of time to type in all the stores again. 

My question therefore is: is there a possibility that I can easily add new stores to my store locator, and that I don't have to re-enter all the addresses? 

I am waiting for your response and hope you can help

Kind Regards

**Comment by jpoehnelt** [comment]
Please open a feature request at https://issuetracker.google.com/issues/new?component=188853&template=787814. You may be able to edit the html/js directly that you embedded in your website.

I'm closing this here since it is not related to this library.

**Comment by jpoehnelt** [comment]
Looks like you already opened this elsewhere at https://issuetracker.google.com/212373767.

**Comment by Roosjeva** [comment]
Yes was that what you meant?
