### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by rg-galieva** [googlemaps/google-maps-services-js#73]
Any ideas how to solve CORS restrictions?
Code below throws "No 'Access-Control-Allow-Origin' header is present on the requested resource." Key is correct. Outside of my app I see the correct json-response. It doesn't work with localhost (webpack-dev-server with correct headers settings), and the same issue with production server.

```
const googleMapsClient = require('@google/maps').createClient({
    key: API_KEY
});

const getTest = () => {
        googleMapsClient.placesNearby({
                radius: 100,
                type: 'city_hall,museum',
                location: '59.922329,30.22241'
        }, function(err, response) {
            if (!err) {
                console.log(response.json());
            }
        });
}
```

**Comment by stephenmcd** [comment]
See https://github.com/googlemaps/google-maps-services-js/issues/59#issuecomment-282595007
