### ISSUE TITLE
Optimize route option using Directions Service work incorrect

### ISSUE THREAD

**Issue by khuongtnq** [googlemaps/google-maps-services-js#738]
Hello guys,
I have a problem when using google maps directions services find route with optimize route option
optimize_route = false -> total route is 21km
optimize_route = true -> total route is 23km
I turned off avoid options, I double-checked after optimizing routes, the total route is larger than.

---
**Document** 
Discover additional support services for the Google Maps Services
https://developers.google.com/maps/documentation/javascript/directions

---

#### Steps to reproduce

  This is list of locations happens the error:
```
[
    {
        "latitude": 10.800841255712163,
        "longitude": 106.65971765401387,
        "name": "55 Cộng Hòa, Phường 4, Tân Bình, Thành phố Hồ Chí Minh, Vietnam"
    },
    {
        "latitude": 10.803370415360932,
        "longitude": 106.74190473390459,
        "name": "159 Xa lộ Hà Nội, Thảo Điền, Quận 2, Thành phố Hồ Chí Minh, Vietnam"
    },
    {
        "latitude": 10.775968596574188,
        "longitude": 106.75271940065264,
        "name": "11 Lê Hiến Mai, Phường Thạnh Mỹ Lợi, Quận 2, Thành phố Hồ Chí Minh 70000, Vietnam"
    },
    {
        "latitude": 10.780943266091418,
        "longitude": 106.73366498781084,
        "name": "QPJM+4VJ, Phường Bình Khánh, Quận 2, Thành phố Hồ Chí Minh, Vietnam"
    }
]
```

#### Code example

```jsx

const request = {
    origin: routes.first().location,
    destination: routes.get(farestIndex(locationsTemp)).location,
    waypoints: routes.splice(0, 1).toJS(),
    optimizeWaypoints: true,
    avoidHighways: keyAvoidRoute.avoidHighways,
    avoidTolls: keyAvoidRoute.avoidTolls,
    avoidFerries: keyAvoidRoute.avoidFerries,
    travelMode: currentVehicleType.settings.travel_mode.toUpperCase()
  }
directionsService.route(request, (response) => {
      dispatch(handleOptimizeLocations(response, {
        locations,
        locationsTemp,
        prevLocations,
        roundTripDiscount,
        callback,
      }))
    })
```

**if use optimize route option, the 2 last locations are swapped positions, which makes the error**
***Locations belongs to Vietnam**

Has anyone had this problem before?

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jpoehnelt** [comment]
Please open this bug at https://issuetracker.google.com/issues/new?component=188841&template=787416 as it is not related to this library. Thanks!
