### ISSUE TITLE
how to restrict multiple countries in placeAutoComplete?

### ISSUE THREAD

**Issue by zbobyuan** [googlemaps/google-maps-services-js#76]
via google map api guide https://developers.google.com/places/web-service/autocomplete :

For example: components=country:us|country:pr|country:vi|country:gu|country:mp would restrict your results to places within the United States and its unincorporated organized territories.

but I cannot figure out how to pass multiple countries to the components parameter.
I tried {
...
components:['country:us','country:ca']
}, doesn't work.

**Comment by zbobyuan** [comment]
I read the code and figured it out, use the 3rd parameter customParams, thanks.

**Comment by dkirsanov** [comment]
You could build query like this:
`var query = {input, type: 'address', language: 'en', components: {country: "us"}};`

**Comment by duzenko** [comment]
@zbobyuan 
Do you mind sharing your discovery with us?
