### ISSUE TITLE
.directions not allowing 'traffic_model' param

### ISSUE THREAD

**Issue by jordandreassen** [googlemaps/google-maps-services-js#82]
I am able to make a request and get a response just fine omitting this parameter. However, including 'traffic_model: '<value>'' does not work, and results in the generic 'InvalidValueError'. <value> can be any of the available options (pessimistic, optimistic, best_guess)

**Comment by stephenmcd** [comment]
Can you post some sample code that reproduces the problem?

**Comment by jordandreassen** [comment]
Solved it! Looking through the source code 'traffic_model' requires 'departure_time' and i was using 'arrival_time'. Thanks.

**Comment by stephenmcd** [comment]
Thanks for the update. That's strange though, if that was the issue you should have gotten a different error.
