### ISSUE TITLE
Allow presigned URLs for Place Photos

### ISSUE THREAD

**Issue by benshare** [googlemaps/google-maps-services-js#856]
We want to display Place photos on the frontend of our app. We're currently able to do that using the [standard request](https://developers.google.com/maps/documentation/places/web-service/photos#place_photo_example), but this forces us to include our API key on the frontend, which we'd like to avoid. Meanwhile, fetching the photo on the backend and then passing it to the frontend is expensive. Is there any support for generating presigned URLs using the API key to pass to the frontend?

**Comment by Harsh5chal** [comment]
Hi Benshare,
You can restrict your frontend API key by using HTTP refer and adding restrictions to the API key, including which service (Places) it can use and on which URL it should work. 
**"fetching the photo on the backend and then passing it to the frontend is expensive"**
By expensive you mean by time? You can create a separate service in the backend to do so. API cost would be the same for that.
No, you can't generate presigned URLs google won’t allow you.

For your reference: https://developers.google.com/maps/documentation/javascript/get-api-key#restrict_key

**Comment by benshare** [comment]
Hey Harsh5chal, thanks for the answer. Restricting to our app will work, I think that solves the security issue. Thanks for linking the relevant doc!

(By expensive, I just meant it's a lot faster to get a URL and pass that over HTTP then to have to download an entire image on the backend and send that to the frontend.)

**Comment by Harsh5chal** [comment]
Hi benshare,  How are you procuring the API despite I'm in the tech team but there is a consultancy team who will be able to guide you more on optimisations & cost and probably call on a private channel etc.
