### ISSUE TITLE
Ability to import saved lists

### ISSUE THREAD

**Issue by benshare** [googlemaps/google-maps-services-js#866]
Not sure if this is right place for this, but is there any way for a user to import a saved list from Google Maps? I haven't been able to find any information about this. Any guidance would be appreciated--thanks.

**Comment by benshare** [comment]
Would love some info on this!

**Comment by amuramoto** [comment]
Hi @benshare - this isn't supported at this time. There's no API for retrieving lists from the Google Maps app
