### ISSUE TITLE
Add request URL to response

### ISSUE THREAD

**Issue by yfr** [googlemaps/google-maps-services-js#88]
We use the google maps services to geocode a lot of addresses. To debug failures it is important that we have the original request URL with which the call was made. 

I know it is possible and would open a PR for this (currently having issues signing the CLA for our company).

Is it something you would add?

**Comment by stephenfarrar** [comment]
You could achieve this by:
1. Get the `makeUrlRequest()` function from `lib/internal/make-url-request`. This function is given the URL.
2. Make a wrapper function that logs the URL, and calls through.
3. Supply your wrapper function when you construct the client object like this
```
createClient({
  makeUrlRequest: myWrappedMakeUrlRequest,
  key: MY_KEY,
});
```

**Comment by yfr** [comment]
Oh, Thanks. Did not know that I can wrap the functions. Will try.
