### ISSUE TITLE
Add instructions for `asPromise()` to documentation

### ISSUE THREAD

**Issue by DaddyWarbucks** [googlemaps/google-maps-services-js#89]
I could not find in the documentation how to properly use promises after initializing the client with a promise constructor. I, luckily, found a reference in an issue about something else.

It would be helpful to edit this line in the "Making API requests" part of the documentation:
```NOTE: Promises are only available if you supply a Promise constructor to the createClient() method.```

Something along the lines of: 
```NOTE: Promises are only available if you supply a Promise constructor to the createClient() method. You must also chain .asPromise() to the method before any .then() or .catch() methods.```

I would be happy to make this change. Should I open a PR?

Thanks!

**Comment by stephenmcd** [comment]
> I would be happy to make this change. Should I open a PR?

That would be awesome, thank you.
