### ISSUE TITLE
Having the option of getting different routes for different types of road vehicles

### ISSUE THREAD

**Issue by nakulBageja** [googlemaps/google-maps-services-js#895]
Problem Statement - Getting the suggested shortest routes unsuitable for 4-wheel vehicles. Sometimes to provide the shorted path to the user, Google Maps offers a route that is very narrow and thus causes the user to have more confusion rather than easiness.

Solution - Getting the user input about which vehicle it's driving and then suggesting the best route for the vehicle type.

**Comment by amuramoto** [comment]
Please open a feature request for the Directions API in the [public issue tracker](https://issuetracker.google.com/issues/new?component=188841&template=789306)
