### ISSUE TITLE
Support for place_type "Rest Area"

### ISSUE THREAD

**Issue by suvvenndu** [googlemaps/google-maps-services-js#898]
While visiting the link for [place types,](https://developers.google.com/maps/documentation/places/web-service/supported_types 
 ), unable to find a type for "rest area" when planning a drive.

This will be helpfull for number of apps.

**Comment by amuramoto** [comment]
Please open a feature request in the Places API [public issue tracker](https://issuetracker.google.com/issues/new?component=188872&template=789309).
