### ISSUE TITLE
Google places autocomplete does not accept types

### ISSUE THREAD

**Issue by atharvajohri** [googlemaps/google-maps-services-js#92]
When i add the `types` parameter to a places autocomplete request, it throws an `InvalidValueError` error.

```
googleMapsClient.placesAutoComplete({
     input: locationHint,
     language: 'en',
     types: '(cities)'
})
```

Shows:
```
 name: 'InvalidValueError',
 message: 'unexpected property "types"',
```

Types is a valid parameter as per https://developers.google.com/places/web-service/autocomplete?authuser=1#place_types

**Comment by stephenmcd** [comment]
Types field was deprecated from feb 16 and stops working in feb 17, so it's not included in this client library. Thanks for raising this - we need to update the docs.

**Comment by atharvajohri** [comment]
@stephenmcd that's not true. `types` is a valid optional parameter for the Place Autocomplete service. It has only been deprecated for Place Search api.

**Comment by stephenmcd** [comment]
You're right, thank you.

**Comment by stephenmcd** [comment]
You're right, thank you.
