### ISSUE TITLE
geocode: components and componentRestrictions

### ISSUE THREAD

**Issue by jorrit** [googlemaps/google-maps-services-js#94]
The Geocode JS API defines the `componentRestrictions` key in the GeocoderRequest object [1]. The geocode method of this API client does not allow this key, but has the `components` key which seems to have the same function. I am wondering if the `components` key should be renamed to `componentRestrictions` in geocode.js.

[1] https://developers.google.com/maps/documentation/javascript/reference#GeocoderRequest

**Comment by stephenmcd** [comment]
You're looking at the documentation for the client-side JS library which is unrelated to this GitHub repo. 

This is the Node JS client library for using the Google Maps Web Services, which is documented here: https://developers.google.com/maps/documentation/geocoding/intro#geocoding (you'll see there the param is named `components`).

**Comment by jorrit** [comment]
I see. Thanks for your time!
