### ISSUE TITLE
Promise constructor example

### ISSUE THREAD

**Issue by G-Rath** [googlemaps/google-maps-services-js#99]
In regards to #89, I think it would be best to have an actual example of what a 'supply a Promise constructor to the createClient() method' actually looks like. 

Personally I'm a little confused as to what I'm meant to do: How do I 'supply' a promise constructor? 

Ultimately I think any confusion around how to use Promises with this library can be solved by simply providing an example.

**Comment by G-Rath** [comment]
I figured out that the answer is rather simple: It's just a matter of doing

```
const google = (require('@google/maps').createClient({
    key: GOOGLE_API_KEY,
    Promise
}));
```

But I still think that an example would go a long way.

**Comment by G-Rath** [comment]
The current geocode examples are also wrong: 

```
// Geocode an address.
googleMapsClient.geocode({
  address: '1600 Amphitheatre Parkway, Mountain View, CA'
}, function(err, response) {
  if (!err) {
    console.log(response.json.results);
  }
});
```

The object returned by google doesn't have a `results` property.

**Comment by nickhaughton** [comment]
+1, weird that for something explained poorly there is no example.

**Comment by stephenmcd** [comment]
#103

**Comment by chrissyast** [comment]
@G-Rath So is it literally just the word "Promise" that needs to go there?

**Comment by G-Rath** [comment]
@chrissyast 

Short answer: yes :)

Long answer: `Promise` is a property that takes an object (called a "thenable") that implements the [`Promise/A+` specification](https://promisesaplus.com/), such as `window.Promise`, or [`Bluebird`](https://www.npmjs.com/package/bluebird).

Since the "native" Promise implementation is called `Promise`, you can use [ES6 shorthand](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#New_notations_in_ECMAScript_2015) notation when passing it in.

Typically, when polyfilling `Promise` you'd do so globally, so this will generally always work - However there are times where you might not want to do that, such as in a library to be consumed by others, where you'd not want to override whatever the consumer is doing. 

In that case you'd do something like:

```
(require('@google/maps').createClient({
    key: GOOGLE_API_KEY,
    Promise: require("bluebird")
}))
```

----

On an aside, the whole reason I made this issue, and found it confusing is b/c there are a couple of different ways to create Promises, and it's always good to be clear :)
